/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos;

import static com.google.genai.gaos.operations.Operations.RequestOperation;

import com.google.genai.gaos.models.operations.CreateAgentRequest;
import com.google.genai.gaos.models.operations.CreateAgentRequestBuilder;
import com.google.genai.gaos.models.operations.CreateAgentResponse;
import com.google.genai.gaos.models.operations.DeleteAgentRequest;
import com.google.genai.gaos.models.operations.DeleteAgentRequestBuilder;
import com.google.genai.gaos.models.operations.DeleteAgentResponse;
import com.google.genai.gaos.models.operations.GetAgentRequest;
import com.google.genai.gaos.models.operations.GetAgentRequestBuilder;
import com.google.genai.gaos.models.operations.GetAgentResponse;
import com.google.genai.gaos.models.operations.ListAgentsRequest;
import com.google.genai.gaos.models.operations.ListAgentsRequestBuilder;
import com.google.genai.gaos.models.operations.ListAgentsResponse;
import com.google.genai.gaos.operations.CreateAgent;
import com.google.genai.gaos.operations.DeleteAgent;
import com.google.genai.gaos.operations.GetAgent;
import com.google.genai.gaos.operations.ListAgents;
import com.google.genai.gaos.utils.Headers;
import com.google.genai.gaos.utils.Options;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;


public class Agents {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncAgents asyncSDK;

    Agents(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncAgents(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncAgents async() {
        return asyncSDK;
    }

    /**
     * Creates a new Agent (Typed version for SDK).
     * 
     * @return The call builder
     */
    public CreateAgentRequestBuilder create() {
        return new CreateAgentRequestBuilder(sdkConfiguration);
    }

    /**
     * Creates a new Agent (Typed version for SDK).
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateAgentResponse create(@Nonnull CreateAgentRequest request) {
        return create(request, null);
    }

    /**
     * Creates a new Agent (Typed version for SDK).
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateAgentResponse create(@Nonnull CreateAgentRequest request, @Nullable Options options) {
        RequestOperation<CreateAgentRequest, CreateAgentResponse> operation
              = new CreateAgent.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Lists all Agents.
     * 
     * @return The call builder
     */
    public ListAgentsRequestBuilder list() {
        return new ListAgentsRequestBuilder(sdkConfiguration);
    }

    /**
     * Lists all Agents.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListAgentsResponse list(@Nonnull ListAgentsRequest request) {
        return list(request, null);
    }

    /**
     * Lists all Agents.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListAgentsResponse list(@Nonnull ListAgentsRequest request, @Nullable Options options) {
        RequestOperation<ListAgentsRequest, ListAgentsResponse> operation
              = new ListAgents.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Gets a specific Agent.
     * 
     * @return The call builder
     */
    public GetAgentRequestBuilder get() {
        return new GetAgentRequestBuilder(sdkConfiguration);
    }

    /**
     * Gets a specific Agent.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetAgentResponse get(@Nonnull GetAgentRequest request) {
        return get(request, null);
    }

    /**
     * Gets a specific Agent.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetAgentResponse get(@Nonnull GetAgentRequest request, @Nullable Options options) {
        RequestOperation<GetAgentRequest, GetAgentResponse> operation
              = new GetAgent.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Deletes an Agent.
     * 
     * @return The call builder
     */
    public DeleteAgentRequestBuilder delete() {
        return new DeleteAgentRequestBuilder(sdkConfiguration);
    }

    /**
     * Deletes an Agent.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public DeleteAgentResponse delete(@Nonnull DeleteAgentRequest request) {
        return delete(request, null);
    }

    /**
     * Deletes an Agent.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public DeleteAgentResponse delete(@Nonnull DeleteAgentRequest request, @Nullable Options options) {
        RequestOperation<DeleteAgentRequest, DeleteAgentResponse> operation
              = new DeleteAgent.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
