/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos;

import com.google.genai.gaos.utils.Headers;

/**
 * Gemini API: The Gemini Interactions API allows developers to build generative AI applications using
 * Gemini models. Gemini is our most capable model, built from the ground up to be multimodal. It can
 * generalize and seamlessly understand, operate across, and combine different types of information
 * including language, images, audio, video, and code.
 * 
 * <p>You can use the Gemini API for use cases like reasoning across text and images, content generation,
 * dialogue agents, summarization and classification systems, and more.
 */
@SuppressWarnings("all")
public class AsyncGenAI {
    private static final Headers _headers = Headers.EMPTY;

    private final AsyncInteractions interactions;

    private final AsyncWebhooks webhooks;

    private final AsyncAgents agents;

    public AsyncInteractions interactions() {
        return interactions;
    }

    public AsyncWebhooks webhooks() {
        return webhooks;
    }

    public AsyncAgents agents() {
        return agents;
    }

    private final SDKConfiguration sdkConfiguration;
    private final GenAI syncSDK;

    AsyncGenAI(GenAI syncSDK, SDKConfiguration sdkConfiguration) {
        this.syncSDK = syncSDK;
        this.sdkConfiguration = sdkConfiguration;
        this.interactions = new AsyncInteractions(syncSDK.interactions(), sdkConfiguration);
        this.webhooks = new AsyncWebhooks(syncSDK.webhooks(), sdkConfiguration);
        this.agents = new AsyncAgents(syncSDK.agents(), sdkConfiguration);
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public GenAI sync() {
        return syncSDK;
    }
}
