/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos;

import com.google.genai.gaos.hooks.SDKHooks;
import com.google.genai.gaos.utils.AsyncHooks;
import com.google.genai.gaos.utils.Globals;
import com.google.genai.gaos.utils.HTTPClient;
import com.google.genai.gaos.utils.Hooks;
import com.google.genai.gaos.utils.RetryConfig;
import com.google.genai.gaos.utils.SpeakeasyHTTPClient;
import com.google.genai.gaos.utils.Utils;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;

@SuppressWarnings("all")
public class SDKConfiguration {

    private static final String LANGUAGE = "java";
    public static final String OPENAPI_DOC_VERSION = "v1beta";
    public static final String SDK_VERSION = "0.1.0";
    public static final String GEN_VERSION = "2.913.3";
    private static final String BASE_PACKAGE = "com.google.genai.gaos";
    public static final String USER_AGENT = 
            String.format("speakeasy-sdk/%s %s %s %s %s",
                LANGUAGE, SDK_VERSION, GEN_VERSION, OPENAPI_DOC_VERSION, BASE_PACKAGE);

    private SecuritySource securitySource = SecuritySource.of(null);
    
    public SecuritySource securitySource() {
        return securitySource;
    }
    
    public void setSecuritySource(SecuritySource securitySource) {
        Utils.checkNotNull(securitySource, "securitySource");
        this.securitySource = securitySource;
    }
    
    private HTTPClient client = new SpeakeasyHTTPClient();
    
    public HTTPClient client() {
        return client;
    }
    
    public void setClient(HTTPClient client) {
        Utils.checkNotNull(client, "client");
        this.client = client;
    }
    
    private String serverUrl;
    
    public String serverUrl() {
        return serverUrl;
    }
    
    public void setServerUrl(String serverUrl) {
        Utils.checkNotNull(serverUrl, "serverUrl");
        this.serverUrl = trimFinalSlash(serverUrl);
    }
    
    private static String trimFinalSlash(String url) {
        if (url == null) {
            return null;
        } else if (url.endsWith("/")) {
            return url.substring(0, url.length() - 1);
        } else  {
            return url;
        }
    }
    
    public String resolvedServerUrl() {
        return serverUrl;
    }
    
    private int serverIdx = 0;
    
    public void setServerIdx(int serverIdx) {
        this.serverIdx = serverIdx;
    }
    
    public int serverIdx() {
        return serverIdx;
    }
    
    
    private Hooks _hooks = createHooks();

    private static Hooks createHooks() {
        Hooks hooks = new Hooks();
        return hooks;
    }
    
    public Hooks hooks() {
        return _hooks;
    }

    public void setHooks(Hooks hooks) {
        this._hooks = hooks;
    }

    /**
     * Initializes state (for example hooks).
     **/
    public void initialize() {
        SDKHooks.initialize(_hooks);
        SDKHooks.initialize(_asyncHooks);
    }

    @SuppressWarnings("serial")
    public Globals globals = new Globals();
    
    private Optional<RetryConfig> retryConfig = Optional.empty();
    
    public Optional<RetryConfig> retryConfig() {
        return retryConfig;
    }

    public void setRetryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
    }
    private ScheduledExecutorService retryScheduler = Executors.newSingleThreadScheduledExecutor();
    
    public ScheduledExecutorService retryScheduler() {
        return retryScheduler;
    }

    public void setAsyncRetryScheduler(ScheduledExecutorService retryScheduler) {
        Utils.checkNotNull(retryScheduler, "retryScheduler");
        this.retryScheduler = retryScheduler;
    }

    private AsyncHooks _asyncHooks = new AsyncHooks();

    public AsyncHooks asyncHooks() {
        return _asyncHooks;
    }

    public void setAsyncHooks(AsyncHooks asyncHooks) {
        Utils.checkNotNull(asyncHooks, "asyncHooks");
        this._asyncHooks = asyncHooks;
    }
}
