/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos;

import static com.google.genai.gaos.operations.Operations.RequestOperation;

import com.google.genai.gaos.models.operations.CreateTriggerRequest;
import com.google.genai.gaos.models.operations.CreateTriggerRequestBuilder;
import com.google.genai.gaos.models.operations.CreateTriggerResponse;
import com.google.genai.gaos.models.operations.DeleteTriggerRequest;
import com.google.genai.gaos.models.operations.DeleteTriggerRequestBuilder;
import com.google.genai.gaos.models.operations.DeleteTriggerResponse;
import com.google.genai.gaos.models.operations.GetTriggerRequest;
import com.google.genai.gaos.models.operations.GetTriggerRequestBuilder;
import com.google.genai.gaos.models.operations.GetTriggerResponse;
import com.google.genai.gaos.models.operations.ListTriggerExecutionsRequest;
import com.google.genai.gaos.models.operations.ListTriggerExecutionsRequestBuilder;
import com.google.genai.gaos.models.operations.ListTriggerExecutionsResponse;
import com.google.genai.gaos.models.operations.ListTriggersRequest;
import com.google.genai.gaos.models.operations.ListTriggersRequestBuilder;
import com.google.genai.gaos.models.operations.ListTriggersResponse;
import com.google.genai.gaos.models.operations.RunTriggerRequest;
import com.google.genai.gaos.models.operations.RunTriggerRequestBuilder;
import com.google.genai.gaos.models.operations.RunTriggerResponse;
import com.google.genai.gaos.models.operations.UpdateTriggerRequest;
import com.google.genai.gaos.models.operations.UpdateTriggerRequestBuilder;
import com.google.genai.gaos.models.operations.UpdateTriggerResponse;
import com.google.genai.gaos.operations.CreateTrigger;
import com.google.genai.gaos.operations.DeleteTrigger;
import com.google.genai.gaos.operations.GetTrigger;
import com.google.genai.gaos.operations.ListTriggerExecutions;
import com.google.genai.gaos.operations.ListTriggers;
import com.google.genai.gaos.operations.RunTrigger;
import com.google.genai.gaos.operations.UpdateTrigger;
import com.google.genai.gaos.utils.Headers;
import com.google.genai.gaos.utils.Options;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;


public class Triggers {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncTriggers asyncSDK;

    Triggers(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncTriggers(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncTriggers async() {
        return asyncSDK;
    }

    /**
     * Creates a new trigger that will invoke the specified agent on the given cron schedule.
     * 
     * @return The call builder
     */
    public CreateTriggerRequestBuilder create() {
        return new CreateTriggerRequestBuilder(sdkConfiguration);
    }

    /**
     * Creates a new trigger that will invoke the specified agent on the given cron schedule.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateTriggerResponse create(@Nonnull CreateTriggerRequest request) {
        return create(request, null);
    }

    /**
     * Creates a new trigger that will invoke the specified agent on the given cron schedule.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateTriggerResponse create(@Nonnull CreateTriggerRequest request, @Nullable Options options) {
        RequestOperation<CreateTriggerRequest, CreateTriggerResponse> operation
              = new CreateTrigger.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Lists triggers for a project.
     * 
     * @return The call builder
     */
    public ListTriggersRequestBuilder list() {
        return new ListTriggersRequestBuilder(sdkConfiguration);
    }

    /**
     * Lists triggers for a project.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListTriggersResponse list(@Nonnull ListTriggersRequest request) {
        return list(request, null);
    }

    /**
     * Lists triggers for a project.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListTriggersResponse list(@Nonnull ListTriggersRequest request, @Nullable Options options) {
        RequestOperation<ListTriggersRequest, ListTriggersResponse> operation
              = new ListTriggers.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Gets details of a single trigger.
     * 
     * @return The call builder
     */
    public GetTriggerRequestBuilder get() {
        return new GetTriggerRequestBuilder(sdkConfiguration);
    }

    /**
     * Gets details of a single trigger.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetTriggerResponse get(@Nonnull GetTriggerRequest request) {
        return get(request, null);
    }

    /**
     * Gets details of a single trigger.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetTriggerResponse get(@Nonnull GetTriggerRequest request, @Nullable Options options) {
        RequestOperation<GetTriggerRequest, GetTriggerResponse> operation
              = new GetTrigger.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Updates a trigger.
     * 
     * @return The call builder
     */
    public UpdateTriggerRequestBuilder update() {
        return new UpdateTriggerRequestBuilder(sdkConfiguration);
    }

    /**
     * Updates a trigger.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public UpdateTriggerResponse update(@Nonnull UpdateTriggerRequest request) {
        return update(request, null);
    }

    /**
     * Updates a trigger.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public UpdateTriggerResponse update(@Nonnull UpdateTriggerRequest request, @Nullable Options options) {
        RequestOperation<UpdateTriggerRequest, UpdateTriggerResponse> operation
              = new UpdateTrigger.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Deletes a trigger.
     * 
     * @return The call builder
     */
    public DeleteTriggerRequestBuilder delete() {
        return new DeleteTriggerRequestBuilder(sdkConfiguration);
    }

    /**
     * Deletes a trigger.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public DeleteTriggerResponse delete(@Nonnull DeleteTriggerRequest request) {
        return delete(request, null);
    }

    /**
     * Deletes a trigger.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public DeleteTriggerResponse delete(@Nonnull DeleteTriggerRequest request, @Nullable Options options) {
        RequestOperation<DeleteTriggerRequest, DeleteTriggerResponse> operation
              = new DeleteTrigger.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Runs a trigger immediately.
     * 
     * @return The call builder
     */
    public RunTriggerRequestBuilder run() {
        return new RunTriggerRequestBuilder(sdkConfiguration);
    }

    /**
     * Runs a trigger immediately.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public RunTriggerResponse run(@Nonnull RunTriggerRequest request) {
        return run(request, null);
    }

    /**
     * Runs a trigger immediately.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public RunTriggerResponse run(@Nonnull RunTriggerRequest request, @Nullable Options options) {
        RequestOperation<RunTriggerRequest, RunTriggerResponse> operation
              = new RunTrigger.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Lists executions for a trigger.
     * 
     * @return The call builder
     */
    public ListTriggerExecutionsRequestBuilder listExecutions() {
        return new ListTriggerExecutionsRequestBuilder(sdkConfiguration);
    }

    /**
     * Lists executions for a trigger.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListTriggerExecutionsResponse listExecutions(@Nonnull ListTriggerExecutionsRequest request) {
        return listExecutions(request, null);
    }

    /**
     * Lists executions for a trigger.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListTriggerExecutionsResponse listExecutions(@Nonnull ListTriggerExecutionsRequest request, @Nullable Options options) {
        RequestOperation<ListTriggerExecutionsRequest, ListTriggerExecutionsResponse> operation
              = new ListTriggerExecutions.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
