handleGHRelease: true
manifest: true
releaseType: maven
bumpMinorPreMajor: true

branches:
  - branch: main-mirror
    releaseType: maven
    handleGHRelease: true
    manifest: true
    manifestFile: pom.xml
    manifestConfig: release-please-config.json
