/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.webhooks;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * WebhookState
 * 
 * <p>Output only. The state of the webhook.
 */
public class WebhookState {

    public static final WebhookState ENABLED = new WebhookState("enabled");
    public static final WebhookState DISABLED = new WebhookState("disabled");
    public static final WebhookState DISABLED_DUE_TO_FAILED_DELIVERIES = new WebhookState("disabled_due_to_failed_deliveries");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, WebhookState> values = createValuesMap();
    private static final Map<String, WebhookStateEnum> enums = createEnumsMap();

    private final String value;

    private WebhookState(String value) {
        this.value = value;
    }

    /**
     * Returns a WebhookState with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as WebhookState
     */ 
    @JsonCreator
    public static WebhookState of(String value) {
        synchronized (WebhookState.class) {
            return values.computeIfAbsent(value, v -> new WebhookState(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<WebhookStateEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        WebhookState other = (WebhookState) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "WebhookState [value=" + value + "]";
    }

    // return an array just like an enum
    public static WebhookState[] values() {
        synchronized (WebhookState.class) {
            return values.values().toArray(new WebhookState[] {});
        }
    }

    private static final Map<String, WebhookState> createValuesMap() {
        Map<String, WebhookState> map = new LinkedHashMap<>();
        map.put("enabled", ENABLED);
        map.put("disabled", DISABLED);
        map.put("disabled_due_to_failed_deliveries", DISABLED_DUE_TO_FAILED_DELIVERIES);
        return map;
    }

    private static final Map<String, WebhookStateEnum> createEnumsMap() {
        Map<String, WebhookStateEnum> map = new HashMap<>();
        map.put("enabled", WebhookStateEnum.ENABLED);
        map.put("disabled", WebhookStateEnum.DISABLED);
        map.put("disabled_due_to_failed_deliveries", WebhookStateEnum.DISABLED_DUE_TO_FAILED_DELIVERIES);
        return map;
    }
    
    
    public enum WebhookStateEnum {

        ENABLED("enabled"),
        DISABLED("disabled"),
        DISABLED_DUE_TO_FAILED_DELIVERIES("disabled_due_to_failed_deliveries"),;

        private final String value;

        private WebhookStateEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

