/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.webhooks;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * WebhookRotateSigningSecretResponse
 * 
 * <p>Response message for WebhookService.RotateSigningSecret.
 */
@SuppressWarnings("all")
public class WebhookRotateSigningSecretResponse {
    /**
     * Output only. The newly generated signing secret.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("secret")
    private Optional<String> secret;

    @JsonCreator
    public WebhookRotateSigningSecretResponse(
            @JsonProperty("secret") Optional<String> secret) {
        Utils.checkNotNull(secret, "secret");
        this.secret = secret;
    }
    
    public WebhookRotateSigningSecretResponse() {
        this(Optional.empty());
    }

    /**
     * Output only. The newly generated signing secret.
     */
    @JsonIgnore
    public Optional<String> secret() {
        return secret;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Output only. The newly generated signing secret.
     */
    public WebhookRotateSigningSecretResponse withSecret(String secret) {
        Utils.checkNotNull(secret, "secret");
        this.secret = Optional.ofNullable(secret);
        return this;
    }


    /**
     * Output only. The newly generated signing secret.
     */
    public WebhookRotateSigningSecretResponse withSecret(Optional<String> secret) {
        Utils.checkNotNull(secret, "secret");
        this.secret = secret;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WebhookRotateSigningSecretResponse other = (WebhookRotateSigningSecretResponse) o;
        return 
            Utils.enhancedDeepEquals(this.secret, other.secret);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            secret);
    }
    
    @Override
    public String toString() {
        return Utils.toString(WebhookRotateSigningSecretResponse.class,
                "secret", secret);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> secret = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Output only. The newly generated signing secret.
         */
        public Builder secret(String secret) {
            Utils.checkNotNull(secret, "secret");
            this.secret = Optional.ofNullable(secret);
            return this;
        }

        /**
         * Output only. The newly generated signing secret.
         */
        public Builder secret(Optional<String> secret) {
            Utils.checkNotNull(secret, "secret");
            this.secret = secret;
            return this;
        }

        public WebhookRotateSigningSecretResponse build() {

            return new WebhookRotateSigningSecretResponse(
                secret);
        }

    }
}
