/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.credentials;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.google.genai.gaos.utils.LazySingletonValue;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * EnvironmentVariableConfig
 * 
 * <p>Configuration for environment variable credentials.
 */
public class EnvironmentVariableConfig implements CredentialCreateParams {

    @JsonProperty("id")
    private String id;

    /**
     * Required. Locations where the environment variable can be injected in
     * outgoing HTTP requests. Must contain at least one location.
     * Accepts either a single location (e.g. "header") or an array of locations.
     */
    @JsonProperty("injection_location")
    private EnvironmentVariableConfigInjectionLocation injectionLocation;

    /**
     * Optional. List of domains allowed to receive this environment variable
     * value in HTTP requests.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("trusted_domains")
    private List<String> trustedDomains;


    @JsonProperty("type")
    private String type;

    /**
     * Required. Input only. Secret value of the environment variable.
     * 
     * <p>Write-only; never
     * returned in responses.
     */
    @JsonProperty("value")
    private String value;

    @JsonCreator
    public EnvironmentVariableConfig(
            @JsonProperty("id") @Nonnull String id,
            @JsonProperty("injection_location") @Nonnull EnvironmentVariableConfigInjectionLocation injectionLocation,
            @JsonProperty("trusted_domains") @Nullable List<String> trustedDomains,
            @JsonProperty("value") @Nonnull String value) {
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.injectionLocation = Optional.ofNullable(injectionLocation)
            .orElseThrow(() -> new IllegalArgumentException("injectionLocation cannot be null"));
        this.trustedDomains = trustedDomains;
        this.type = Builder._SINGLETON_VALUE_Type.value();
        this.value = Optional.ofNullable(value)
            .orElseThrow(() -> new IllegalArgumentException("value cannot be null"));
    }
    
    public EnvironmentVariableConfig(
            @Nonnull String id,
            @Nonnull EnvironmentVariableConfigInjectionLocation injectionLocation,
            @Nonnull String value) {
        this(id, injectionLocation, null,
            value);
    }

    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * Required. Locations where the environment variable can be injected in
     * outgoing HTTP requests. Must contain at least one location.
     * Accepts either a single location (e.g. "header") or an array of locations.
     */
    public Optional<EnvironmentVariableConfigInjectionLocation> injectionLocation() {
        return Optional.ofNullable(this.injectionLocation);
    }

    /**
     * Optional. List of domains allowed to receive this environment variable
     * value in HTTP requests.
     */
    public Optional<List<String>> trustedDomains() {
        return Optional.ofNullable(this.trustedDomains);
    }

    @Override
    public String type() {
        return Utils.discriminatorToString(type);
    }

    /**
     * Required. Input only. Secret value of the environment variable.
     * 
     * <p>Write-only; never
     * returned in responses.
     */
    public Optional<String> value() {
        return Optional.ofNullable(this.value);
    }

    public static Builder builder() {
        return new Builder();
    }


    public EnvironmentVariableConfig withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    /**
     * Required. Locations where the environment variable can be injected in
     * outgoing HTTP requests. Must contain at least one location.
     * Accepts either a single location (e.g. "header") or an array of locations.
     */
    public EnvironmentVariableConfig withInjectionLocation(@Nonnull EnvironmentVariableConfigInjectionLocation injectionLocation) {
        this.injectionLocation = Utils.checkNotNull(injectionLocation, "injectionLocation");
        return this;
    }


    /**
     * Optional. List of domains allowed to receive this environment variable
     * value in HTTP requests.
     */
    public EnvironmentVariableConfig withTrustedDomains(@Nullable List<String> trustedDomains) {
        this.trustedDomains = trustedDomains;
        return this;
    }


    /**
     * Required. Input only. Secret value of the environment variable.
     * 
     * <p>Write-only; never
     * returned in responses.
     */
    public EnvironmentVariableConfig withValue(@Nonnull String value) {
        this.value = Utils.checkNotNull(value, "value");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EnvironmentVariableConfig other = (EnvironmentVariableConfig) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.injectionLocation, other.injectionLocation) &&
            Utils.enhancedDeepEquals(this.trustedDomains, other.trustedDomains) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.value, other.value);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, injectionLocation, trustedDomains,
            type, value);
    }
    
    @Override
    public String toString() {
        return Utils.toString(EnvironmentVariableConfig.class,
                "id", id,
                "injectionLocation", injectionLocation,
                "trustedDomains", trustedDomains,
                "type", type,
                "value", value);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private EnvironmentVariableConfigInjectionLocation injectionLocation;

        private List<String> trustedDomains;

        private String value;

        private Builder() {
          // force use of static builder() method
        }

        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        /**
         * Required. Locations where the environment variable can be injected in
         * outgoing HTTP requests. Must contain at least one location.
         * Accepts either a single location (e.g. "header") or an array of locations.
         */
        public Builder injectionLocation(@Nonnull EnvironmentVariableConfigInjectionLocation injectionLocation) {
            this.injectionLocation = Utils.checkNotNull(injectionLocation, "injectionLocation");
            return this;
        }

        /**
         * Optional. List of domains allowed to receive this environment variable
         * value in HTTP requests.
         */
        public Builder trustedDomains(@Nullable List<String> trustedDomains) {
            this.trustedDomains = trustedDomains;
            return this;
        }

        /**
         * Required. Input only. Secret value of the environment variable.
         * 
         * <p>Write-only; never
         * returned in responses.
         */
        public Builder value(@Nonnull String value) {
            this.value = Utils.checkNotNull(value, "value");
            return this;
        }

        public EnvironmentVariableConfig build() {
            return new EnvironmentVariableConfig(
                id, injectionLocation, trustedDomains,
                value);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_Type =
                new LazySingletonValue<>(
                        "type",
                        "\"environment_variable\"",
                        new TypeReference<String>() {});
    }
}
