/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.voices;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * ReplicatedVoice
 * 
 * <p>Input only. Parameters for replicated voice generation.
 * Required on input when `type` is `"replicated"`. Not returned in
 * responses.
 */
public class ReplicatedVoice {
    /**
     * Audio payload used for voice creation.
     */
    @JsonProperty("consent_audio")
    private AudioData consentAudio;

    /**
     * Audio payload used for voice creation.
     */
    @JsonProperty("source_audio")
    private AudioData sourceAudio;

    @JsonCreator
    public ReplicatedVoice(
            @JsonProperty("consent_audio") @Nonnull AudioData consentAudio,
            @JsonProperty("source_audio") @Nonnull AudioData sourceAudio) {
        this.consentAudio = Optional.ofNullable(consentAudio)
            .orElseThrow(() -> new IllegalArgumentException("consentAudio cannot be null"));
        this.sourceAudio = Optional.ofNullable(sourceAudio)
            .orElseThrow(() -> new IllegalArgumentException("sourceAudio cannot be null"));
    }

    /**
     * Audio payload used for voice creation.
     */
    public Optional<AudioData> consentAudio() {
        return Optional.ofNullable(this.consentAudio);
    }

    /**
     * Audio payload used for voice creation.
     */
    public Optional<AudioData> sourceAudio() {
        return Optional.ofNullable(this.sourceAudio);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Audio payload used for voice creation.
     */
    public ReplicatedVoice withConsentAudio(@Nonnull AudioData consentAudio) {
        this.consentAudio = Utils.checkNotNull(consentAudio, "consentAudio");
        return this;
    }


    /**
     * Audio payload used for voice creation.
     */
    public ReplicatedVoice withSourceAudio(@Nonnull AudioData sourceAudio) {
        this.sourceAudio = Utils.checkNotNull(sourceAudio, "sourceAudio");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ReplicatedVoice other = (ReplicatedVoice) o;
        return 
            Utils.enhancedDeepEquals(this.consentAudio, other.consentAudio) &&
            Utils.enhancedDeepEquals(this.sourceAudio, other.sourceAudio);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            consentAudio, sourceAudio);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ReplicatedVoice.class,
                "consentAudio", consentAudio,
                "sourceAudio", sourceAudio);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private AudioData consentAudio;

        private AudioData sourceAudio;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Audio payload used for voice creation.
         */
        public Builder consentAudio(@Nonnull AudioData consentAudio) {
            this.consentAudio = Utils.checkNotNull(consentAudio, "consentAudio");
            return this;
        }

        /**
         * Audio payload used for voice creation.
         */
        public Builder sourceAudio(@Nonnull AudioData sourceAudio) {
            this.sourceAudio = Utils.checkNotNull(sourceAudio, "sourceAudio");
            return this;
        }

        public ReplicatedVoice build() {
            return new ReplicatedVoice(
                consentAudio, sourceAudio);
        }

    }
}
