/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.operations;

import static com.google.genai.gaos.operations.Operations.RequestOperation;

import com.google.genai.gaos.SDKConfiguration;
import com.google.genai.gaos.operations.CreateInteraction;
import com.google.genai.gaos.utils.Headers;
import com.google.genai.gaos.utils.Options;
import com.google.genai.gaos.utils.RetryConfig;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

public class CreateInteractionRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private CreateInteractionRequest request;
    private final Options.Builder optionsBuilder;

    public CreateInteractionRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.optionsBuilder = Options.builder();
    }

    public CreateInteractionRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    public CreateInteractionRequestBuilder request(@Nonnull CreateInteractionRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private CreateInteractionRequest _buildRequest() {
        return this.request;
    }
    
    public CreateInteractionRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CreateInteractionResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<CreateInteractionRequest, CreateInteractionResponse> operation
              = new CreateInteraction.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
