/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.google.genai.gaos.models.agents.Agent;
import com.google.genai.gaos.utils.SpeakeasyMetadata;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class CreateAgentRequest {
    /**
     * Which version of the API to use.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=api_version")
    private String apiVersion;

    /**
     * The request body.
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private Agent body;

    @JsonCreator
    public CreateAgentRequest(
            @Nullable String apiVersion,
            @Nonnull Agent body) {
        this.apiVersion = apiVersion;
        this.body = Optional.ofNullable(body)
            .orElseThrow(() -> new IllegalArgumentException("body cannot be null"));
    }
    
    public CreateAgentRequest(
            @Nonnull Agent body) {
        this(null, body);
    }

    /**
     * Which version of the API to use.
     */
    public Optional<String> apiVersion() {
        return Optional.ofNullable(this.apiVersion);
    }

    /**
     * The request body.
     */
    public Optional<Agent> body() {
        return Optional.ofNullable(this.body);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Which version of the API to use.
     */
    public CreateAgentRequest withApiVersion(@Nullable String apiVersion) {
        this.apiVersion = apiVersion;
        return this;
    }


    /**
     * The request body.
     */
    public CreateAgentRequest withBody(@Nonnull Agent body) {
        this.body = Utils.checkNotNull(body, "body");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateAgentRequest other = (CreateAgentRequest) o;
        return 
            Utils.enhancedDeepEquals(this.apiVersion, other.apiVersion) &&
            Utils.enhancedDeepEquals(this.body, other.body);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            apiVersion, body);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateAgentRequest.class,
                "apiVersion", apiVersion,
                "body", body);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String apiVersion;

        private Agent body;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Which version of the API to use.
         */
        public Builder apiVersion(@Nullable String apiVersion) {
            this.apiVersion = apiVersion;
            return this;
        }

        /**
         * The request body.
         */
        public Builder body(@Nonnull Agent body) {
            this.body = Utils.checkNotNull(body, "body");
            return this;
        }

        public CreateAgentRequest build() {
            return new CreateAgentRequest(
                apiVersion, body);
        }

    }
}
