/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.google.genai.gaos.utils.SpeakeasyMetadata;
import com.google.genai.gaos.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


@SuppressWarnings("all")
public class ListTriggersRequest {
    /**
     * Which version of the API to use.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=api_version")
    private Optional<String> apiVersion;

    /**
     * Optional. Filter expression (e.g., by state).
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter")
    private Optional<String> filter;

    /**
     * Optional. The maximum number of triggers to return per page.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_size")
    private Optional<Long> pageSize;

    /**
     * Optional. A page token from a previous ListTriggers call.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page_token")
    private Optional<String> pageToken;

    @JsonCreator
    public ListTriggersRequest(
            Optional<String> apiVersion,
            Optional<String> filter,
            Optional<Long> pageSize,
            Optional<String> pageToken) {
        Utils.checkNotNull(apiVersion, "apiVersion");
        Utils.checkNotNull(filter, "filter");
        Utils.checkNotNull(pageSize, "pageSize");
        Utils.checkNotNull(pageToken, "pageToken");
        this.apiVersion = apiVersion;
        this.filter = filter;
        this.pageSize = pageSize;
        this.pageToken = pageToken;
    }
    
    public ListTriggersRequest() {
        this(Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty());
    }

    /**
     * Which version of the API to use.
     */
    @JsonIgnore
    public Optional<String> apiVersion() {
        return apiVersion;
    }

    /**
     * Optional. Filter expression (e.g., by state).
     */
    @JsonIgnore
    public Optional<String> filter() {
        return filter;
    }

    /**
     * Optional. The maximum number of triggers to return per page.
     */
    @JsonIgnore
    public Optional<Long> pageSize() {
        return pageSize;
    }

    /**
     * Optional. A page token from a previous ListTriggers call.
     */
    @JsonIgnore
    public Optional<String> pageToken() {
        return pageToken;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Which version of the API to use.
     */
    public ListTriggersRequest withApiVersion(String apiVersion) {
        Utils.checkNotNull(apiVersion, "apiVersion");
        this.apiVersion = Optional.ofNullable(apiVersion);
        return this;
    }


    /**
     * Which version of the API to use.
     */
    public ListTriggersRequest withApiVersion(Optional<String> apiVersion) {
        Utils.checkNotNull(apiVersion, "apiVersion");
        this.apiVersion = apiVersion;
        return this;
    }

    /**
     * Optional. Filter expression (e.g., by state).
     */
    public ListTriggersRequest withFilter(String filter) {
        Utils.checkNotNull(filter, "filter");
        this.filter = Optional.ofNullable(filter);
        return this;
    }


    /**
     * Optional. Filter expression (e.g., by state).
     */
    public ListTriggersRequest withFilter(Optional<String> filter) {
        Utils.checkNotNull(filter, "filter");
        this.filter = filter;
        return this;
    }

    /**
     * Optional. The maximum number of triggers to return per page.
     */
    public ListTriggersRequest withPageSize(long pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = Optional.ofNullable(pageSize);
        return this;
    }


    /**
     * Optional. The maximum number of triggers to return per page.
     */
    public ListTriggersRequest withPageSize(Optional<Long> pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = pageSize;
        return this;
    }

    /**
     * Optional. A page token from a previous ListTriggers call.
     */
    public ListTriggersRequest withPageToken(String pageToken) {
        Utils.checkNotNull(pageToken, "pageToken");
        this.pageToken = Optional.ofNullable(pageToken);
        return this;
    }


    /**
     * Optional. A page token from a previous ListTriggers call.
     */
    public ListTriggersRequest withPageToken(Optional<String> pageToken) {
        Utils.checkNotNull(pageToken, "pageToken");
        this.pageToken = pageToken;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListTriggersRequest other = (ListTriggersRequest) o;
        return 
            Utils.enhancedDeepEquals(this.apiVersion, other.apiVersion) &&
            Utils.enhancedDeepEquals(this.filter, other.filter) &&
            Utils.enhancedDeepEquals(this.pageSize, other.pageSize) &&
            Utils.enhancedDeepEquals(this.pageToken, other.pageToken);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            apiVersion, filter, pageSize,
            pageToken);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListTriggersRequest.class,
                "apiVersion", apiVersion,
                "filter", filter,
                "pageSize", pageSize,
                "pageToken", pageToken);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> apiVersion = Optional.empty();

        private Optional<String> filter = Optional.empty();

        private Optional<Long> pageSize = Optional.empty();

        private Optional<String> pageToken = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Which version of the API to use.
         */
        public Builder apiVersion(String apiVersion) {
            Utils.checkNotNull(apiVersion, "apiVersion");
            this.apiVersion = Optional.ofNullable(apiVersion);
            return this;
        }

        /**
         * Which version of the API to use.
         */
        public Builder apiVersion(Optional<String> apiVersion) {
            Utils.checkNotNull(apiVersion, "apiVersion");
            this.apiVersion = apiVersion;
            return this;
        }


        /**
         * Optional. Filter expression (e.g., by state).
         */
        public Builder filter(String filter) {
            Utils.checkNotNull(filter, "filter");
            this.filter = Optional.ofNullable(filter);
            return this;
        }

        /**
         * Optional. Filter expression (e.g., by state).
         */
        public Builder filter(Optional<String> filter) {
            Utils.checkNotNull(filter, "filter");
            this.filter = filter;
            return this;
        }


        /**
         * Optional. The maximum number of triggers to return per page.
         */
        public Builder pageSize(long pageSize) {
            Utils.checkNotNull(pageSize, "pageSize");
            this.pageSize = Optional.ofNullable(pageSize);
            return this;
        }

        /**
         * Optional. The maximum number of triggers to return per page.
         */
        public Builder pageSize(Optional<Long> pageSize) {
            Utils.checkNotNull(pageSize, "pageSize");
            this.pageSize = pageSize;
            return this;
        }


        /**
         * Optional. A page token from a previous ListTriggers call.
         */
        public Builder pageToken(String pageToken) {
            Utils.checkNotNull(pageToken, "pageToken");
            this.pageToken = Optional.ofNullable(pageToken);
            return this;
        }

        /**
         * Optional. A page token from a previous ListTriggers call.
         */
        public Builder pageToken(Optional<String> pageToken) {
            Utils.checkNotNull(pageToken, "pageToken");
            this.pageToken = pageToken;
            return this;
        }

        public ListTriggersRequest build() {

            return new ListTriggersRequest(
                apiVersion, filter, pageSize,
                pageToken);
        }

    }
}
