/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.operations;

import static com.google.genai.gaos.operations.Operations.RequestOperation;

import com.google.genai.gaos.SDKConfiguration;
import com.google.genai.gaos.models.webhooks.PingWebhookRequest;
import com.google.genai.gaos.operations.PingWebhook;
import com.google.genai.gaos.utils.Headers;
import com.google.genai.gaos.utils.Options;
import com.google.genai.gaos.utils.RetryConfig;
import com.google.genai.gaos.utils.Utils;
import java.lang.String;
import java.util.Optional;

@SuppressWarnings("all")
public class PingWebhookRequestBuilder {

    private Optional<String> apiVersion = Optional.empty();
    private String id;
    private Optional<? extends PingWebhookRequest> body = Optional.empty();
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public PingWebhookRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public PingWebhookRequestBuilder apiVersion(String apiVersion) {
        Utils.checkNotNull(apiVersion, "apiVersion");
        this.apiVersion = Optional.of(apiVersion);
        return this;
    }

    public PingWebhookRequestBuilder apiVersion(Optional<String> apiVersion) {
        Utils.checkNotNull(apiVersion, "apiVersion");
        this.apiVersion = apiVersion;
        return this;
    }

    public PingWebhookRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }
                
    public PingWebhookRequestBuilder body(PingWebhookRequest body) {
        Utils.checkNotNull(body, "body");
        this.body = Optional.of(body);
        return this;
    }

    public PingWebhookRequestBuilder body(Optional<? extends PingWebhookRequest> body) {
        Utils.checkNotNull(body, "body");
        this.body = body;
        return this;
    }
                
    public PingWebhookRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public PingWebhookRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }


    private com.google.genai.gaos.models.operations.PingWebhookRequest buildRequest() {

        com.google.genai.gaos.models.operations.PingWebhookRequest request = new com.google.genai.gaos.models.operations.PingWebhookRequest(apiVersion,
            id,
            body);

        return request;
    }

    public PingWebhookResponse call() {
        Optional<Options> options = Optional.of(Options.builder()
            .retryConfig(retryConfig)
            .build());

        RequestOperation<com.google.genai.gaos.models.operations.PingWebhookRequest, PingWebhookResponse> operation
              = new PingWebhook.Sync(sdkConfiguration, options, _headers);
        com.google.genai.gaos.models.operations.PingWebhookRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
