/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.utils;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.Collection;
import java.util.Locale;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.CompletableFuture;
import java.util.function.Consumer;
import java.util.stream.Collectors;

import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import okio.BufferedSink;
import okio.Okio;

import com.google.genai.gaos.utils.Java8Compat;

import com.google.genai.gaos.utils.transport.HttpBody;
import com.google.genai.gaos.utils.transport.HttpRequest;
import com.google.genai.gaos.utils.transport.HttpResponse;

public class SpeakeasyHTTPClient implements HTTPClient {

    private static boolean debugEnabled = false;

    private Boolean localDebugEnabled;

    private static Set<String> redactedHeaders = Java8Compat.setOf("AUTHORIZATION", "X-API-KEY");

    private static Consumer<? super String> logger = System.out::println;

    private final OkHttpClient client = new OkHttpClient.Builder()
            .followRedirects(false)
            .followSslRedirects(false)
            .readTimeout(300, TimeUnit.SECONDS)
            .build();

    private static final Set<String> STREAMING_MEDIA_TYPES =
            
            Java8Compat.setOf("text/event-stream", "application/x-ndjson", "application/jsonl");

    private static boolean isStreamingMediaType(String value) {
        int paramsIndex = value.indexOf(';');
        String mediaType = paramsIndex == -1 ? value : value.substring(0, paramsIndex);
        return STREAMING_MEDIA_TYPES.contains(mediaType.trim().toLowerCase(Locale.ENGLISH));
    }

    private final OkHttpClient streamingClient = client.newBuilder()
            .readTimeout(0, TimeUnit.MILLISECONDS)
            .build();

    private OkHttpClient asyncCallClient(HttpRequest request) {
        boolean streaming = request.headers().get("Accept").stream()
                .flatMap(value -> java.util.Arrays.stream(value.split(",")))
                .anyMatch(SpeakeasyHTTPClient::isStreamingMediaType);
        return streaming ? streamingClient : client;
    }

    /**
     * Sets debug logging on or off for requests and responses including bodies for JSON content.
     * <p>
     * <strong>WARNING:</strong> This setting may expose sensitive information in logs (such as
     * {@code Authorization} headers) and should only be enabled temporarily for local debugging
     * purposes.
     * <p>
     * By default, {@code Authorization} headers are redacted in the logs (printed with a value
     * of {@code [*******]}). Header suppression can be controlled with the
     * {@link #setRedactedHeaders(Collection)} method.
     *
     * @param enabled {@code true} to enable debug logging, {@code false} to disable it
     * @see #setRedactedHeaders(Collection)
     * @see #addRedactedHeader(String)
     * @see #getDebugLoggingEnabled()
     */
    public static void setDebugLogging(boolean enabled) {
        debugEnabled = enabled;
    }

    public static boolean getDebugLoggingEnabled() {
        return debugEnabled;
    }

    @Override
    public boolean isDebugLoggingEnabled() {
        return Optional.ofNullable(localDebugEnabled).orElse(debugEnabled);
    }

    @Override
    public void enableDebugLogging(boolean enabled) {
        localDebugEnabled = enabled;
    }

    /**
     * When debug logging is enabled, this method controls the suppression of header values in the logs.
     * <p>
     * By default, {@code Authorization} headers are redacted in the logs (printed with a value
     * of {@code [*******]}).
     *
     * @param headerNames the names (case-insensitive) of the headers whose values
     *                    will be redacted in the logs
     * @see #setDebugLogging(boolean)
     */
    public static void setRedactedHeaders(Collection<String> headerNames) {
        redactedHeaders = headerNames.stream() //
                .map(x -> x.toUpperCase(Locale.ENGLISH)) //
                .collect(Collectors.toSet());
    }

    /**
     * When debug logging is enabled, this method adds a single header to the list of headers
     * whose values will be redacted in the logs.
     * <p>
     * By default, {@code Authorization} headers are redacted in the logs (printed with a value
     * of {@code [*******]}).
     *
     * @param headerName the name (case-insensitive) of the header whose value
     *                   will be redacted in the logs
     * @see #setDebugLogging(boolean)
     * @see #setRedactedHeaders(Collection)
     */
    public static void addRedactedHeader(String headerName) {
        Set<String> updated = new java.util.HashSet<>(redactedHeaders);
        updated.add(headerName.toUpperCase(Locale.ENGLISH));
        redactedHeaders = Java8Compat.setCopyOf(updated);
    }

    public static void setLogger(Consumer<? super String> logger) {
        SpeakeasyHTTPClient.logger = logger;
    }

    @Override
    public HttpResponse<InputStream> send(HttpRequest request) throws IOException {
        if (isDebugLoggingEnabled()) {
            logRequest(request, true);
        }
        Response okResponse = client.newCall(toOkHttpRequest(request)).execute();
        HttpResponse<InputStream> response = toResponse(request, okResponse);
        if (isDebugLoggingEnabled()) {
            response = logResponse(response, true);
        }
        return response;
    }

    @Override
    public CompletableFuture<HttpResponse<InputStream>> sendAsync(HttpRequest request) {
        CompletableFuture<HttpResponse<InputStream>> future = new CompletableFuture<>();
        try {
            if (isDebugLoggingEnabled()) {
                logRequest(request, true);
            }
            Call call = asyncCallClient(request).newCall(toOkHttpRequest(request));
            future.whenComplete((ignored, throwable) -> {
                if (future.isCancelled()) {
                    call.cancel();
                }
            });
            call.enqueue(new Callback() {

                @Override
                public void onFailure(Call call, IOException e) {
                    CompletableFuture.runAsync(() -> future.completeExceptionally(e));
                }

                @Override
                public void onResponse(Call call, Response okResponse) {
                    try {
                        HttpResponse<InputStream> response = toResponse(request, okResponse);
                        if (isDebugLoggingEnabled()) {
                            CompletableFuture.supplyAsync(() -> {
                                try {
                                    return logResponse(response, true);
                                } catch (IOException e) {
                                    throw new java.util.concurrent.CompletionException(e);
                                }
                            }).whenCompleteAsync((loggedResponse, error) -> {
                                if (error != null) {
                                    okResponse.close();
                                    future.completeExceptionally(error);
                                } else if (!future.complete(loggedResponse)) {
                                    okResponse.close();
                                }
                            });
                        } else {
                            CompletableFuture.runAsync(() -> {
                                if (!future.complete(response)) {
                                    okResponse.close();
                                }
                            });
                        }
                    } catch (Exception e) {
                        okResponse.close();
                        CompletableFuture.runAsync(() -> future.completeExceptionally(e));
                    }
                }
            });
        } catch (Exception e) {
            future.completeExceptionally(e);
        }
        return future;
    }

    private static Request toOkHttpRequest(HttpRequest request) {
        Request.Builder builder = new Request.Builder().url(request.uri().toString());
        request.headers().forEach((name, values) -> values.forEach(value -> builder.addHeader(name, value)));
        okhttp3.RequestBody body = request.body().map(SpeakeasyHTTPClient::toOkHttpBody).orElse(null);
        if (body == null && requiresRequestBody(request.method())) {
            body = okhttp3.RequestBody.create(new byte[0], null);
        }
        builder.method(request.method(), body);
        return builder.build();
    }

    private static boolean requiresRequestBody(String method) {
        return method.equals("POST") || method.equals("PUT") || method.equals("PATCH");
    }

    private static okhttp3.RequestBody toOkHttpBody(HttpBody body) {
        return new okhttp3.RequestBody() {

            @Override
            public MediaType contentType() {
                return null;
            }

            @Override
            public long contentLength() {
                return body.contentLength();
            }

            @Override
            public boolean isOneShot() {
                return !body.isRepeatable();
            }

            @Override
            public void writeTo(BufferedSink sink) throws IOException {
                InputStream in;
                try {
                    in = body.stream();
                } catch (IllegalStateException e) {
                    throw new IOException(e.getMessage(), e);
                }
                try (InputStream closeable = in) {
                    sink.writeAll(Okio.source(closeable));
                } catch (UncheckedIOException e) {
                    throw e.getCause();
                }
            }
        };
    }

    private static HttpResponse<InputStream> toResponse(HttpRequest request, Response response) {
        Headers headers = new Headers(response.headers().toMultimap());
        ResponseBody body = response.body();
        InputStream in = body == null ? new ByteArrayInputStream(new byte[0]) : body.byteStream();
        return new HttpResponse<>(request, response.code(), headers, in);
    }

    private static void logRequest(HttpRequest request, boolean logBody) throws IOException {
        log("Sending request: " + request);
        log("Request headers: " + redactHeaders(request.headers()));

        Optional<HttpBody> body = request.body();
        if (logBody && body.isPresent() && body.get().isRepeatable() && request.headers() //
                .first("Content-Type") //
                .filter(x -> x.equals("application/json") || x.equals("text/plain")).isPresent()) {
            try (InputStream in = body.get().stream()) {
                byte[] bytes = toByteArray(in);
                log("Request body:\n" + new String(bytes, StandardCharsets.UTF_8));
            }
        }
    }

    private static HttpResponse<InputStream> logResponse(HttpResponse<InputStream> response, boolean logBody) throws IOException {
        String contentType = response.contentType().orElse("application/octet-stream");
        log("Received response: " + response);
        log("Response headers: " + redactHeaders(response.headers()));

        if (isStreamingMediaType(contentType)) {
            return response;
        }

        byte[] bytes;
        try (InputStream in = response.body()) {
            bytes = toByteArray(in);
        }
        response = new HttpResponse<>(response.request(), response.statusCode(), response.headers(),
                new ByteArrayInputStream(bytes));

        if (logBody && (contentType.startsWith("application/json") || contentType.startsWith("text/plain"))) {
            log("Response body:\n" + new String(bytes, StandardCharsets.UTF_8));
        }
        return response;
    }

    private static String redactHeaders(Headers headers) {
        return "{" + headers.map() //
                .entrySet() //
                .stream() //
                .map(entry -> {
                    final String value;
                    if (redactedHeaders.contains(entry.getKey().toUpperCase(Locale.ENGLISH))) {
                        value = "[******]";
                    } else {
                        value = String.valueOf(entry.getValue());
                    }
                    return entry.getKey() + "=" + value;
                }) //
                .collect(Collectors.joining(", ")) + "}";
    }

    private static void log(String message) {
        logger.accept(message);
    }

    private static byte[] toByteArray(InputStream in) throws IOException {
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        byte[] data = new byte[4096];
        int nRead;
        while ((nRead = in.read(data, 0, data.length)) != -1) {
            buffer.write(data, 0, nRead);
        }
        return buffer.toByteArray();
    }
}
