/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * AllowedTools
 * 
 * <p>The configuration for allowed tools.
 */
public class AllowedTools {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mode")
    private ToolChoiceType mode;

    /**
     * The names of the allowed tools.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tools")
    private List<String> tools;

    @JsonCreator
    public AllowedTools(
            @JsonProperty("mode") @Nullable ToolChoiceType mode,
            @JsonProperty("tools") @Nullable List<String> tools) {
        this.mode = mode;
        this.tools = tools;
    }
    
    public AllowedTools() {
        this(null, null);
    }

    public Optional<ToolChoiceType> mode() {
        return Optional.ofNullable(this.mode);
    }

    /**
     * The names of the allowed tools.
     */
    public Optional<List<String>> tools() {
        return Optional.ofNullable(this.tools);
    }

    public static Builder builder() {
        return new Builder();
    }


    public AllowedTools withMode(@Nullable ToolChoiceType mode) {
        this.mode = mode;
        return this;
    }


    /**
     * The names of the allowed tools.
     */
    public AllowedTools withTools(@Nullable List<String> tools) {
        this.tools = tools;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AllowedTools other = (AllowedTools) o;
        return 
            Utils.enhancedDeepEquals(this.mode, other.mode) &&
            Utils.enhancedDeepEquals(this.tools, other.tools);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            mode, tools);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AllowedTools.class,
                "mode", mode,
                "tools", tools);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private ToolChoiceType mode;

        private List<String> tools;

        private Builder() {
          // force use of static builder() method
        }

        public Builder mode(@Nullable ToolChoiceType mode) {
            this.mode = mode;
            return this;
        }

        /**
         * The names of the allowed tools.
         */
        public Builder tools(@Nullable List<String> tools) {
            this.tools = tools;
            return this;
        }

        public AllowedTools build() {
            return new AllowedTools(
                mode, tools);
        }

    }
}
