/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

/**
 * Allowlist
 * 
 * <p>Outbound networking configuration for the sandbox. When specified, restricts which external domains
 * the sandbox can reach. Omit entirely to allow all outbound traffic with no header injection.
 */
@SuppressWarnings("all")
public class Allowlist {
    /**
     * List of allowed outbound domains. Only requests to listed domains are permitted. Use [{'domain':
     * '*'}] to allow all domains while still injecting headers on specific ones.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("allowlist")
    private Optional<? extends List<AllowlistEntry>> allowlist;

    @JsonCreator
    public Allowlist(
            @JsonProperty("allowlist") Optional<? extends List<AllowlistEntry>> allowlist) {
        Utils.checkNotNull(allowlist, "allowlist");
        this.allowlist = allowlist;
    }
    
    public Allowlist() {
        this(Optional.empty());
    }

    /**
     * List of allowed outbound domains. Only requests to listed domains are permitted. Use [{'domain':
     * '*'}] to allow all domains while still injecting headers on specific ones.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<AllowlistEntry>> allowlist() {
        return (Optional<List<AllowlistEntry>>) allowlist;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * List of allowed outbound domains. Only requests to listed domains are permitted. Use [{'domain':
     * '*'}] to allow all domains while still injecting headers on specific ones.
     */
    public Allowlist withAllowlist(List<AllowlistEntry> allowlist) {
        Utils.checkNotNull(allowlist, "allowlist");
        this.allowlist = Optional.ofNullable(allowlist);
        return this;
    }


    /**
     * List of allowed outbound domains. Only requests to listed domains are permitted. Use [{'domain':
     * '*'}] to allow all domains while still injecting headers on specific ones.
     */
    public Allowlist withAllowlist(Optional<? extends List<AllowlistEntry>> allowlist) {
        Utils.checkNotNull(allowlist, "allowlist");
        this.allowlist = allowlist;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Allowlist other = (Allowlist) o;
        return 
            Utils.enhancedDeepEquals(this.allowlist, other.allowlist);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            allowlist);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Allowlist.class,
                "allowlist", allowlist);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends List<AllowlistEntry>> allowlist = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * List of allowed outbound domains. Only requests to listed domains are permitted. Use [{'domain':
         * '*'}] to allow all domains while still injecting headers on specific ones.
         */
        public Builder allowlist(List<AllowlistEntry> allowlist) {
            Utils.checkNotNull(allowlist, "allowlist");
            this.allowlist = Optional.ofNullable(allowlist);
            return this;
        }

        /**
         * List of allowed outbound domains. Only requests to listed domains are permitted. Use [{'domain':
         * '*'}] to allow all domains while still injecting headers on specific ones.
         */
        public Builder allowlist(Optional<? extends List<AllowlistEntry>> allowlist) {
            Utils.checkNotNull(allowlist, "allowlist");
            this.allowlist = allowlist;
            return this;
        }

        public Allowlist build() {

            return new Allowlist(
                allowlist);
        }

    }
}
