/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

/**
 * Arguments
 * 
 * <p>The arguments to pass to the URL context.
 */
@SuppressWarnings("all")
public class Arguments {
    /**
     * The URLs to fetch.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("urls")
    private Optional<? extends List<String>> urls;

    @JsonCreator
    public Arguments(
            @JsonProperty("urls") Optional<? extends List<String>> urls) {
        Utils.checkNotNull(urls, "urls");
        this.urls = urls;
    }
    
    public Arguments() {
        this(Optional.empty());
    }

    /**
     * The URLs to fetch.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> urls() {
        return (Optional<List<String>>) urls;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The URLs to fetch.
     */
    public Arguments withUrls(List<String> urls) {
        Utils.checkNotNull(urls, "urls");
        this.urls = Optional.ofNullable(urls);
        return this;
    }


    /**
     * The URLs to fetch.
     */
    public Arguments withUrls(Optional<? extends List<String>> urls) {
        Utils.checkNotNull(urls, "urls");
        this.urls = urls;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Arguments other = (Arguments) o;
        return 
            Utils.enhancedDeepEquals(this.urls, other.urls);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            urls);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Arguments.class,
                "urls", urls);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends List<String>> urls = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The URLs to fetch.
         */
        public Builder urls(List<String> urls) {
            Utils.checkNotNull(urls, "urls");
            this.urls = Optional.ofNullable(urls);
            return this;
        }

        /**
         * The URLs to fetch.
         */
        public Builder urls(Optional<? extends List<String>> urls) {
            Utils.checkNotNull(urls, "urls");
            this.urls = urls;
            return this;
        }

        public Arguments build() {

            return new Arguments(
                urls);
        }

    }
}
