/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * AudioContentMimeType
 * 
 * <p>The mime type of the audio.
 */
public class AudioContentMimeType {

    public static final AudioContentMimeType AUDIO_WAV = new AudioContentMimeType("audio/wav");
    public static final AudioContentMimeType AUDIO_MP3 = new AudioContentMimeType("audio/mp3");
    public static final AudioContentMimeType AUDIO_AIFF = new AudioContentMimeType("audio/aiff");
    public static final AudioContentMimeType AUDIO_AAC = new AudioContentMimeType("audio/aac");
    public static final AudioContentMimeType AUDIO_OGG = new AudioContentMimeType("audio/ogg");
    public static final AudioContentMimeType AUDIO_FLAC = new AudioContentMimeType("audio/flac");
    public static final AudioContentMimeType AUDIO_MPEG = new AudioContentMimeType("audio/mpeg");
    public static final AudioContentMimeType AUDIO_M4A = new AudioContentMimeType("audio/m4a");
    public static final AudioContentMimeType AUDIO_L16 = new AudioContentMimeType("audio/l16");
    public static final AudioContentMimeType AUDIO_OPUS = new AudioContentMimeType("audio/opus");
    public static final AudioContentMimeType AUDIO_ALAW = new AudioContentMimeType("audio/alaw");
    public static final AudioContentMimeType AUDIO_MULAW = new AudioContentMimeType("audio/mulaw");
    public static final AudioContentMimeType AUDIO_WEBM = new AudioContentMimeType("audio/webm");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, AudioContentMimeType> values = createValuesMap();
    private static final Map<String, AudioContentMimeTypeEnum> enums = createEnumsMap();

    private final String value;

    private AudioContentMimeType(String value) {
        this.value = value;
    }

    /**
     * Returns a AudioContentMimeType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as AudioContentMimeType
     */ 
    @JsonCreator
    public static AudioContentMimeType of(String value) {
        synchronized (AudioContentMimeType.class) {
            return values.computeIfAbsent(value, v -> new AudioContentMimeType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<AudioContentMimeTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        AudioContentMimeType other = (AudioContentMimeType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "AudioContentMimeType [value=" + value + "]";
    }

    // return an array just like an enum
    public static AudioContentMimeType[] values() {
        synchronized (AudioContentMimeType.class) {
            return values.values().toArray(new AudioContentMimeType[] {});
        }
    }

    private static final Map<String, AudioContentMimeType> createValuesMap() {
        Map<String, AudioContentMimeType> map = new LinkedHashMap<>();
        map.put("audio/wav", AUDIO_WAV);
        map.put("audio/mp3", AUDIO_MP3);
        map.put("audio/aiff", AUDIO_AIFF);
        map.put("audio/aac", AUDIO_AAC);
        map.put("audio/ogg", AUDIO_OGG);
        map.put("audio/flac", AUDIO_FLAC);
        map.put("audio/mpeg", AUDIO_MPEG);
        map.put("audio/m4a", AUDIO_M4A);
        map.put("audio/l16", AUDIO_L16);
        map.put("audio/opus", AUDIO_OPUS);
        map.put("audio/alaw", AUDIO_ALAW);
        map.put("audio/mulaw", AUDIO_MULAW);
        map.put("audio/webm", AUDIO_WEBM);
        return map;
    }

    private static final Map<String, AudioContentMimeTypeEnum> createEnumsMap() {
        Map<String, AudioContentMimeTypeEnum> map = new HashMap<>();
        map.put("audio/wav", AudioContentMimeTypeEnum.AUDIO_WAV);
        map.put("audio/mp3", AudioContentMimeTypeEnum.AUDIO_MP3);
        map.put("audio/aiff", AudioContentMimeTypeEnum.AUDIO_AIFF);
        map.put("audio/aac", AudioContentMimeTypeEnum.AUDIO_AAC);
        map.put("audio/ogg", AudioContentMimeTypeEnum.AUDIO_OGG);
        map.put("audio/flac", AudioContentMimeTypeEnum.AUDIO_FLAC);
        map.put("audio/mpeg", AudioContentMimeTypeEnum.AUDIO_MPEG);
        map.put("audio/m4a", AudioContentMimeTypeEnum.AUDIO_M4A);
        map.put("audio/l16", AudioContentMimeTypeEnum.AUDIO_L16);
        map.put("audio/opus", AudioContentMimeTypeEnum.AUDIO_OPUS);
        map.put("audio/alaw", AudioContentMimeTypeEnum.AUDIO_ALAW);
        map.put("audio/mulaw", AudioContentMimeTypeEnum.AUDIO_MULAW);
        map.put("audio/webm", AudioContentMimeTypeEnum.AUDIO_WEBM);
        return map;
    }
    
    
    public enum AudioContentMimeTypeEnum {

        AUDIO_WAV("audio/wav"),
        AUDIO_MP3("audio/mp3"),
        AUDIO_AIFF("audio/aiff"),
        AUDIO_AAC("audio/aac"),
        AUDIO_OGG("audio/ogg"),
        AUDIO_FLAC("audio/flac"),
        AUDIO_MPEG("audio/mpeg"),
        AUDIO_M4A("audio/m4a"),
        AUDIO_L16("audio/l16"),
        AUDIO_OPUS("audio/opus"),
        AUDIO_ALAW("audio/alaw"),
        AUDIO_MULAW("audio/mulaw"),
        AUDIO_WEBM("audio/webm"),;

        private final String value;

        private AudioContentMimeTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

