/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Deprecated;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * CreateModelInteraction
 * 
 * <p>Parameters for creating model interactions
 */
@SuppressWarnings("all")
public class CreateModelInteraction {
    /**
     * The model that will complete your prompt.\n\nSee
     * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
     */
    @JsonProperty("model")
    private Model model;

    /**
     * Input only. Whether to run the model interaction in the background.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("background")
    private Boolean background;

    /**
     * Input only. Whether to store the response and request for later retrieval.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("store")
    private Boolean store;

    /**
     * Input only. Whether the interaction will be streamed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("stream")
    private Boolean stream;

    /**
     * The environment configuration for the interaction. Can be an object specifying remote environment
     * sources or a string referencing an existing environment ID.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("environment")
    private CreateModelInteractionEnvironment environment;

    /**
     * The ID of the previous interaction, if any.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("previous_interaction_id")
    private String previousInteractionId;

    /**
     * The mime type of the response. This is required if response_format is set.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_mime_type")
    @Deprecated
    private String responseMimeType;

    /**
     * The requested modalities of the response (TEXT, IMAGE, AUDIO).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_modalities")
    private List<ResponseModality> responseModalities;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("service_tier")
    private ServiceTier serviceTier;

    /**
     * System instruction for the interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("system_instruction")
    private String systemInstruction;

    /**
     * A list of tool declarations the model may call during interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tools")
    private List<Tool> tools;

    /**
     * Statistics on the interaction request's token usage.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("usage")
    private Usage usage;

    /**
     * Message for configuring webhook events for a request.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("webhook_config")
    private WebhookConfig webhookConfig;

    /**
     * Configuration parameters for model interactions.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("generation_config")
    private GenerationConfig generationConfig;

    /**
     * Enforces that the generated response is a JSON object that complies with the JSON schema specified
     * in this field.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_format")
    private CreateModelInteractionResponseFormat responseFormat;

    /**
     * The input for the interaction.
     */
    @JsonProperty("input")
    private InteractionsInput input;

    @JsonCreator
    public CreateModelInteraction(
            @JsonProperty("model") @Nonnull Model model,
            @JsonProperty("background") @Nullable Boolean background,
            @JsonProperty("store") @Nullable Boolean store,
            @JsonProperty("stream") @Nullable Boolean stream,
            @JsonProperty("environment") @Nullable CreateModelInteractionEnvironment environment,
            @JsonProperty("previous_interaction_id") @Nullable String previousInteractionId,
            @JsonProperty("response_mime_type") @Nullable String responseMimeType,
            @JsonProperty("response_modalities") @Nullable List<ResponseModality> responseModalities,
            @JsonProperty("service_tier") @Nullable ServiceTier serviceTier,
            @JsonProperty("system_instruction") @Nullable String systemInstruction,
            @JsonProperty("tools") @Nullable List<Tool> tools,
            @JsonProperty("usage") @Nullable Usage usage,
            @JsonProperty("webhook_config") @Nullable WebhookConfig webhookConfig,
            @JsonProperty("generation_config") @Nullable GenerationConfig generationConfig,
            @JsonProperty("response_format") @Nullable CreateModelInteractionResponseFormat responseFormat,
            @JsonProperty("input") @Nonnull InteractionsInput input) {
        this.model = Optional.ofNullable(model)
            .orElseThrow(() -> new IllegalArgumentException("model cannot be null"));
        this.background = background;
        this.store = store;
        this.stream = stream;
        this.environment = environment;
        this.previousInteractionId = previousInteractionId;
        this.responseMimeType = responseMimeType;
        this.responseModalities = responseModalities;
        this.serviceTier = serviceTier;
        this.systemInstruction = systemInstruction;
        this.tools = tools;
        this.usage = usage;
        this.webhookConfig = webhookConfig;
        this.generationConfig = generationConfig;
        this.responseFormat = responseFormat;
        this.input = Optional.ofNullable(input)
            .orElseThrow(() -> new IllegalArgumentException("input cannot be null"));
    }
    
    public CreateModelInteraction(
            @Nonnull Model model,
            @Nonnull InteractionsInput input) {
        this(model, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            input);
    }

    /**
     * The model that will complete your prompt.\n\nSee
     * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
     */
    public Model model() {
        return this.model;
    }

    /**
     * Input only. Whether to run the model interaction in the background.
     */
    public Optional<Boolean> background() {
        return Optional.ofNullable(this.background);
    }

    /**
     * Input only. Whether to store the response and request for later retrieval.
     */
    public Optional<Boolean> store() {
        return Optional.ofNullable(this.store);
    }

    /**
     * Input only. Whether the interaction will be streamed.
     */
    public Optional<Boolean> stream() {
        return Optional.ofNullable(this.stream);
    }

    /**
     * The environment configuration for the interaction. Can be an object specifying remote environment
     * sources or a string referencing an existing environment ID.
     */
    public Optional<CreateModelInteractionEnvironment> environment() {
        return Optional.ofNullable(this.environment);
    }

    /**
     * The ID of the previous interaction, if any.
     */
    public Optional<String> previousInteractionId() {
        return Optional.ofNullable(this.previousInteractionId);
    }

    /**
     * The mime type of the response. This is required if response_format is set.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Optional<String> responseMimeType() {
        return Optional.ofNullable(this.responseMimeType);
    }

    /**
     * The requested modalities of the response (TEXT, IMAGE, AUDIO).
     */
    public Optional<List<ResponseModality>> responseModalities() {
        return Optional.ofNullable(this.responseModalities);
    }

    public Optional<ServiceTier> serviceTier() {
        return Optional.ofNullable(this.serviceTier);
    }

    /**
     * System instruction for the interaction.
     */
    public Optional<String> systemInstruction() {
        return Optional.ofNullable(this.systemInstruction);
    }

    /**
     * A list of tool declarations the model may call during interaction.
     */
    public Optional<List<Tool>> tools() {
        return Optional.ofNullable(this.tools);
    }

    /**
     * Statistics on the interaction request's token usage.
     */
    public Optional<Usage> usage() {
        return Optional.ofNullable(this.usage);
    }

    /**
     * Message for configuring webhook events for a request.
     */
    public Optional<WebhookConfig> webhookConfig() {
        return Optional.ofNullable(this.webhookConfig);
    }

    /**
     * Configuration parameters for model interactions.
     */
    public Optional<GenerationConfig> generationConfig() {
        return Optional.ofNullable(this.generationConfig);
    }

    /**
     * Enforces that the generated response is a JSON object that complies with the JSON schema specified
     * in this field.
     */
    public Optional<CreateModelInteractionResponseFormat> responseFormat() {
        return Optional.ofNullable(this.responseFormat);
    }

    /**
     * The input for the interaction.
     */
    public InteractionsInput input() {
        return this.input;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The model that will complete your prompt.\n\nSee
     * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
     */
    public CreateModelInteraction withModel(@Nonnull Model model) {
        this.model = Utils.checkNotNull(model, "model");
        return this;
    }


    /**
     * Input only. Whether to run the model interaction in the background.
     */
    public CreateModelInteraction withBackground(@Nullable Boolean background) {
        this.background = background;
        return this;
    }


    /**
     * Input only. Whether to store the response and request for later retrieval.
     */
    public CreateModelInteraction withStore(@Nullable Boolean store) {
        this.store = store;
        return this;
    }


    /**
     * Input only. Whether the interaction will be streamed.
     */
    public CreateModelInteraction withStream(@Nullable Boolean stream) {
        this.stream = stream;
        return this;
    }


    /**
     * The environment configuration for the interaction. Can be an object specifying remote environment
     * sources or a string referencing an existing environment ID.
     */
    public CreateModelInteraction withEnvironment(@Nullable CreateModelInteractionEnvironment environment) {
        this.environment = environment;
        return this;
    }


    /**
     * The ID of the previous interaction, if any.
     */
    public CreateModelInteraction withPreviousInteractionId(@Nullable String previousInteractionId) {
        this.previousInteractionId = previousInteractionId;
        return this;
    }


    /**
     * The mime type of the response. This is required if response_format is set.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public CreateModelInteraction withResponseMimeType(@Nullable String responseMimeType) {
        this.responseMimeType = responseMimeType;
        return this;
    }


    /**
     * The requested modalities of the response (TEXT, IMAGE, AUDIO).
     */
    public CreateModelInteraction withResponseModalities(@Nullable List<ResponseModality> responseModalities) {
        this.responseModalities = responseModalities;
        return this;
    }


    public CreateModelInteraction withServiceTier(@Nullable ServiceTier serviceTier) {
        this.serviceTier = serviceTier;
        return this;
    }


    /**
     * System instruction for the interaction.
     */
    public CreateModelInteraction withSystemInstruction(@Nullable String systemInstruction) {
        this.systemInstruction = systemInstruction;
        return this;
    }


    /**
     * A list of tool declarations the model may call during interaction.
     */
    public CreateModelInteraction withTools(@Nullable List<Tool> tools) {
        this.tools = tools;
        return this;
    }


    /**
     * Statistics on the interaction request's token usage.
     */
    public CreateModelInteraction withUsage(@Nullable Usage usage) {
        this.usage = usage;
        return this;
    }


    /**
     * Message for configuring webhook events for a request.
     */
    public CreateModelInteraction withWebhookConfig(@Nullable WebhookConfig webhookConfig) {
        this.webhookConfig = webhookConfig;
        return this;
    }


    /**
     * Configuration parameters for model interactions.
     */
    public CreateModelInteraction withGenerationConfig(@Nullable GenerationConfig generationConfig) {
        this.generationConfig = generationConfig;
        return this;
    }


    /**
     * Enforces that the generated response is a JSON object that complies with the JSON schema specified
     * in this field.
     */
    public CreateModelInteraction withResponseFormat(@Nullable CreateModelInteractionResponseFormat responseFormat) {
        this.responseFormat = responseFormat;
        return this;
    }


    /**
     * The input for the interaction.
     */
    public CreateModelInteraction withInput(@Nonnull InteractionsInput input) {
        this.input = Utils.checkNotNull(input, "input");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateModelInteraction other = (CreateModelInteraction) o;
        return 
            Utils.enhancedDeepEquals(this.model, other.model) &&
            Utils.enhancedDeepEquals(this.background, other.background) &&
            Utils.enhancedDeepEquals(this.store, other.store) &&
            Utils.enhancedDeepEquals(this.stream, other.stream) &&
            Utils.enhancedDeepEquals(this.environment, other.environment) &&
            Utils.enhancedDeepEquals(this.previousInteractionId, other.previousInteractionId) &&
            Utils.enhancedDeepEquals(this.responseMimeType, other.responseMimeType) &&
            Utils.enhancedDeepEquals(this.responseModalities, other.responseModalities) &&
            Utils.enhancedDeepEquals(this.serviceTier, other.serviceTier) &&
            Utils.enhancedDeepEquals(this.systemInstruction, other.systemInstruction) &&
            Utils.enhancedDeepEquals(this.tools, other.tools) &&
            Utils.enhancedDeepEquals(this.usage, other.usage) &&
            Utils.enhancedDeepEquals(this.webhookConfig, other.webhookConfig) &&
            Utils.enhancedDeepEquals(this.generationConfig, other.generationConfig) &&
            Utils.enhancedDeepEquals(this.responseFormat, other.responseFormat) &&
            Utils.enhancedDeepEquals(this.input, other.input);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            model, background, store,
            stream, environment, previousInteractionId,
            responseMimeType, responseModalities, serviceTier,
            systemInstruction, tools, usage,
            webhookConfig, generationConfig, responseFormat,
            input);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateModelInteraction.class,
                "model", model,
                "background", background,
                "store", store,
                "stream", stream,
                "environment", environment,
                "previousInteractionId", previousInteractionId,
                "responseMimeType", responseMimeType,
                "responseModalities", responseModalities,
                "serviceTier", serviceTier,
                "systemInstruction", systemInstruction,
                "tools", tools,
                "usage", usage,
                "webhookConfig", webhookConfig,
                "generationConfig", generationConfig,
                "responseFormat", responseFormat,
                "input", input);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Model model;

        private Boolean background;

        private Boolean store;

        private Boolean stream;

        private CreateModelInteractionEnvironment environment;

        private String previousInteractionId;

        @Deprecated
        private String responseMimeType;

        private List<ResponseModality> responseModalities;

        private ServiceTier serviceTier;

        private String systemInstruction;

        private List<Tool> tools;

        private Usage usage;

        private WebhookConfig webhookConfig;

        private GenerationConfig generationConfig;

        private CreateModelInteractionResponseFormat responseFormat;

        private InteractionsInput input;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The model that will complete your prompt.\n\nSee
         * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
         */
        public Builder model(@Nonnull Model model) {
            this.model = Utils.checkNotNull(model, "model");
            return this;
        }

        /**
         * The model that will complete your prompt.\n\nSee
         * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
         */
        public Builder model(@Nonnull String model) {
            this.model = Model.of(Utils.checkNotNull(model, "model"));
            return this;
        }

        /**
         * Input only. Whether to run the model interaction in the background.
         */
        public Builder background(@Nullable Boolean background) {
            this.background = background;
            return this;
        }

        /**
         * Input only. Whether to store the response and request for later retrieval.
         */
        public Builder store(@Nullable Boolean store) {
            this.store = store;
            return this;
        }

        /**
         * Input only. Whether the interaction will be streamed.
         */
        public Builder stream(@Nullable Boolean stream) {
            this.stream = stream;
            return this;
        }

        /**
         * The environment configuration for the interaction. Can be an object specifying remote environment
         * sources or a string referencing an existing environment ID.
         */
        public Builder environment(@Nullable CreateModelInteractionEnvironment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * The ID of the previous interaction, if any.
         */
        public Builder previousInteractionId(@Nullable String previousInteractionId) {
            this.previousInteractionId = previousInteractionId;
            return this;
        }

        /**
         * The mime type of the response. This is required if response_format is set.
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder responseMimeType(@Nullable String responseMimeType) {
            this.responseMimeType = responseMimeType;
            return this;
        }

        /**
         * The requested modalities of the response (TEXT, IMAGE, AUDIO).
         */
        public Builder responseModalities(@Nullable List<ResponseModality> responseModalities) {
            this.responseModalities = responseModalities;
            return this;
        }

        public Builder serviceTier(@Nullable ServiceTier serviceTier) {
            this.serviceTier = serviceTier;
            return this;
        }

        /**
         * System instruction for the interaction.
         */
        public Builder systemInstruction(@Nullable String systemInstruction) {
            this.systemInstruction = systemInstruction;
            return this;
        }

        /**
         * A list of tool declarations the model may call during interaction.
         */
        public Builder tools(@Nullable List<Tool> tools) {
            this.tools = tools;
            return this;
        }

        /**
         * Statistics on the interaction request's token usage.
         */
        public Builder usage(@Nullable Usage usage) {
            this.usage = usage;
            return this;
        }

        /**
         * Message for configuring webhook events for a request.
         */
        public Builder webhookConfig(@Nullable WebhookConfig webhookConfig) {
            this.webhookConfig = webhookConfig;
            return this;
        }

        /**
         * Configuration parameters for model interactions.
         */
        public Builder generationConfig(@Nullable GenerationConfig generationConfig) {
            this.generationConfig = generationConfig;
            return this;
        }

        /**
         * Enforces that the generated response is a JSON object that complies with the JSON schema specified
         * in this field.
         */
        public Builder responseFormat(@Nullable CreateModelInteractionResponseFormat responseFormat) {
            this.responseFormat = responseFormat;
            return this;
        }

        /**
         * The input for the interaction.
         */
        public Builder input(@Nonnull InteractionsInput input) {
            this.input = Utils.checkNotNull(input, "input");
            return this;
        }

        public CreateModelInteraction build() {
            return new CreateModelInteraction(
                model, background, store,
                stream, environment, previousInteractionId,
                responseMimeType, responseModalities, serviceTier,
                systemInstruction, tools, usage,
                webhookConfig, generationConfig, responseFormat,
                input);
        }

    }
}
