/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Deprecated;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * CreateModelInteraction
 * 
 * <p>Parameters for creating model interactions
 */
public class CreateModelInteraction {
    /**
     * The model that will complete your prompt.\n\nSee
     * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
     */
    @JsonProperty("model")
    private Model model;

    /**
     * Input only. Whether the interaction will be streamed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("stream")
    private Boolean stream;

    /**
     * Input only. Whether to store the response and request for later retrieval.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("store")
    private Boolean store;

    /**
     * Input only. Whether to run the model interaction in the background.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("background")
    private Boolean background;

    /**
     * System instruction for the interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("system_instruction")
    private String systemInstruction;

    /**
     * A list of tool declarations the model may call during interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tools")
    private List<Tool> tools;

    /**
     * The requested modalities of the response (TEXT, IMAGE, AUDIO).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_modalities")
    private List<ResponseModality> responseModalities;

    /**
     * The mime type of the response. This is required if response_format is set.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_mime_type")
    @Deprecated
    private String responseMimeType;

    /**
     * The ID of the previous interaction, if any.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("previous_interaction_id")
    private String previousInteractionId;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("service_tier")
    private ServiceTier serviceTier;

    /**
     * Message for configuring webhook events for a request.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("webhook_config")
    private WebhookConfig webhookConfig;

    /**
     * Enforces that the generated response is a JSON object that complies with the JSON schema specified
     * in this field.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_format")
    private CreateModelInteractionResponseFormat responseFormat;

    /**
     * The environment configuration for the interaction. Can be an object specifying remote environment
     * sources or a string referencing an existing environment ID.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("environment")
    private CreateModelInteractionEnvironment environment;

    /**
     * Configuration parameters for model interactions.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("generation_config")
    private GenerationConfig generationConfig;

    /**
     * Safety settings for the interaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("safety_settings")
    private List<SafetySetting> safetySettings;

    /**
     * The labels with user-defined metadata for the request.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("labels")
    private Map<String, String> labels;

    /**
     * The input for the interaction.
     */
    @JsonProperty("input")
    private InteractionsInput input;

    @JsonCreator
    public CreateModelInteraction(
            @JsonProperty("model") @Nonnull Model model,
            @JsonProperty("stream") @Nullable Boolean stream,
            @JsonProperty("store") @Nullable Boolean store,
            @JsonProperty("background") @Nullable Boolean background,
            @JsonProperty("system_instruction") @Nullable String systemInstruction,
            @JsonProperty("tools") @Nullable List<Tool> tools,
            @JsonProperty("response_modalities") @Nullable List<ResponseModality> responseModalities,
            @JsonProperty("response_mime_type") @Nullable String responseMimeType,
            @JsonProperty("previous_interaction_id") @Nullable String previousInteractionId,
            @JsonProperty("service_tier") @Nullable ServiceTier serviceTier,
            @JsonProperty("webhook_config") @Nullable WebhookConfig webhookConfig,
            @JsonProperty("response_format") @Nullable CreateModelInteractionResponseFormat responseFormat,
            @JsonProperty("environment") @Nullable CreateModelInteractionEnvironment environment,
            @JsonProperty("generation_config") @Nullable GenerationConfig generationConfig,
            @JsonProperty("safety_settings") @Nullable List<SafetySetting> safetySettings,
            @JsonProperty("labels") @Nullable Map<String, String> labels,
            @JsonProperty("input") @Nonnull InteractionsInput input) {
        this.model = Optional.ofNullable(model)
            .orElseThrow(() -> new IllegalArgumentException("model cannot be null"));
        this.stream = stream;
        this.store = store;
        this.background = background;
        this.systemInstruction = systemInstruction;
        this.tools = tools;
        this.responseModalities = responseModalities;
        this.responseMimeType = responseMimeType;
        this.previousInteractionId = previousInteractionId;
        this.serviceTier = serviceTier;
        this.webhookConfig = webhookConfig;
        this.responseFormat = responseFormat;
        this.environment = environment;
        this.generationConfig = generationConfig;
        this.safetySettings = safetySettings;
        this.labels = labels;
        this.input = Optional.ofNullable(input)
            .orElseThrow(() -> new IllegalArgumentException("input cannot be null"));
    }
    
    public CreateModelInteraction(
            @Nonnull Model model,
            @Nonnull InteractionsInput input) {
        this(model, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, null, null,
            null, input);
    }

    /**
     * The model that will complete your prompt.\n\nSee
     * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
     */
    public Optional<Model> model() {
        return Optional.ofNullable(this.model);
    }

    /**
     * Input only. Whether the interaction will be streamed.
     */
    public Optional<Boolean> stream() {
        return Optional.ofNullable(this.stream);
    }

    /**
     * Input only. Whether to store the response and request for later retrieval.
     */
    public Optional<Boolean> store() {
        return Optional.ofNullable(this.store);
    }

    /**
     * Input only. Whether to run the model interaction in the background.
     */
    public Optional<Boolean> background() {
        return Optional.ofNullable(this.background);
    }

    /**
     * System instruction for the interaction.
     */
    public Optional<String> systemInstruction() {
        return Optional.ofNullable(this.systemInstruction);
    }

    /**
     * A list of tool declarations the model may call during interaction.
     */
    public Optional<List<Tool>> tools() {
        return Optional.ofNullable(this.tools);
    }

    /**
     * The requested modalities of the response (TEXT, IMAGE, AUDIO).
     */
    public Optional<List<ResponseModality>> responseModalities() {
        return Optional.ofNullable(this.responseModalities);
    }

    /**
     * The mime type of the response. This is required if response_format is set.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public Optional<String> responseMimeType() {
        return Optional.ofNullable(this.responseMimeType);
    }

    /**
     * The ID of the previous interaction, if any.
     */
    public Optional<String> previousInteractionId() {
        return Optional.ofNullable(this.previousInteractionId);
    }

    public Optional<ServiceTier> serviceTier() {
        return Optional.ofNullable(this.serviceTier);
    }

    /**
     * Message for configuring webhook events for a request.
     */
    public Optional<WebhookConfig> webhookConfig() {
        return Optional.ofNullable(this.webhookConfig);
    }

    /**
     * Enforces that the generated response is a JSON object that complies with the JSON schema specified
     * in this field.
     */
    public Optional<CreateModelInteractionResponseFormat> responseFormat() {
        return Optional.ofNullable(this.responseFormat);
    }

    /**
     * The environment configuration for the interaction. Can be an object specifying remote environment
     * sources or a string referencing an existing environment ID.
     */
    public Optional<CreateModelInteractionEnvironment> environment() {
        return Optional.ofNullable(this.environment);
    }

    /**
     * Configuration parameters for model interactions.
     */
    public Optional<GenerationConfig> generationConfig() {
        return Optional.ofNullable(this.generationConfig);
    }

    /**
     * Safety settings for the interaction.
     */
    public Optional<List<SafetySetting>> safetySettings() {
        return Optional.ofNullable(this.safetySettings);
    }

    /**
     * The labels with user-defined metadata for the request.
     */
    public Optional<Map<String, String>> labels() {
        return Optional.ofNullable(this.labels);
    }

    /**
     * The input for the interaction.
     */
    public Optional<InteractionsInput> input() {
        return Optional.ofNullable(this.input);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The model that will complete your prompt.\n\nSee
     * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
     */
    public CreateModelInteraction withModel(@Nonnull Model model) {
        this.model = Utils.checkNotNull(model, "model");
        return this;
    }


    /**
     * Input only. Whether the interaction will be streamed.
     */
    public CreateModelInteraction withStream(@Nullable Boolean stream) {
        this.stream = stream;
        return this;
    }


    /**
     * Input only. Whether to store the response and request for later retrieval.
     */
    public CreateModelInteraction withStore(@Nullable Boolean store) {
        this.store = store;
        return this;
    }


    /**
     * Input only. Whether to run the model interaction in the background.
     */
    public CreateModelInteraction withBackground(@Nullable Boolean background) {
        this.background = background;
        return this;
    }


    /**
     * System instruction for the interaction.
     */
    public CreateModelInteraction withSystemInstruction(@Nullable String systemInstruction) {
        this.systemInstruction = systemInstruction;
        return this;
    }


    /**
     * A list of tool declarations the model may call during interaction.
     */
    public CreateModelInteraction withTools(@Nullable List<Tool> tools) {
        this.tools = tools;
        return this;
    }


    /**
     * The requested modalities of the response (TEXT, IMAGE, AUDIO).
     */
    public CreateModelInteraction withResponseModalities(@Nullable List<ResponseModality> responseModalities) {
        this.responseModalities = responseModalities;
        return this;
    }


    /**
     * The mime type of the response. This is required if response_format is set.
     * 
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public CreateModelInteraction withResponseMimeType(@Nullable String responseMimeType) {
        this.responseMimeType = responseMimeType;
        return this;
    }


    /**
     * The ID of the previous interaction, if any.
     */
    public CreateModelInteraction withPreviousInteractionId(@Nullable String previousInteractionId) {
        this.previousInteractionId = previousInteractionId;
        return this;
    }


    public CreateModelInteraction withServiceTier(@Nullable ServiceTier serviceTier) {
        this.serviceTier = serviceTier;
        return this;
    }


    /**
     * Message for configuring webhook events for a request.
     */
    public CreateModelInteraction withWebhookConfig(@Nullable WebhookConfig webhookConfig) {
        this.webhookConfig = webhookConfig;
        return this;
    }


    /**
     * Enforces that the generated response is a JSON object that complies with the JSON schema specified
     * in this field.
     */
    public CreateModelInteraction withResponseFormat(@Nullable CreateModelInteractionResponseFormat responseFormat) {
        this.responseFormat = responseFormat;
        return this;
    }


    /**
     * The environment configuration for the interaction. Can be an object specifying remote environment
     * sources or a string referencing an existing environment ID.
     */
    public CreateModelInteraction withEnvironment(@Nullable CreateModelInteractionEnvironment environment) {
        this.environment = environment;
        return this;
    }


    /**
     * Configuration parameters for model interactions.
     */
    public CreateModelInteraction withGenerationConfig(@Nullable GenerationConfig generationConfig) {
        this.generationConfig = generationConfig;
        return this;
    }


    /**
     * Safety settings for the interaction.
     */
    public CreateModelInteraction withSafetySettings(@Nullable List<SafetySetting> safetySettings) {
        this.safetySettings = safetySettings;
        return this;
    }


    /**
     * The labels with user-defined metadata for the request.
     */
    public CreateModelInteraction withLabels(@Nullable Map<String, String> labels) {
        this.labels = labels;
        return this;
    }


    /**
     * The input for the interaction.
     */
    public CreateModelInteraction withInput(@Nonnull InteractionsInput input) {
        this.input = Utils.checkNotNull(input, "input");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateModelInteraction other = (CreateModelInteraction) o;
        return 
            Utils.enhancedDeepEquals(this.model, other.model) &&
            Utils.enhancedDeepEquals(this.stream, other.stream) &&
            Utils.enhancedDeepEquals(this.store, other.store) &&
            Utils.enhancedDeepEquals(this.background, other.background) &&
            Utils.enhancedDeepEquals(this.systemInstruction, other.systemInstruction) &&
            Utils.enhancedDeepEquals(this.tools, other.tools) &&
            Utils.enhancedDeepEquals(this.responseModalities, other.responseModalities) &&
            Utils.enhancedDeepEquals(this.responseMimeType, other.responseMimeType) &&
            Utils.enhancedDeepEquals(this.previousInteractionId, other.previousInteractionId) &&
            Utils.enhancedDeepEquals(this.serviceTier, other.serviceTier) &&
            Utils.enhancedDeepEquals(this.webhookConfig, other.webhookConfig) &&
            Utils.enhancedDeepEquals(this.responseFormat, other.responseFormat) &&
            Utils.enhancedDeepEquals(this.environment, other.environment) &&
            Utils.enhancedDeepEquals(this.generationConfig, other.generationConfig) &&
            Utils.enhancedDeepEquals(this.safetySettings, other.safetySettings) &&
            Utils.enhancedDeepEquals(this.labels, other.labels) &&
            Utils.enhancedDeepEquals(this.input, other.input);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            model, stream, store,
            background, systemInstruction, tools,
            responseModalities, responseMimeType, previousInteractionId,
            serviceTier, webhookConfig, responseFormat,
            environment, generationConfig, safetySettings,
            labels, input);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateModelInteraction.class,
                "model", model,
                "stream", stream,
                "store", store,
                "background", background,
                "systemInstruction", systemInstruction,
                "tools", tools,
                "responseModalities", responseModalities,
                "responseMimeType", responseMimeType,
                "previousInteractionId", previousInteractionId,
                "serviceTier", serviceTier,
                "webhookConfig", webhookConfig,
                "responseFormat", responseFormat,
                "environment", environment,
                "generationConfig", generationConfig,
                "safetySettings", safetySettings,
                "labels", labels,
                "input", input);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Model model;

        private Boolean stream;

        private Boolean store;

        private Boolean background;

        private String systemInstruction;

        private List<Tool> tools;

        private List<ResponseModality> responseModalities;

        @Deprecated
        private String responseMimeType;

        private String previousInteractionId;

        private ServiceTier serviceTier;

        private WebhookConfig webhookConfig;

        private CreateModelInteractionResponseFormat responseFormat;

        private CreateModelInteractionEnvironment environment;

        private GenerationConfig generationConfig;

        private List<SafetySetting> safetySettings;

        private Map<String, String> labels;

        private InteractionsInput input;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The model that will complete your prompt.\n\nSee
         * [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
         */
        public Builder model(@Nonnull Model model) {
            this.model = Utils.checkNotNull(model, "model");
            return this;
        }

        public Builder model(@Nonnull String model) {
            this.model = Model.of(Utils.checkNotNull(model, "model"));
            return this;
        }

        /**
         * Input only. Whether the interaction will be streamed.
         */
        public Builder stream(@Nullable Boolean stream) {
            this.stream = stream;
            return this;
        }

        /**
         * Input only. Whether to store the response and request for later retrieval.
         */
        public Builder store(@Nullable Boolean store) {
            this.store = store;
            return this;
        }

        /**
         * Input only. Whether to run the model interaction in the background.
         */
        public Builder background(@Nullable Boolean background) {
            this.background = background;
            return this;
        }

        /**
         * System instruction for the interaction.
         */
        public Builder systemInstruction(@Nullable String systemInstruction) {
            this.systemInstruction = systemInstruction;
            return this;
        }

        /**
         * A list of tool declarations the model may call during interaction.
         */
        public Builder tools(@Nullable List<Tool> tools) {
            this.tools = tools;
            return this;
        }

        /**
         * The requested modalities of the response (TEXT, IMAGE, AUDIO).
         */
        public Builder responseModalities(@Nullable List<ResponseModality> responseModalities) {
            this.responseModalities = responseModalities;
            return this;
        }

        /**
         * The mime type of the response. This is required if response_format is set.
         * 
         * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
         */
        @Deprecated
        public Builder responseMimeType(@Nullable String responseMimeType) {
            this.responseMimeType = responseMimeType;
            return this;
        }

        /**
         * The ID of the previous interaction, if any.
         */
        public Builder previousInteractionId(@Nullable String previousInteractionId) {
            this.previousInteractionId = previousInteractionId;
            return this;
        }

        public Builder serviceTier(@Nullable ServiceTier serviceTier) {
            this.serviceTier = serviceTier;
            return this;
        }

        /**
         * Message for configuring webhook events for a request.
         */
        public Builder webhookConfig(@Nullable WebhookConfig webhookConfig) {
            this.webhookConfig = webhookConfig;
            return this;
        }

        /**
         * Enforces that the generated response is a JSON object that complies with the JSON schema specified
         * in this field.
         */
        public Builder responseFormat(@Nullable CreateModelInteractionResponseFormat responseFormat) {
            this.responseFormat = responseFormat;
            return this;
        }

        /**
         * The environment configuration for the interaction. Can be an object specifying remote environment
         * sources or a string referencing an existing environment ID.
         */
        public Builder environment(@Nullable CreateModelInteractionEnvironment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * Configuration parameters for model interactions.
         */
        public Builder generationConfig(@Nullable GenerationConfig generationConfig) {
            this.generationConfig = generationConfig;
            return this;
        }

        /**
         * Safety settings for the interaction.
         */
        public Builder safetySettings(@Nullable List<SafetySetting> safetySettings) {
            this.safetySettings = safetySettings;
            return this;
        }

        /**
         * The labels with user-defined metadata for the request.
         */
        public Builder labels(@Nullable Map<String, String> labels) {
            this.labels = labels;
            return this;
        }

        /**
         * The input for the interaction.
         */
        public Builder input(@Nonnull InteractionsInput input) {
            this.input = Utils.checkNotNull(input, "input");
            return this;
        }

        public CreateModelInteraction build() {
            return new CreateModelInteraction(
                model, stream, store,
                background, systemInstruction, tools,
                responseModalities, responseMimeType, previousInteractionId,
                serviceTier, webhookConfig, responseFormat,
                environment, generationConfig, safetySettings,
                labels, input);
        }

    }
}
