/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class DocumentDeltaMimeType {

    public static final DocumentDeltaMimeType APPLICATION_PDF = new DocumentDeltaMimeType("application/pdf");
    public static final DocumentDeltaMimeType TEXT_CSV = new DocumentDeltaMimeType("text/csv");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, DocumentDeltaMimeType> values = createValuesMap();
    private static final Map<String, DocumentDeltaMimeTypeEnum> enums = createEnumsMap();

    private final String value;

    private DocumentDeltaMimeType(String value) {
        this.value = value;
    }

    /**
     * Returns a DocumentDeltaMimeType with the given value. For a specific value the
     * returned object will always be a singleton so reference equality
     * is satisfied when the values are the same.
     *
     * @param value value to be wrapped as DocumentDeltaMimeType
     */
    @JsonCreator
    public static DocumentDeltaMimeType of(String value) {
        synchronized (DocumentDeltaMimeType.class) {
            return values.computeIfAbsent(value, v -> new DocumentDeltaMimeType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<DocumentDeltaMimeTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        DocumentDeltaMimeType other = (DocumentDeltaMimeType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "DocumentDeltaMimeType [value=" + value + "]";
    }

    // return an array just like an enum
    public static DocumentDeltaMimeType[] values() {
        synchronized (DocumentDeltaMimeType.class) {
            return values.values().toArray(new DocumentDeltaMimeType[] {});
        }
    }

    private static final Map<String, DocumentDeltaMimeType> createValuesMap() {
        Map<String, DocumentDeltaMimeType> map = new LinkedHashMap<>();
        map.put("application/pdf", APPLICATION_PDF);
        map.put("text/csv", TEXT_CSV);
        return map;
    }

    private static final Map<String, DocumentDeltaMimeTypeEnum> createEnumsMap() {
        Map<String, DocumentDeltaMimeTypeEnum> map = new HashMap<>();
        map.put("application/pdf", DocumentDeltaMimeTypeEnum.APPLICATION_PDF);
        map.put("text/csv", DocumentDeltaMimeTypeEnum.TEXT_CSV);
        return map;
    }

    public enum DocumentDeltaMimeTypeEnum {

        APPLICATION_PDF("application/pdf"),
        TEXT_CSV("text/csv"),
        ;

        private final String value;

        private DocumentDeltaMimeTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}
