/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.google.genai.gaos.utils.LazySingletonValue;
import com.google.genai.gaos.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

/**
 * Environment
 * 
 * <p>Configuration for a custom environment.
 */
@SuppressWarnings("all")
public class Environment {

    @JsonProperty("type")
    private String type;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sources")
    private Optional<? extends List<Source>> sources;

    /**
     * Network configuration for the environment.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("network")
    private Optional<? extends Network> network;

    @JsonCreator
    public Environment(
            @JsonProperty("sources") Optional<? extends List<Source>> sources,
            @JsonProperty("network") Optional<? extends Network> network) {
        Utils.checkNotNull(sources, "sources");
        Utils.checkNotNull(network, "network");
        this.type = Builder._SINGLETON_VALUE_Type.value();
        this.sources = sources;
        this.network = network;
    }
    
    public Environment() {
        this(Optional.empty(), Optional.empty());
    }

    @JsonIgnore
    public String type() {
        return type;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<Source>> sources() {
        return (Optional<List<Source>>) sources;
    }

    /**
     * Network configuration for the environment.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Network> network() {
        return (Optional<Network>) network;
    }

    public static Builder builder() {
        return new Builder();
    }


    public Environment withSources(List<Source> sources) {
        Utils.checkNotNull(sources, "sources");
        this.sources = Optional.ofNullable(sources);
        return this;
    }


    public Environment withSources(Optional<? extends List<Source>> sources) {
        Utils.checkNotNull(sources, "sources");
        this.sources = sources;
        return this;
    }

    /**
     * Network configuration for the environment.
     */
    public Environment withNetwork(Network network) {
        Utils.checkNotNull(network, "network");
        this.network = Optional.ofNullable(network);
        return this;
    }


    /**
     * Network configuration for the environment.
     */
    public Environment withNetwork(Optional<? extends Network> network) {
        Utils.checkNotNull(network, "network");
        this.network = network;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Environment other = (Environment) o;
        return 
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.sources, other.sources) &&
            Utils.enhancedDeepEquals(this.network, other.network);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            type, sources, network);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Environment.class,
                "type", type,
                "sources", sources,
                "network", network);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends List<Source>> sources = Optional.empty();

        private Optional<? extends Network> network = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder sources(List<Source> sources) {
            Utils.checkNotNull(sources, "sources");
            this.sources = Optional.ofNullable(sources);
            return this;
        }

        public Builder sources(Optional<? extends List<Source>> sources) {
            Utils.checkNotNull(sources, "sources");
            this.sources = sources;
            return this;
        }


        /**
         * Network configuration for the environment.
         */
        public Builder network(Network network) {
            Utils.checkNotNull(network, "network");
            this.network = Optional.ofNullable(network);
            return this;
        }

        /**
         * Network configuration for the environment.
         */
        public Builder network(Optional<? extends Network> network) {
            Utils.checkNotNull(network, "network");
            this.network = network;
            return this;
        }

        public Environment build() {

            return new Environment(
                sources, network);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_Type =
                new LazySingletonValue<>(
                        "type",
                        "\"remote\"",
                        new TypeReference<String>() {});
    }
}
