/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * Error
 *
 * <p>Error message from an interaction.
 */
public class Error {
    /**
     * A URI that identifies the error type.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code")
    private String code;

    /**
     * A human-readable error message.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    private String message;

    @JsonCreator
    public Error(@JsonProperty("code") @Nullable String code, @JsonProperty("message") @Nullable String message) {
        this.code = code;
        this.message = message;
    }

    public Error() {
        this(null, null);
    }

    /**
     * A URI that identifies the error type.
     */
    public Optional<String> code() {
        return Optional.ofNullable(this.code);
    }

    /**
     * A human-readable error message.
     */
    public Optional<String> message() {
        return Optional.ofNullable(this.message);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * A URI that identifies the error type.
     */
    public Error withCode(@Nullable String code) {
        this.code = code;
        return this;
    }

    /**
     * A human-readable error message.
     */
    public Error withMessage(@Nullable String message) {
        this.message = message;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Error other = (Error) o;
        return Utils.enhancedDeepEquals(this.code, other.code) && Utils.enhancedDeepEquals(this.message, other.message);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(code, message);
    }

    @Override
    public String toString() {
        return Utils.toString(Error.class, "code", code, "message", message);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private String code;

        private String message;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * A URI that identifies the error type.
         */
        public Builder code(@Nullable String code) {
            this.code = code;
            return this;
        }

        /**
         * A human-readable error message.
         */
        public Builder message(@Nullable String message) {
            this.message = message;
            return this;
        }

        public Error build() {
            return new Error(code, message);
        }
    }
}
