/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Map;
import java.util.Optional;

/**
 * ExaAISearchConfig
 * 
 * <p>Used to specify configuration for ExaAISearch.
 */
@SuppressWarnings("all")
public class ExaAISearchConfig {
    /**
     * Required. The API key for ExaAiSearch.
     */
    @JsonProperty("api_key")
    private String apiKey;

    /**
     * Optional. This field can be used to pass any parameter from the Exa.ai Search API.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("custom_config")
    private Optional<? extends Map<String, Object>> customConfig;

    @JsonCreator
    public ExaAISearchConfig(
            @JsonProperty("api_key") String apiKey,
            @JsonProperty("custom_config") Optional<? extends Map<String, Object>> customConfig) {
        Utils.checkNotNull(apiKey, "apiKey");
        Utils.checkNotNull(customConfig, "customConfig");
        this.apiKey = apiKey;
        this.customConfig = customConfig;
    }
    
    public ExaAISearchConfig(
            String apiKey) {
        this(apiKey, Optional.empty());
    }

    /**
     * Required. The API key for ExaAiSearch.
     */
    @JsonIgnore
    public String apiKey() {
        return apiKey;
    }

    /**
     * Optional. This field can be used to pass any parameter from the Exa.ai Search API.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, Object>> customConfig() {
        return (Optional<Map<String, Object>>) customConfig;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Required. The API key for ExaAiSearch.
     */
    public ExaAISearchConfig withApiKey(String apiKey) {
        Utils.checkNotNull(apiKey, "apiKey");
        this.apiKey = apiKey;
        return this;
    }

    /**
     * Optional. This field can be used to pass any parameter from the Exa.ai Search API.
     */
    public ExaAISearchConfig withCustomConfig(Map<String, Object> customConfig) {
        Utils.checkNotNull(customConfig, "customConfig");
        this.customConfig = Optional.ofNullable(customConfig);
        return this;
    }


    /**
     * Optional. This field can be used to pass any parameter from the Exa.ai Search API.
     */
    public ExaAISearchConfig withCustomConfig(Optional<? extends Map<String, Object>> customConfig) {
        Utils.checkNotNull(customConfig, "customConfig");
        this.customConfig = customConfig;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExaAISearchConfig other = (ExaAISearchConfig) o;
        return 
            Utils.enhancedDeepEquals(this.apiKey, other.apiKey) &&
            Utils.enhancedDeepEquals(this.customConfig, other.customConfig);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            apiKey, customConfig);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ExaAISearchConfig.class,
                "apiKey", apiKey,
                "customConfig", customConfig);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String apiKey;

        private Optional<? extends Map<String, Object>> customConfig = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Required. The API key for ExaAiSearch.
         */
        public Builder apiKey(String apiKey) {
            Utils.checkNotNull(apiKey, "apiKey");
            this.apiKey = apiKey;
            return this;
        }


        /**
         * Optional. This field can be used to pass any parameter from the Exa.ai Search API.
         */
        public Builder customConfig(Map<String, Object> customConfig) {
            Utils.checkNotNull(customConfig, "customConfig");
            this.customConfig = Optional.ofNullable(customConfig);
            return this;
        }

        /**
         * Optional. This field can be used to pass any parameter from the Exa.ai Search API.
         */
        public Builder customConfig(Optional<? extends Map<String, Object>> customConfig) {
            Utils.checkNotNull(customConfig, "customConfig");
            this.customConfig = customConfig;
            return this;
        }

        public ExaAISearchConfig build() {

            return new ExaAISearchConfig(
                apiKey, customConfig);
        }

    }
}
