/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

/**
 * FixRequest
 * 
 * <p>Request parameters specific to FIX sessions, used for generating and
 * validating security patches.
 */
@SuppressWarnings("all")
public class FixRequest {
    /**
     * Additional context or custom instructions provided by the user to guide
     * the patch generation process.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private Optional<String> description;

    /**
     * The identifier of the specific security finding to be remediated. This ID
     * maps to a previously discovered vulnerability.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("finding_id")
    private Optional<String> findingId;

    /**
     * A list of source files providing context for the remediation. These files
     * are typically the ones containing the identified vulnerability.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("source_files")
    private Optional<? extends List<FileContent>> sourceFiles;

    @JsonCreator
    public FixRequest(
            @JsonProperty("description") Optional<String> description,
            @JsonProperty("finding_id") Optional<String> findingId,
            @JsonProperty("source_files") Optional<? extends List<FileContent>> sourceFiles) {
        Utils.checkNotNull(description, "description");
        Utils.checkNotNull(findingId, "findingId");
        Utils.checkNotNull(sourceFiles, "sourceFiles");
        this.description = description;
        this.findingId = findingId;
        this.sourceFiles = sourceFiles;
    }
    
    public FixRequest() {
        this(Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * Additional context or custom instructions provided by the user to guide
     * the patch generation process.
     */
    @JsonIgnore
    public Optional<String> description() {
        return description;
    }

    /**
     * The identifier of the specific security finding to be remediated. This ID
     * maps to a previously discovered vulnerability.
     */
    @JsonIgnore
    public Optional<String> findingId() {
        return findingId;
    }

    /**
     * A list of source files providing context for the remediation. These files
     * are typically the ones containing the identified vulnerability.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<FileContent>> sourceFiles() {
        return (Optional<List<FileContent>>) sourceFiles;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Additional context or custom instructions provided by the user to guide
     * the patch generation process.
     */
    public FixRequest withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = Optional.ofNullable(description);
        return this;
    }


    /**
     * Additional context or custom instructions provided by the user to guide
     * the patch generation process.
     */
    public FixRequest withDescription(Optional<String> description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    /**
     * The identifier of the specific security finding to be remediated. This ID
     * maps to a previously discovered vulnerability.
     */
    public FixRequest withFindingId(String findingId) {
        Utils.checkNotNull(findingId, "findingId");
        this.findingId = Optional.ofNullable(findingId);
        return this;
    }


    /**
     * The identifier of the specific security finding to be remediated. This ID
     * maps to a previously discovered vulnerability.
     */
    public FixRequest withFindingId(Optional<String> findingId) {
        Utils.checkNotNull(findingId, "findingId");
        this.findingId = findingId;
        return this;
    }

    /**
     * A list of source files providing context for the remediation. These files
     * are typically the ones containing the identified vulnerability.
     */
    public FixRequest withSourceFiles(List<FileContent> sourceFiles) {
        Utils.checkNotNull(sourceFiles, "sourceFiles");
        this.sourceFiles = Optional.ofNullable(sourceFiles);
        return this;
    }


    /**
     * A list of source files providing context for the remediation. These files
     * are typically the ones containing the identified vulnerability.
     */
    public FixRequest withSourceFiles(Optional<? extends List<FileContent>> sourceFiles) {
        Utils.checkNotNull(sourceFiles, "sourceFiles");
        this.sourceFiles = sourceFiles;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FixRequest other = (FixRequest) o;
        return 
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.findingId, other.findingId) &&
            Utils.enhancedDeepEquals(this.sourceFiles, other.sourceFiles);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            description, findingId, sourceFiles);
    }
    
    @Override
    public String toString() {
        return Utils.toString(FixRequest.class,
                "description", description,
                "findingId", findingId,
                "sourceFiles", sourceFiles);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> description = Optional.empty();

        private Optional<String> findingId = Optional.empty();

        private Optional<? extends List<FileContent>> sourceFiles = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Additional context or custom instructions provided by the user to guide
         * the patch generation process.
         */
        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * Additional context or custom instructions provided by the user to guide
         * the patch generation process.
         */
        public Builder description(Optional<String> description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }


        /**
         * The identifier of the specific security finding to be remediated. This ID
         * maps to a previously discovered vulnerability.
         */
        public Builder findingId(String findingId) {
            Utils.checkNotNull(findingId, "findingId");
            this.findingId = Optional.ofNullable(findingId);
            return this;
        }

        /**
         * The identifier of the specific security finding to be remediated. This ID
         * maps to a previously discovered vulnerability.
         */
        public Builder findingId(Optional<String> findingId) {
            Utils.checkNotNull(findingId, "findingId");
            this.findingId = findingId;
            return this;
        }


        /**
         * A list of source files providing context for the remediation. These files
         * are typically the ones containing the identified vulnerability.
         */
        public Builder sourceFiles(List<FileContent> sourceFiles) {
            Utils.checkNotNull(sourceFiles, "sourceFiles");
            this.sourceFiles = Optional.ofNullable(sourceFiles);
            return this;
        }

        /**
         * A list of source files providing context for the remediation. These files
         * are typically the ones containing the identified vulnerability.
         */
        public Builder sourceFiles(Optional<? extends List<FileContent>> sourceFiles) {
            Utils.checkNotNull(sourceFiles, "sourceFiles");
            this.sourceFiles = sourceFiles;
            return this;
        }

        public FixRequest build() {

            return new FixRequest(
                description, findingId, sourceFiles);
        }

    }
}
