/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.google.genai.gaos.models.agents.AgentTool;
import com.google.genai.gaos.utils.LazySingletonValue;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * Function
 * 
 * <p>A tool that can be used by the model.
 */
public class Function implements AgentTool, Tool {
    /**
     * A description of the function.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private String description;

    /**
     * The name of the function.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private String name;

    /**
     * The JSON Schema for the function's parameters.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("parameters")
    private Object parameters;


    @JsonProperty("type")
    private String type;

    @JsonCreator
    public Function(
            @JsonProperty("description") @Nullable String description,
            @JsonProperty("name") @Nullable String name,
            @JsonProperty("parameters") @Nullable Object parameters) {
        this.description = description;
        this.name = name;
        this.parameters = parameters;
        this.type = Builder._SINGLETON_VALUE_Type.value();
    }
    
    public Function() {
        this(null, null, null);
    }

    /**
     * A description of the function.
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The name of the function.
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The JSON Schema for the function's parameters.
     */
    public Optional<Object> parameters() {
        return Optional.ofNullable(this.parameters);
    }

    @Override
    public String type() {
        return Utils.discriminatorToString(type);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A description of the function.
     */
    public Function withDescription(@Nullable String description) {
        this.description = description;
        return this;
    }


    /**
     * The name of the function.
     */
    public Function withName(@Nullable String name) {
        this.name = name;
        return this;
    }


    /**
     * The JSON Schema for the function's parameters.
     */
    public Function withParameters(@Nullable Object parameters) {
        this.parameters = parameters;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Function other = (Function) o;
        return 
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.parameters, other.parameters) &&
            Utils.enhancedDeepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            description, name, parameters,
            type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Function.class,
                "description", description,
                "name", name,
                "parameters", parameters,
                "type", type);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String description;

        private String name;

        private Object parameters;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * A description of the function.
         */
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }

        /**
         * The name of the function.
         */
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /**
         * The JSON Schema for the function's parameters.
         */
        public Builder parameters(@Nullable Object parameters) {
            this.parameters = parameters;
            return this;
        }

        public Function build() {
            return new Function(
                description, name, parameters);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_Type =
                new LazySingletonValue<>(
                        "type",
                        "\"function\"",
                        new TypeReference<String>() {});
    }
}
