/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.google.genai.gaos.utils.LazySingletonValue;
import com.google.genai.gaos.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * FunctionResultStep
 * 
 * <p>Result of a function tool call.
 */
@SuppressWarnings("all")
public class FunctionResultStep {

    @JsonProperty("type")
    private String type;

    /**
     * The name of the tool that was called.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private Optional<String> name;

    /**
     * Whether the tool call resulted in an error.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_error")
    private Optional<Boolean> isError;

    /**
     * Required. ID to match the ID from the function call block.
     */
    @JsonProperty("call_id")
    private String callId;

    /**
     * The result of the tool call.
     */
    @JsonProperty("result")
    private FunctionResultStepResultUnion result;

    @JsonCreator
    public FunctionResultStep(
            @JsonProperty("name") Optional<String> name,
            @JsonProperty("is_error") Optional<Boolean> isError,
            @JsonProperty("call_id") String callId,
            @JsonProperty("result") FunctionResultStepResultUnion result) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(isError, "isError");
        Utils.checkNotNull(callId, "callId");
        Utils.checkNotNull(result, "result");
        this.type = Builder._SINGLETON_VALUE_Type.value();
        this.name = name;
        this.isError = isError;
        this.callId = callId;
        this.result = result;
    }
    
    public FunctionResultStep(
            String callId,
            FunctionResultStepResultUnion result) {
        this(Optional.empty(), Optional.empty(), callId,
            result);
    }

    @JsonIgnore
    public String type() {
        return type;
    }

    /**
     * The name of the tool that was called.
     */
    @JsonIgnore
    public Optional<String> name() {
        return name;
    }

    /**
     * Whether the tool call resulted in an error.
     */
    @JsonIgnore
    public Optional<Boolean> isError() {
        return isError;
    }

    /**
     * Required. ID to match the ID from the function call block.
     */
    @JsonIgnore
    public String callId() {
        return callId;
    }

    /**
     * The result of the tool call.
     */
    @JsonIgnore
    public FunctionResultStepResultUnion result() {
        return result;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The name of the tool that was called.
     */
    public FunctionResultStep withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = Optional.ofNullable(name);
        return this;
    }


    /**
     * The name of the tool that was called.
     */
    public FunctionResultStep withName(Optional<String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * Whether the tool call resulted in an error.
     */
    public FunctionResultStep withIsError(boolean isError) {
        Utils.checkNotNull(isError, "isError");
        this.isError = Optional.ofNullable(isError);
        return this;
    }


    /**
     * Whether the tool call resulted in an error.
     */
    public FunctionResultStep withIsError(Optional<Boolean> isError) {
        Utils.checkNotNull(isError, "isError");
        this.isError = isError;
        return this;
    }

    /**
     * Required. ID to match the ID from the function call block.
     */
    public FunctionResultStep withCallId(String callId) {
        Utils.checkNotNull(callId, "callId");
        this.callId = callId;
        return this;
    }

    /**
     * The result of the tool call.
     */
    public FunctionResultStep withResult(FunctionResultStepResultUnion result) {
        Utils.checkNotNull(result, "result");
        this.result = result;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FunctionResultStep other = (FunctionResultStep) o;
        return 
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.isError, other.isError) &&
            Utils.enhancedDeepEquals(this.callId, other.callId) &&
            Utils.enhancedDeepEquals(this.result, other.result);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            type, name, isError,
            callId, result);
    }
    
    @Override
    public String toString() {
        return Utils.toString(FunctionResultStep.class,
                "type", type,
                "name", name,
                "isError", isError,
                "callId", callId,
                "result", result);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> name = Optional.empty();

        private Optional<Boolean> isError = Optional.empty();

        private String callId;

        private FunctionResultStepResultUnion result;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The name of the tool that was called.
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * The name of the tool that was called.
         */
        public Builder name(Optional<String> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }


        /**
         * Whether the tool call resulted in an error.
         */
        public Builder isError(boolean isError) {
            Utils.checkNotNull(isError, "isError");
            this.isError = Optional.ofNullable(isError);
            return this;
        }

        /**
         * Whether the tool call resulted in an error.
         */
        public Builder isError(Optional<Boolean> isError) {
            Utils.checkNotNull(isError, "isError");
            this.isError = isError;
            return this;
        }


        /**
         * Required. ID to match the ID from the function call block.
         */
        public Builder callId(String callId) {
            Utils.checkNotNull(callId, "callId");
            this.callId = callId;
            return this;
        }


        /**
         * The result of the tool call.
         */
        public Builder result(FunctionResultStepResultUnion result) {
            Utils.checkNotNull(result, "result");
            this.result = result;
            return this;
        }

        public FunctionResultStep build() {

            return new FunctionResultStep(
                name, isError, callId,
                result);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_Type =
                new LazySingletonValue<>(
                        "type",
                        "\"function_result\"",
                        new TypeReference<String>() {});
    }
}
