/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.google.genai.gaos.utils.LazySingletonValue;
import com.google.genai.gaos.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * GoogleMapsResultStep
 * 
 * <p>Google Maps result step.
 */
@SuppressWarnings("all")
public class GoogleMapsResultStep {
    /**
     * Required. ID to match the ID from the function call block.
     */
    @JsonProperty("call_id")
    private String callId;


    @JsonProperty("result")
    private List<GoogleMapsResult> result;

    /**
     * A signature hash for backend validation.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("signature")
    private Optional<String> signature;


    @JsonProperty("type")
    private String type;

    @JsonCreator
    public GoogleMapsResultStep(
            @JsonProperty("call_id") String callId,
            @JsonProperty("result") List<GoogleMapsResult> result,
            @JsonProperty("signature") Optional<String> signature) {
        Utils.checkNotNull(callId, "callId");
        Utils.checkNotNull(result, "result");
        Utils.checkNotNull(signature, "signature");
        this.callId = callId;
        this.result = result;
        this.signature = signature;
        this.type = Builder._SINGLETON_VALUE_Type.value();
    }
    
    public GoogleMapsResultStep(
            String callId,
            List<GoogleMapsResult> result) {
        this(callId, result, Optional.empty());
    }

    /**
     * Required. ID to match the ID from the function call block.
     */
    @JsonIgnore
    public String callId() {
        return callId;
    }

    @JsonIgnore
    public List<GoogleMapsResult> result() {
        return result;
    }

    /**
     * A signature hash for backend validation.
     */
    @JsonIgnore
    public Optional<String> signature() {
        return signature;
    }

    @JsonIgnore
    public String type() {
        return type;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Required. ID to match the ID from the function call block.
     */
    public GoogleMapsResultStep withCallId(String callId) {
        Utils.checkNotNull(callId, "callId");
        this.callId = callId;
        return this;
    }

    public GoogleMapsResultStep withResult(List<GoogleMapsResult> result) {
        Utils.checkNotNull(result, "result");
        this.result = result;
        return this;
    }

    /**
     * A signature hash for backend validation.
     */
    public GoogleMapsResultStep withSignature(String signature) {
        Utils.checkNotNull(signature, "signature");
        this.signature = Optional.ofNullable(signature);
        return this;
    }


    /**
     * A signature hash for backend validation.
     */
    public GoogleMapsResultStep withSignature(Optional<String> signature) {
        Utils.checkNotNull(signature, "signature");
        this.signature = signature;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GoogleMapsResultStep other = (GoogleMapsResultStep) o;
        return 
            Utils.enhancedDeepEquals(this.callId, other.callId) &&
            Utils.enhancedDeepEquals(this.result, other.result) &&
            Utils.enhancedDeepEquals(this.signature, other.signature) &&
            Utils.enhancedDeepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            callId, result, signature,
            type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GoogleMapsResultStep.class,
                "callId", callId,
                "result", result,
                "signature", signature,
                "type", type);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String callId;

        private List<GoogleMapsResult> result;

        private Optional<String> signature = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Required. ID to match the ID from the function call block.
         */
        public Builder callId(String callId) {
            Utils.checkNotNull(callId, "callId");
            this.callId = callId;
            return this;
        }


        public Builder result(List<GoogleMapsResult> result) {
            Utils.checkNotNull(result, "result");
            this.result = result;
            return this;
        }


        /**
         * A signature hash for backend validation.
         */
        public Builder signature(String signature) {
            Utils.checkNotNull(signature, "signature");
            this.signature = Optional.ofNullable(signature);
            return this;
        }

        /**
         * A signature hash for backend validation.
         */
        public Builder signature(Optional<String> signature) {
            Utils.checkNotNull(signature, "signature");
            this.signature = signature;
            return this;
        }

        public GoogleMapsResultStep build() {

            return new GoogleMapsResultStep(
                callId, result, signature);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_Type =
                new LazySingletonValue<>(
                        "type",
                        "\"google_maps_result\"",
                        new TypeReference<String>() {});
    }
}
