/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.google.genai.gaos.utils.LazySingletonValue;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class GoogleMapsCallDelta implements StepDeltaData {
    /**
     * The arguments to pass to the Google Maps tool.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("arguments")
    private GoogleMapsCallArguments arguments;

    /**
     * A signature hash for backend validation.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("signature")
    private String signature;


    @JsonProperty("type")
    private String type;

    @JsonCreator
    public GoogleMapsCallDelta(
            @JsonProperty("arguments") @Nullable GoogleMapsCallArguments arguments,
            @JsonProperty("signature") @Nullable String signature) {
        this.arguments = arguments;
        this.signature = signature;
        this.type = Builder._SINGLETON_VALUE_Type.value();
    }
    
    public GoogleMapsCallDelta() {
        this(null, null);
    }

    /**
     * The arguments to pass to the Google Maps tool.
     */
    public Optional<GoogleMapsCallArguments> arguments() {
        return Optional.ofNullable(this.arguments);
    }

    /**
     * A signature hash for backend validation.
     */
    public Optional<String> signature() {
        return Optional.ofNullable(this.signature);
    }

    @Override
    public String type() {
        return Utils.discriminatorToString(type);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The arguments to pass to the Google Maps tool.
     */
    public GoogleMapsCallDelta withArguments(@Nullable GoogleMapsCallArguments arguments) {
        this.arguments = arguments;
        return this;
    }


    /**
     * A signature hash for backend validation.
     */
    public GoogleMapsCallDelta withSignature(@Nullable String signature) {
        this.signature = signature;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GoogleMapsCallDelta other = (GoogleMapsCallDelta) o;
        return 
            Utils.enhancedDeepEquals(this.arguments, other.arguments) &&
            Utils.enhancedDeepEquals(this.signature, other.signature) &&
            Utils.enhancedDeepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            arguments, signature, type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GoogleMapsCallDelta.class,
                "arguments", arguments,
                "signature", signature,
                "type", type);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private GoogleMapsCallArguments arguments;

        private String signature;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The arguments to pass to the Google Maps tool.
         */
        public Builder arguments(@Nullable GoogleMapsCallArguments arguments) {
            this.arguments = arguments;
            return this;
        }

        /**
         * A signature hash for backend validation.
         */
        public Builder signature(@Nullable String signature) {
            this.signature = signature;
            return this;
        }

        public GoogleMapsCallDelta build() {
            return new GoogleMapsCallDelta(
                arguments, signature);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_Type =
                new LazySingletonValue<>(
                        "type",
                        "\"google_maps_call\"",
                        new TypeReference<String>() {});
    }
}
