/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

/**
 * GoogleMapsCallArguments
 * 
 * <p>The arguments to pass to the Google Maps tool.
 */
@SuppressWarnings("all")
public class GoogleMapsCallArguments {
    /**
     * The queries to be executed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("queries")
    private Optional<? extends List<String>> queries;

    @JsonCreator
    public GoogleMapsCallArguments(
            @JsonProperty("queries") Optional<? extends List<String>> queries) {
        Utils.checkNotNull(queries, "queries");
        this.queries = queries;
    }
    
    public GoogleMapsCallArguments() {
        this(Optional.empty());
    }

    /**
     * The queries to be executed.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> queries() {
        return (Optional<List<String>>) queries;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The queries to be executed.
     */
    public GoogleMapsCallArguments withQueries(List<String> queries) {
        Utils.checkNotNull(queries, "queries");
        this.queries = Optional.ofNullable(queries);
        return this;
    }


    /**
     * The queries to be executed.
     */
    public GoogleMapsCallArguments withQueries(Optional<? extends List<String>> queries) {
        Utils.checkNotNull(queries, "queries");
        this.queries = queries;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GoogleMapsCallArguments other = (GoogleMapsCallArguments) o;
        return 
            Utils.enhancedDeepEquals(this.queries, other.queries);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            queries);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GoogleMapsCallArguments.class,
                "queries", queries);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends List<String>> queries = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The queries to be executed.
         */
        public Builder queries(List<String> queries) {
            Utils.checkNotNull(queries, "queries");
            this.queries = Optional.ofNullable(queries);
            return this;
        }

        /**
         * The queries to be executed.
         */
        public Builder queries(Optional<? extends List<String>> queries) {
            Utils.checkNotNull(queries, "queries");
            this.queries = queries;
            return this;
        }

        public GoogleMapsCallArguments build() {

            return new GoogleMapsCallArguments(
                queries);
        }

    }
}
