/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class HarmCategory {

    public static final HarmCategory HATE_SPEECH = new HarmCategory("hate_speech");
    public static final HarmCategory DANGEROUS_CONTENT = new HarmCategory("dangerous_content");
    public static final HarmCategory HARASSMENT = new HarmCategory("harassment");
    public static final HarmCategory SEXUALLY_EXPLICIT = new HarmCategory("sexually_explicit");
    public static final HarmCategory CIVIC_INTEGRITY = new HarmCategory("civic_integrity");
    public static final HarmCategory IMAGE_HATE = new HarmCategory("image_hate");
    public static final HarmCategory IMAGE_DANGEROUS_CONTENT = new HarmCategory("image_dangerous_content");
    public static final HarmCategory IMAGE_HARASSMENT = new HarmCategory("image_harassment");
    public static final HarmCategory IMAGE_SEXUALLY_EXPLICIT = new HarmCategory("image_sexually_explicit");
    public static final HarmCategory JAILBREAK = new HarmCategory("jailbreak");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, HarmCategory> values = createValuesMap();
    private static final Map<String, HarmCategoryEnum> enums = createEnumsMap();

    private final String value;

    private HarmCategory(String value) {
        this.value = value;
    }

    /**
     * Returns a HarmCategory with the given value. For a specific value the
     * returned object will always be a singleton so reference equality
     * is satisfied when the values are the same.
     *
     * @param value value to be wrapped as HarmCategory
     */
    @JsonCreator
    public static HarmCategory of(String value) {
        synchronized (HarmCategory.class) {
            return values.computeIfAbsent(value, v -> new HarmCategory(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<HarmCategoryEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        HarmCategory other = (HarmCategory) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "HarmCategory [value=" + value + "]";
    }

    // return an array just like an enum
    public static HarmCategory[] values() {
        synchronized (HarmCategory.class) {
            return values.values().toArray(new HarmCategory[] {});
        }
    }

    private static final Map<String, HarmCategory> createValuesMap() {
        Map<String, HarmCategory> map = new LinkedHashMap<>();
        map.put("hate_speech", HATE_SPEECH);
        map.put("dangerous_content", DANGEROUS_CONTENT);
        map.put("harassment", HARASSMENT);
        map.put("sexually_explicit", SEXUALLY_EXPLICIT);
        map.put("civic_integrity", CIVIC_INTEGRITY);
        map.put("image_hate", IMAGE_HATE);
        map.put("image_dangerous_content", IMAGE_DANGEROUS_CONTENT);
        map.put("image_harassment", IMAGE_HARASSMENT);
        map.put("image_sexually_explicit", IMAGE_SEXUALLY_EXPLICIT);
        map.put("jailbreak", JAILBREAK);
        return map;
    }

    private static final Map<String, HarmCategoryEnum> createEnumsMap() {
        Map<String, HarmCategoryEnum> map = new HashMap<>();
        map.put("hate_speech", HarmCategoryEnum.HATE_SPEECH);
        map.put("dangerous_content", HarmCategoryEnum.DANGEROUS_CONTENT);
        map.put("harassment", HarmCategoryEnum.HARASSMENT);
        map.put("sexually_explicit", HarmCategoryEnum.SEXUALLY_EXPLICIT);
        map.put("civic_integrity", HarmCategoryEnum.CIVIC_INTEGRITY);
        map.put("image_hate", HarmCategoryEnum.IMAGE_HATE);
        map.put("image_dangerous_content", HarmCategoryEnum.IMAGE_DANGEROUS_CONTENT);
        map.put("image_harassment", HarmCategoryEnum.IMAGE_HARASSMENT);
        map.put("image_sexually_explicit", HarmCategoryEnum.IMAGE_SEXUALLY_EXPLICIT);
        map.put("jailbreak", HarmCategoryEnum.JAILBREAK);
        return map;
    }

    public enum HarmCategoryEnum {

        HATE_SPEECH("hate_speech"),
        DANGEROUS_CONTENT("dangerous_content"),
        HARASSMENT("harassment"),
        SEXUALLY_EXPLICIT("sexually_explicit"),
        CIVIC_INTEGRITY("civic_integrity"),
        IMAGE_HATE("image_hate"),
        IMAGE_DANGEROUS_CONTENT("image_dangerous_content"),
        IMAGE_HARASSMENT("image_harassment"),
        IMAGE_SEXUALLY_EXPLICIT("image_sexually_explicit"),
        JAILBREAK("jailbreak"),
        ;

        private final String value;

        private HarmCategoryEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}
