/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * ImageResponseFormatDelivery
 * 
 * <p>The delivery mode for the image output.
 */
public class ImageResponseFormatDelivery {

    public static final ImageResponseFormatDelivery INLINE = new ImageResponseFormatDelivery("inline");
    public static final ImageResponseFormatDelivery URI = new ImageResponseFormatDelivery("uri");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, ImageResponseFormatDelivery> values = createValuesMap();
    private static final Map<String, ImageResponseFormatDeliveryEnum> enums = createEnumsMap();

    private final String value;

    private ImageResponseFormatDelivery(String value) {
        this.value = value;
    }

    /**
     * Returns a ImageResponseFormatDelivery with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as ImageResponseFormatDelivery
     */ 
    @JsonCreator
    public static ImageResponseFormatDelivery of(String value) {
        synchronized (ImageResponseFormatDelivery.class) {
            return values.computeIfAbsent(value, v -> new ImageResponseFormatDelivery(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<ImageResponseFormatDeliveryEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        ImageResponseFormatDelivery other = (ImageResponseFormatDelivery) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "ImageResponseFormatDelivery [value=" + value + "]";
    }

    // return an array just like an enum
    public static ImageResponseFormatDelivery[] values() {
        synchronized (ImageResponseFormatDelivery.class) {
            return values.values().toArray(new ImageResponseFormatDelivery[] {});
        }
    }

    private static final Map<String, ImageResponseFormatDelivery> createValuesMap() {
        Map<String, ImageResponseFormatDelivery> map = new LinkedHashMap<>();
        map.put("inline", INLINE);
        map.put("uri", URI);
        return map;
    }

    private static final Map<String, ImageResponseFormatDeliveryEnum> createEnumsMap() {
        Map<String, ImageResponseFormatDeliveryEnum> map = new HashMap<>();
        map.put("inline", ImageResponseFormatDeliveryEnum.INLINE);
        map.put("uri", ImageResponseFormatDeliveryEnum.URI);
        return map;
    }
    
    
    public enum ImageResponseFormatDeliveryEnum {

        INLINE("inline"),
        URI("uri"),;

        private final String value;

        private ImageResponseFormatDeliveryEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

