/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.google.genai.gaos.utils.LazySingletonValue;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * ImageContent
 * 
 * <p>An image content block.
 */
public class ImageContent implements Content, ThoughtSummaryContent, FunctionResultSubcontent {
    /**
     * The image content.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    private String data;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resolution")
    private MediaResolution resolution;


    @JsonProperty("type")
    private String type;

    /**
     * The URI of the image.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("uri")
    private String uri;

    /**
     * The mime type of the image.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mime_type")
    private ImageContentMimeType mimeType;

    @JsonCreator
    public ImageContent(
            @JsonProperty("data") @Nullable String data,
            @JsonProperty("resolution") @Nullable MediaResolution resolution,
            @JsonProperty("uri") @Nullable String uri,
            @JsonProperty("mime_type") @Nullable ImageContentMimeType mimeType) {
        this.data = data;
        this.resolution = resolution;
        this.type = Builder._SINGLETON_VALUE_Type.value();
        this.uri = uri;
        this.mimeType = mimeType;
    }
    
    public ImageContent() {
        this(null, null, null,
            null);
    }

    /**
     * The image content.
     */
    public Optional<String> data() {
        return Optional.ofNullable(this.data);
    }

    public Optional<MediaResolution> resolution() {
        return Optional.ofNullable(this.resolution);
    }

    @Override
    public String type() {
        return Utils.discriminatorToString(type);
    }

    /**
     * The URI of the image.
     */
    public Optional<String> uri() {
        return Optional.ofNullable(this.uri);
    }

    /**
     * The mime type of the image.
     */
    public Optional<ImageContentMimeType> mimeType() {
        return Optional.ofNullable(this.mimeType);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The image content.
     */
    public ImageContent withData(@Nullable String data) {
        this.data = data;
        return this;
    }


    public ImageContent withResolution(@Nullable MediaResolution resolution) {
        this.resolution = resolution;
        return this;
    }


    /**
     * The URI of the image.
     */
    public ImageContent withUri(@Nullable String uri) {
        this.uri = uri;
        return this;
    }


    /**
     * The mime type of the image.
     */
    public ImageContent withMimeType(@Nullable ImageContentMimeType mimeType) {
        this.mimeType = mimeType;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ImageContent other = (ImageContent) o;
        return 
            Utils.enhancedDeepEquals(this.data, other.data) &&
            Utils.enhancedDeepEquals(this.resolution, other.resolution) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.uri, other.uri) &&
            Utils.enhancedDeepEquals(this.mimeType, other.mimeType);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            data, resolution, type,
            uri, mimeType);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ImageContent.class,
                "data", data,
                "resolution", resolution,
                "type", type,
                "uri", uri,
                "mimeType", mimeType);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String data;

        private MediaResolution resolution;

        private String uri;

        private ImageContentMimeType mimeType;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The image content.
         */
        public Builder data(@Nullable String data) {
            this.data = data;
            return this;
        }

        public Builder resolution(@Nullable MediaResolution resolution) {
            this.resolution = resolution;
            return this;
        }

        /**
         * The URI of the image.
         */
        public Builder uri(@Nullable String uri) {
            this.uri = uri;
            return this;
        }

        /**
         * The mime type of the image.
         */
        public Builder mimeType(@Nullable ImageContentMimeType mimeType) {
            this.mimeType = mimeType;
            return this;
        }

        public ImageContent build() {
            return new ImageContent(
                data, resolution, uri,
                mimeType);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_Type =
                new LazySingletonValue<>(
                        "type",
                        "\"image\"",
                        new TypeReference<String>() {});
    }
}
