/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses without runtime
 * errors. Instances are immutable singletons with reference equality. Use {@code asEnum()} for
 * switch expressions.
 */
/**
 * ImageResponseFormatAspectRatio
 *
 * <p>The aspect ratio for the image output.
 */
public class ImageResponseFormatAspectRatio {

  public static final ImageResponseFormatAspectRatio ELEVEN =
      new ImageResponseFormatAspectRatio("1:1");
  public static final ImageResponseFormatAspectRatio TWENTY_THREE =
      new ImageResponseFormatAspectRatio("2:3");
  public static final ImageResponseFormatAspectRatio THIRTY_TWO =
      new ImageResponseFormatAspectRatio("3:2");
  public static final ImageResponseFormatAspectRatio THIRTY_FOUR =
      new ImageResponseFormatAspectRatio("3:4");
  public static final ImageResponseFormatAspectRatio FORTY_THREE =
      new ImageResponseFormatAspectRatio("4:3");
  public static final ImageResponseFormatAspectRatio FORTY_FIVE =
      new ImageResponseFormatAspectRatio("4:5");
  public static final ImageResponseFormatAspectRatio FIFTY_FOUR =
      new ImageResponseFormatAspectRatio("5:4");
  public static final ImageResponseFormatAspectRatio NINE_HUNDRED_AND_SIXTEEN =
      new ImageResponseFormatAspectRatio("9:16");
  public static final ImageResponseFormatAspectRatio ONE_HUNDRED_AND_SIXTY_NINE =
      new ImageResponseFormatAspectRatio("16:9");
  public static final ImageResponseFormatAspectRatio TWO_HUNDRED_AND_NINETEEN =
      new ImageResponseFormatAspectRatio("21:9");
  public static final ImageResponseFormatAspectRatio EIGHTEEN =
      new ImageResponseFormatAspectRatio("1:8");
  public static final ImageResponseFormatAspectRatio EIGHTY_ONE =
      new ImageResponseFormatAspectRatio("8:1");
  public static final ImageResponseFormatAspectRatio FOURTEEN =
      new ImageResponseFormatAspectRatio("1:4");
  public static final ImageResponseFormatAspectRatio FORTY_ONE =
      new ImageResponseFormatAspectRatio("4:1");

  // This map will grow whenever a Color gets created with a new
  // unrecognized value (a potential memory leak if the user is not
  // careful). Keep this field lower case to avoid clashing with
  // generated member names which will always be upper cased (Java
  // convention)
  private static final Map<String, ImageResponseFormatAspectRatio> values = createValuesMap();
  private static final Map<String, ImageResponseFormatAspectRatioEnum> enums = createEnumsMap();

  private final String value;

  private ImageResponseFormatAspectRatio(String value) {
    this.value = value;
  }

  /**
   * Returns a ImageResponseFormatAspectRatio with the given value. For a specific value the
   * returned object will always be a singleton so reference equality is satisfied when the values
   * are the same.
   *
   * @param value value to be wrapped as ImageResponseFormatAspectRatio
   */
  @JsonCreator
  public static ImageResponseFormatAspectRatio of(String value) {
    synchronized (ImageResponseFormatAspectRatio.class) {
      return values.computeIfAbsent(value, v -> new ImageResponseFormatAspectRatio(v));
    }
  }

  @JsonValue
  public String value() {
    return value;
  }

  public Optional<ImageResponseFormatAspectRatioEnum> asEnum() {
    return Optional.ofNullable(enums.getOrDefault(value, null));
  }

  public boolean isKnown() {
    return asEnum().isPresent();
  }

  @Override
  public int hashCode() {
    return Objects.hash(value);
  }

  @Override
  public boolean equals(java.lang.Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    ImageResponseFormatAspectRatio other = (ImageResponseFormatAspectRatio) obj;
    return Objects.equals(value, other.value);
  }

  @Override
  public String toString() {
    return "ImageResponseFormatAspectRatio [value=" + value + "]";
  }

  // return an array just like an enum
  public static ImageResponseFormatAspectRatio[] values() {
    synchronized (ImageResponseFormatAspectRatio.class) {
      return values.values().toArray(new ImageResponseFormatAspectRatio[] {});
    }
  }

  private static final Map<String, ImageResponseFormatAspectRatio> createValuesMap() {
    Map<String, ImageResponseFormatAspectRatio> map = new LinkedHashMap<>();
    map.put("1:1", ELEVEN);
    map.put("2:3", TWENTY_THREE);
    map.put("3:2", THIRTY_TWO);
    map.put("3:4", THIRTY_FOUR);
    map.put("4:3", FORTY_THREE);
    map.put("4:5", FORTY_FIVE);
    map.put("5:4", FIFTY_FOUR);
    map.put("9:16", NINE_HUNDRED_AND_SIXTEEN);
    map.put("16:9", ONE_HUNDRED_AND_SIXTY_NINE);
    map.put("21:9", TWO_HUNDRED_AND_NINETEEN);
    map.put("1:8", EIGHTEEN);
    map.put("8:1", EIGHTY_ONE);
    map.put("1:4", FOURTEEN);
    map.put("4:1", FORTY_ONE);
    return map;
  }

  private static final Map<String, ImageResponseFormatAspectRatioEnum> createEnumsMap() {
    Map<String, ImageResponseFormatAspectRatioEnum> map = new HashMap<>();
    map.put("1:1", ImageResponseFormatAspectRatioEnum.ELEVEN);
    map.put("2:3", ImageResponseFormatAspectRatioEnum.TWENTY_THREE);
    map.put("3:2", ImageResponseFormatAspectRatioEnum.THIRTY_TWO);
    map.put("3:4", ImageResponseFormatAspectRatioEnum.THIRTY_FOUR);
    map.put("4:3", ImageResponseFormatAspectRatioEnum.FORTY_THREE);
    map.put("4:5", ImageResponseFormatAspectRatioEnum.FORTY_FIVE);
    map.put("5:4", ImageResponseFormatAspectRatioEnum.FIFTY_FOUR);
    map.put("9:16", ImageResponseFormatAspectRatioEnum.NINE_HUNDRED_AND_SIXTEEN);
    map.put("16:9", ImageResponseFormatAspectRatioEnum.ONE_HUNDRED_AND_SIXTY_NINE);
    map.put("21:9", ImageResponseFormatAspectRatioEnum.TWO_HUNDRED_AND_NINETEEN);
    map.put("1:8", ImageResponseFormatAspectRatioEnum.EIGHTEEN);
    map.put("8:1", ImageResponseFormatAspectRatioEnum.EIGHTY_ONE);
    map.put("1:4", ImageResponseFormatAspectRatioEnum.FOURTEEN);
    map.put("4:1", ImageResponseFormatAspectRatioEnum.FORTY_ONE);
    return map;
  }

  public enum ImageResponseFormatAspectRatioEnum {
    ELEVEN("1:1"),
    TWENTY_THREE("2:3"),
    THIRTY_TWO("3:2"),
    THIRTY_FOUR("3:4"),
    FORTY_THREE("4:3"),
    FORTY_FIVE("4:5"),
    FIFTY_FOUR("5:4"),
    NINE_HUNDRED_AND_SIXTEEN("9:16"),
    ONE_HUNDRED_AND_SIXTY_NINE("16:9"),
    TWO_HUNDRED_AND_NINETEEN("21:9"),
    EIGHTEEN("1:8"),
    EIGHTY_ONE("8:1"),
    FOURTEEN("1:4"),
    FORTY_ONE("4:1"),
    ;

    private final String value;

    private ImageResponseFormatAspectRatioEnum(String value) {
      this.value = value;
    }

    public String value() {
      return value;
    }
  }
}
