/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ImageResponseFormatAspectRatio
 * 
 * <p>The aspect ratio for the image output.
 */
@SuppressWarnings("all")
public enum ImageResponseFormatAspectRatio {
    ELEVEN("1:1"),
    TWENTY_THREE("2:3"),
    THIRTY_TWO("3:2"),
    THIRTY_FOUR("3:4"),
    FORTY_THREE("4:3"),
    FORTY_FIVE("4:5"),
    FIFTY_FOUR("5:4"),
    NINE_HUNDRED_AND_SIXTEEN("9:16"),
    ONE_HUNDRED_AND_SIXTY_NINE("16:9"),
    TWO_HUNDRED_AND_NINETEEN("21:9"),
    EIGHTEEN("1:8"),
    EIGHTY_ONE("8:1"),
    FOURTEEN("1:4"),
    FORTY_ONE("4:1");

    @JsonValue
    private final String value;

    ImageResponseFormatAspectRatio(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ImageResponseFormatAspectRatio> fromValue(String value) {
        for (ImageResponseFormatAspectRatio o: ImageResponseFormatAspectRatio.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

