/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.google.genai.gaos.utils.LazySingletonValue;
import com.google.genai.gaos.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * MCPServerToolResultStep
 * 
 * <p>MCPServer tool result step.
 */
@SuppressWarnings("all")
public class MCPServerToolResultStep {
    /**
     * Required. ID to match the ID from the function call block.
     */
    @JsonProperty("call_id")
    private String callId;

    /**
     * Name of the tool which is called for this specific tool call.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private Optional<String> name;

    /**
     * The output from the MCP server call. Can be simple text or rich content.
     */
    @JsonProperty("result")
    private MCPServerToolResultStepResultUnion result;

    /**
     * The name of the used MCP server.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("server_name")
    private Optional<String> serverName;


    @JsonProperty("type")
    private String type;

    @JsonCreator
    public MCPServerToolResultStep(
            @JsonProperty("call_id") String callId,
            @JsonProperty("name") Optional<String> name,
            @JsonProperty("result") MCPServerToolResultStepResultUnion result,
            @JsonProperty("server_name") Optional<String> serverName) {
        Utils.checkNotNull(callId, "callId");
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(result, "result");
        Utils.checkNotNull(serverName, "serverName");
        this.callId = callId;
        this.name = name;
        this.result = result;
        this.serverName = serverName;
        this.type = Builder._SINGLETON_VALUE_Type.value();
    }
    
    public MCPServerToolResultStep(
            String callId,
            MCPServerToolResultStepResultUnion result) {
        this(callId, Optional.empty(), result,
            Optional.empty());
    }

    /**
     * Required. ID to match the ID from the function call block.
     */
    @JsonIgnore
    public String callId() {
        return callId;
    }

    /**
     * Name of the tool which is called for this specific tool call.
     */
    @JsonIgnore
    public Optional<String> name() {
        return name;
    }

    /**
     * The output from the MCP server call. Can be simple text or rich content.
     */
    @JsonIgnore
    public MCPServerToolResultStepResultUnion result() {
        return result;
    }

    /**
     * The name of the used MCP server.
     */
    @JsonIgnore
    public Optional<String> serverName() {
        return serverName;
    }

    @JsonIgnore
    public String type() {
        return type;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Required. ID to match the ID from the function call block.
     */
    public MCPServerToolResultStep withCallId(String callId) {
        Utils.checkNotNull(callId, "callId");
        this.callId = callId;
        return this;
    }

    /**
     * Name of the tool which is called for this specific tool call.
     */
    public MCPServerToolResultStep withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = Optional.ofNullable(name);
        return this;
    }


    /**
     * Name of the tool which is called for this specific tool call.
     */
    public MCPServerToolResultStep withName(Optional<String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * The output from the MCP server call. Can be simple text or rich content.
     */
    public MCPServerToolResultStep withResult(MCPServerToolResultStepResultUnion result) {
        Utils.checkNotNull(result, "result");
        this.result = result;
        return this;
    }

    /**
     * The name of the used MCP server.
     */
    public MCPServerToolResultStep withServerName(String serverName) {
        Utils.checkNotNull(serverName, "serverName");
        this.serverName = Optional.ofNullable(serverName);
        return this;
    }


    /**
     * The name of the used MCP server.
     */
    public MCPServerToolResultStep withServerName(Optional<String> serverName) {
        Utils.checkNotNull(serverName, "serverName");
        this.serverName = serverName;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MCPServerToolResultStep other = (MCPServerToolResultStep) o;
        return 
            Utils.enhancedDeepEquals(this.callId, other.callId) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.result, other.result) &&
            Utils.enhancedDeepEquals(this.serverName, other.serverName) &&
            Utils.enhancedDeepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            callId, name, result,
            serverName, type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(MCPServerToolResultStep.class,
                "callId", callId,
                "name", name,
                "result", result,
                "serverName", serverName,
                "type", type);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String callId;

        private Optional<String> name = Optional.empty();

        private MCPServerToolResultStepResultUnion result;

        private Optional<String> serverName = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Required. ID to match the ID from the function call block.
         */
        public Builder callId(String callId) {
            Utils.checkNotNull(callId, "callId");
            this.callId = callId;
            return this;
        }


        /**
         * Name of the tool which is called for this specific tool call.
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * Name of the tool which is called for this specific tool call.
         */
        public Builder name(Optional<String> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }


        /**
         * The output from the MCP server call. Can be simple text or rich content.
         */
        public Builder result(MCPServerToolResultStepResultUnion result) {
            Utils.checkNotNull(result, "result");
            this.result = result;
            return this;
        }


        /**
         * The name of the used MCP server.
         */
        public Builder serverName(String serverName) {
            Utils.checkNotNull(serverName, "serverName");
            this.serverName = Optional.ofNullable(serverName);
            return this;
        }

        /**
         * The name of the used MCP server.
         */
        public Builder serverName(Optional<String> serverName) {
            Utils.checkNotNull(serverName, "serverName");
            this.serverName = serverName;
            return this;
        }

        public MCPServerToolResultStep build() {

            return new MCPServerToolResultStep(
                callId, name, result,
                serverName);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_Type =
                new LazySingletonValue<>(
                        "type",
                        "\"mcp_server_tool_result\"",
                        new TypeReference<String>() {});
    }
}
