/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.google.genai.gaos.utils.LazySingletonValue;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nonnull;
import java.util.Map;
import java.util.Optional;

public class MCPServerToolCallDelta implements StepDeltaData {

  @JsonProperty("arguments")
  private Map<String, Object> arguments;

  @JsonProperty("name")
  private String name;

  @JsonProperty("server_name")
  private String serverName;

  @JsonProperty("type")
  private String type;

  @JsonCreator
  public MCPServerToolCallDelta(
      @JsonProperty("arguments") @Nonnull Map<String, Object> arguments,
      @JsonProperty("name") @Nonnull String name,
      @JsonProperty("server_name") @Nonnull String serverName) {
    arguments = Utils.emptyMapIfNull(arguments);
    this.arguments =
        Optional.ofNullable(arguments)
            .orElseThrow(() -> new IllegalArgumentException("arguments cannot be null"));
    this.name =
        Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
    this.serverName =
        Optional.ofNullable(serverName)
            .orElseThrow(() -> new IllegalArgumentException("serverName cannot be null"));
    this.type = Builder._SINGLETON_VALUE_Type.value();
  }

  public Optional<Map<String, Object>> arguments() {
    return Optional.ofNullable(this.arguments);
  }

  public Optional<String> name() {
    return Optional.ofNullable(this.name);
  }

  public Optional<String> serverName() {
    return Optional.ofNullable(this.serverName);
  }

  @Override
  public String type() {
    return Utils.discriminatorToString(type);
  }

  public static Builder builder() {
    return new Builder();
  }

  public MCPServerToolCallDelta withArguments(@Nonnull Map<String, Object> arguments) {
    this.arguments = Utils.checkNotNull(arguments, "arguments");
    return this;
  }

  public MCPServerToolCallDelta withName(@Nonnull String name) {
    this.name = Utils.checkNotNull(name, "name");
    return this;
  }

  public MCPServerToolCallDelta withServerName(@Nonnull String serverName) {
    this.serverName = Utils.checkNotNull(serverName, "serverName");
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MCPServerToolCallDelta other = (MCPServerToolCallDelta) o;
    return Utils.enhancedDeepEquals(this.arguments, other.arguments)
        && Utils.enhancedDeepEquals(this.name, other.name)
        && Utils.enhancedDeepEquals(this.serverName, other.serverName)
        && Utils.enhancedDeepEquals(this.type, other.type);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(arguments, name, serverName, type);
  }

  @Override
  public String toString() {
    return Utils.toString(
        MCPServerToolCallDelta.class,
        "arguments",
        arguments,
        "name",
        name,
        "serverName",
        serverName,
        "type",
        type);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private Map<String, Object> arguments;

    private String name;

    private String serverName;

    private Builder() {
      // force use of static builder() method
    }

    public Builder arguments(@Nonnull Map<String, Object> arguments) {
      this.arguments = Utils.checkNotNull(arguments, "arguments");
      return this;
    }

    public Builder name(@Nonnull String name) {
      this.name = Utils.checkNotNull(name, "name");
      return this;
    }

    public Builder serverName(@Nonnull String serverName) {
      this.serverName = Utils.checkNotNull(serverName, "serverName");
      return this;
    }

    public MCPServerToolCallDelta build() {
      return new MCPServerToolCallDelta(arguments, name, serverName);
    }

    private static final LazySingletonValue<String> _SINGLETON_VALUE_Type =
        new LazySingletonValue<>(
            "type", "\"mcp_server_tool_call\"", new TypeReference<String>() {});
  }
}
