/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * ModalityTokens
 * 
 * <p>The token count for a single response modality.
 */
public class ModalityTokens {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("modality")
    private ResponseModality modality;

    /**
     * Number of tokens for the modality.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tokens")
    private Integer tokens;

    @JsonCreator
    public ModalityTokens(
            @JsonProperty("modality") @Nullable ResponseModality modality,
            @JsonProperty("tokens") @Nullable Integer tokens) {
        this.modality = modality;
        this.tokens = tokens;
    }
    
    public ModalityTokens() {
        this(null, null);
    }

    public Optional<ResponseModality> modality() {
        return Optional.ofNullable(this.modality);
    }

    /**
     * Number of tokens for the modality.
     */
    public Optional<Integer> tokens() {
        return Optional.ofNullable(this.tokens);
    }

    public static Builder builder() {
        return new Builder();
    }


    public ModalityTokens withModality(@Nullable ResponseModality modality) {
        this.modality = modality;
        return this;
    }


    /**
     * Number of tokens for the modality.
     */
    public ModalityTokens withTokens(@Nullable Integer tokens) {
        this.tokens = tokens;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ModalityTokens other = (ModalityTokens) o;
        return 
            Utils.enhancedDeepEquals(this.modality, other.modality) &&
            Utils.enhancedDeepEquals(this.tokens, other.tokens);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            modality, tokens);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ModalityTokens.class,
                "modality", modality,
                "tokens", tokens);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private ResponseModality modality;

        private Integer tokens;

        private Builder() {
          // force use of static builder() method
        }

        public Builder modality(@Nullable ResponseModality modality) {
            this.modality = modality;
            return this;
        }

        /**
         * Number of tokens for the modality.
         */
        public Builder tokens(@Nullable Integer tokens) {
            this.tokens = tokens;
            return this;
        }

        public ModalityTokens build() {
            return new ModalityTokens(
                modality, tokens);
        }

    }
}
