/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * Mode
 * 
 * <p>The mode of the find session.
 */
public class Mode {

    public static final Mode SCAN = new Mode("scan");
    public static final Mode VERIFY = new Mode("verify");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, Mode> values = createValuesMap();
    private static final Map<String, ModeEnum> enums = createEnumsMap();

    private final String value;

    private Mode(String value) {
        this.value = value;
    }

    /**
     * Returns a Mode with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as Mode
     */ 
    @JsonCreator
    public static Mode of(String value) {
        synchronized (Mode.class) {
            return values.computeIfAbsent(value, v -> new Mode(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<ModeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Mode other = (Mode) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "Mode [value=" + value + "]";
    }

    // return an array just like an enum
    public static Mode[] values() {
        synchronized (Mode.class) {
            return values.values().toArray(new Mode[] {});
        }
    }

    private static final Map<String, Mode> createValuesMap() {
        Map<String, Mode> map = new LinkedHashMap<>();
        map.put("scan", SCAN);
        map.put("verify", VERIFY);
        return map;
    }

    private static final Map<String, ModeEnum> createEnumsMap() {
        Map<String, ModeEnum> map = new HashMap<>();
        map.put("scan", ModeEnum.SCAN);
        map.put("verify", ModeEnum.VERIFY);
        return map;
    }
    
    
    public enum ModeEnum {

        SCAN("scan"),
        VERIFY("verify"),;

        private final String value;

        private ModeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

