/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.google.genai.gaos.utils.OneOfDeserializer;
import com.google.genai.gaos.utils.TypedObject;
import com.google.genai.gaos.utils.Utils;
import com.google.genai.gaos.utils.Utils.JsonShape;
import com.google.genai.gaos.utils.Utils.TypeReferenceWithShape;
import java.util.Optional;

/**
 * Network
 *
 * <p>Network configuration for the environment.
 */
@JsonDeserialize(using = Network._Deserializer.class)
public class Network {

  @JsonValue private final TypedObject value;

  private Network(TypedObject value) {
    this.value = value;
  }

  public static Network of(EnvironmentNetworkEgressAllowlist value) {
    Utils.checkNotNull(value, "value");
    return new Network(
        TypedObject.of(
            value, JsonShape.DEFAULT, new TypeReference<EnvironmentNetworkEgressAllowlist>() {}));
  }

  public static Network of(NetworkEnum value) {
    Utils.checkNotNull(value, "value");
    return new Network(
        TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<NetworkEnum>() {}));
  }

  /**
   * Returns an {@link Optional} containing the value if it is of type {@code
   * EnvironmentNetworkEgressAllowlist}, otherwise returns an empty {@link Optional}.
   *
   * @return an {@link Optional} containing the {@code EnvironmentNetworkEgressAllowlist} value, or
   *     empty if not of this type
   */
  public Optional<EnvironmentNetworkEgressAllowlist> environmentNetworkEgressAllowlist() {
    if (value.value() instanceof EnvironmentNetworkEgressAllowlist) {
      return Optional.of((EnvironmentNetworkEgressAllowlist) value.value());
    }
    return Optional.empty();
  }

  /**
   * Returns an {@link Optional} containing the value if it is of type {@code NetworkEnum},
   * otherwise returns an empty {@link Optional}.
   *
   * @return an {@link Optional} containing the {@code NetworkEnum} value, or empty if not of this
   *     type
   */
  public Optional<NetworkEnum> networkEnum() {
    if (value.value() instanceof NetworkEnum) {
      return Optional.of((NetworkEnum) value.value());
    }
    return Optional.empty();
  }

  /**
   * Returns an {@link Optional} containing the value as a {@code JsonNode}. This accessor returns
   * the raw JSON when the value doesn't match any of the defined union types.
   *
   * @return an {@link Optional} containing the {@code JsonNode} value, or empty if value matched a
   *     known type
   */
  public Optional<JsonNode> asJson() {
    if (value.value() instanceof JsonNode) {
      return Optional.of((JsonNode) value.value());
    }
    return Optional.empty();
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Network other = (Network) o;
    return Utils.enhancedDeepEquals(this.value.value(), other.value.value());
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(value.value());
  }

  @SuppressWarnings("serial")
  public static final class _Deserializer extends OneOfDeserializer<Network> {

    public _Deserializer() {
      super(
          Network.class,
          false,
          TypeReferenceWithShape.of(
              new TypeReference<EnvironmentNetworkEgressAllowlist>() {}, JsonShape.DEFAULT),
          TypeReferenceWithShape.of(new TypeReference<NetworkEnum>() {}, JsonShape.DEFAULT));
    }
  }

  @Override
  public String toString() {
    return Utils.toString(Network.class, "value", value);
  }
}
