/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.google.genai.gaos.utils.LazySingletonValue;
import com.google.genai.gaos.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

/**
 * Retrieval
 * 
 * <p>A tool that can be used by the model to retrieve files.
 */
@SuppressWarnings("all")
public class Retrieval {
    /**
     * Used to specify configuration for ExaAISearch.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("exa_ai_search_config")
    private Optional<? extends ExaAISearchConfig> exaAiSearchConfig;

    /**
     * Used to specify configuration for ParallelAISearch.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("parallel_ai_search_config")
    private Optional<? extends ParallelAISearchConfig> parallelAiSearchConfig;

    /**
     * Use to specify configuration for RAG Store.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("rag_store_config")
    private Optional<? extends RagStoreConfig> ragStoreConfig;

    /**
     * The types of file retrieval to enable.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("retrieval_types")
    private Optional<? extends List<RetrievalRetrievalType>> retrievalTypes;


    @JsonProperty("type")
    private String type;

    /**
     * Used to specify configuration for VertexAISearch.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vertex_ai_search_config")
    private Optional<? extends VertexAISearchConfig> vertexAiSearchConfig;

    @JsonCreator
    public Retrieval(
            @JsonProperty("exa_ai_search_config") Optional<? extends ExaAISearchConfig> exaAiSearchConfig,
            @JsonProperty("parallel_ai_search_config") Optional<? extends ParallelAISearchConfig> parallelAiSearchConfig,
            @JsonProperty("rag_store_config") Optional<? extends RagStoreConfig> ragStoreConfig,
            @JsonProperty("retrieval_types") Optional<? extends List<RetrievalRetrievalType>> retrievalTypes,
            @JsonProperty("vertex_ai_search_config") Optional<? extends VertexAISearchConfig> vertexAiSearchConfig) {
        Utils.checkNotNull(exaAiSearchConfig, "exaAiSearchConfig");
        Utils.checkNotNull(parallelAiSearchConfig, "parallelAiSearchConfig");
        Utils.checkNotNull(ragStoreConfig, "ragStoreConfig");
        Utils.checkNotNull(retrievalTypes, "retrievalTypes");
        Utils.checkNotNull(vertexAiSearchConfig, "vertexAiSearchConfig");
        this.exaAiSearchConfig = exaAiSearchConfig;
        this.parallelAiSearchConfig = parallelAiSearchConfig;
        this.ragStoreConfig = ragStoreConfig;
        this.retrievalTypes = retrievalTypes;
        this.type = Builder._SINGLETON_VALUE_Type.value();
        this.vertexAiSearchConfig = vertexAiSearchConfig;
    }
    
    public Retrieval() {
        this(Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    /**
     * Used to specify configuration for ExaAISearch.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ExaAISearchConfig> exaAiSearchConfig() {
        return (Optional<ExaAISearchConfig>) exaAiSearchConfig;
    }

    /**
     * Used to specify configuration for ParallelAISearch.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ParallelAISearchConfig> parallelAiSearchConfig() {
        return (Optional<ParallelAISearchConfig>) parallelAiSearchConfig;
    }

    /**
     * Use to specify configuration for RAG Store.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<RagStoreConfig> ragStoreConfig() {
        return (Optional<RagStoreConfig>) ragStoreConfig;
    }

    /**
     * The types of file retrieval to enable.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<RetrievalRetrievalType>> retrievalTypes() {
        return (Optional<List<RetrievalRetrievalType>>) retrievalTypes;
    }

    @JsonIgnore
    public String type() {
        return type;
    }

    /**
     * Used to specify configuration for VertexAISearch.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<VertexAISearchConfig> vertexAiSearchConfig() {
        return (Optional<VertexAISearchConfig>) vertexAiSearchConfig;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Used to specify configuration for ExaAISearch.
     */
    public Retrieval withExaAiSearchConfig(ExaAISearchConfig exaAiSearchConfig) {
        Utils.checkNotNull(exaAiSearchConfig, "exaAiSearchConfig");
        this.exaAiSearchConfig = Optional.ofNullable(exaAiSearchConfig);
        return this;
    }


    /**
     * Used to specify configuration for ExaAISearch.
     */
    public Retrieval withExaAiSearchConfig(Optional<? extends ExaAISearchConfig> exaAiSearchConfig) {
        Utils.checkNotNull(exaAiSearchConfig, "exaAiSearchConfig");
        this.exaAiSearchConfig = exaAiSearchConfig;
        return this;
    }

    /**
     * Used to specify configuration for ParallelAISearch.
     */
    public Retrieval withParallelAiSearchConfig(ParallelAISearchConfig parallelAiSearchConfig) {
        Utils.checkNotNull(parallelAiSearchConfig, "parallelAiSearchConfig");
        this.parallelAiSearchConfig = Optional.ofNullable(parallelAiSearchConfig);
        return this;
    }


    /**
     * Used to specify configuration for ParallelAISearch.
     */
    public Retrieval withParallelAiSearchConfig(Optional<? extends ParallelAISearchConfig> parallelAiSearchConfig) {
        Utils.checkNotNull(parallelAiSearchConfig, "parallelAiSearchConfig");
        this.parallelAiSearchConfig = parallelAiSearchConfig;
        return this;
    }

    /**
     * Use to specify configuration for RAG Store.
     */
    public Retrieval withRagStoreConfig(RagStoreConfig ragStoreConfig) {
        Utils.checkNotNull(ragStoreConfig, "ragStoreConfig");
        this.ragStoreConfig = Optional.ofNullable(ragStoreConfig);
        return this;
    }


    /**
     * Use to specify configuration for RAG Store.
     */
    public Retrieval withRagStoreConfig(Optional<? extends RagStoreConfig> ragStoreConfig) {
        Utils.checkNotNull(ragStoreConfig, "ragStoreConfig");
        this.ragStoreConfig = ragStoreConfig;
        return this;
    }

    /**
     * The types of file retrieval to enable.
     */
    public Retrieval withRetrievalTypes(List<RetrievalRetrievalType> retrievalTypes) {
        Utils.checkNotNull(retrievalTypes, "retrievalTypes");
        this.retrievalTypes = Optional.ofNullable(retrievalTypes);
        return this;
    }


    /**
     * The types of file retrieval to enable.
     */
    public Retrieval withRetrievalTypes(Optional<? extends List<RetrievalRetrievalType>> retrievalTypes) {
        Utils.checkNotNull(retrievalTypes, "retrievalTypes");
        this.retrievalTypes = retrievalTypes;
        return this;
    }

    /**
     * Used to specify configuration for VertexAISearch.
     */
    public Retrieval withVertexAiSearchConfig(VertexAISearchConfig vertexAiSearchConfig) {
        Utils.checkNotNull(vertexAiSearchConfig, "vertexAiSearchConfig");
        this.vertexAiSearchConfig = Optional.ofNullable(vertexAiSearchConfig);
        return this;
    }


    /**
     * Used to specify configuration for VertexAISearch.
     */
    public Retrieval withVertexAiSearchConfig(Optional<? extends VertexAISearchConfig> vertexAiSearchConfig) {
        Utils.checkNotNull(vertexAiSearchConfig, "vertexAiSearchConfig");
        this.vertexAiSearchConfig = vertexAiSearchConfig;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Retrieval other = (Retrieval) o;
        return 
            Utils.enhancedDeepEquals(this.exaAiSearchConfig, other.exaAiSearchConfig) &&
            Utils.enhancedDeepEquals(this.parallelAiSearchConfig, other.parallelAiSearchConfig) &&
            Utils.enhancedDeepEquals(this.ragStoreConfig, other.ragStoreConfig) &&
            Utils.enhancedDeepEquals(this.retrievalTypes, other.retrievalTypes) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.vertexAiSearchConfig, other.vertexAiSearchConfig);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            exaAiSearchConfig, parallelAiSearchConfig, ragStoreConfig,
            retrievalTypes, type, vertexAiSearchConfig);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Retrieval.class,
                "exaAiSearchConfig", exaAiSearchConfig,
                "parallelAiSearchConfig", parallelAiSearchConfig,
                "ragStoreConfig", ragStoreConfig,
                "retrievalTypes", retrievalTypes,
                "type", type,
                "vertexAiSearchConfig", vertexAiSearchConfig);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends ExaAISearchConfig> exaAiSearchConfig = Optional.empty();

        private Optional<? extends ParallelAISearchConfig> parallelAiSearchConfig = Optional.empty();

        private Optional<? extends RagStoreConfig> ragStoreConfig = Optional.empty();

        private Optional<? extends List<RetrievalRetrievalType>> retrievalTypes = Optional.empty();

        private Optional<? extends VertexAISearchConfig> vertexAiSearchConfig = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Used to specify configuration for ExaAISearch.
         */
        public Builder exaAiSearchConfig(ExaAISearchConfig exaAiSearchConfig) {
            Utils.checkNotNull(exaAiSearchConfig, "exaAiSearchConfig");
            this.exaAiSearchConfig = Optional.ofNullable(exaAiSearchConfig);
            return this;
        }

        /**
         * Used to specify configuration for ExaAISearch.
         */
        public Builder exaAiSearchConfig(Optional<? extends ExaAISearchConfig> exaAiSearchConfig) {
            Utils.checkNotNull(exaAiSearchConfig, "exaAiSearchConfig");
            this.exaAiSearchConfig = exaAiSearchConfig;
            return this;
        }


        /**
         * Used to specify configuration for ParallelAISearch.
         */
        public Builder parallelAiSearchConfig(ParallelAISearchConfig parallelAiSearchConfig) {
            Utils.checkNotNull(parallelAiSearchConfig, "parallelAiSearchConfig");
            this.parallelAiSearchConfig = Optional.ofNullable(parallelAiSearchConfig);
            return this;
        }

        /**
         * Used to specify configuration for ParallelAISearch.
         */
        public Builder parallelAiSearchConfig(Optional<? extends ParallelAISearchConfig> parallelAiSearchConfig) {
            Utils.checkNotNull(parallelAiSearchConfig, "parallelAiSearchConfig");
            this.parallelAiSearchConfig = parallelAiSearchConfig;
            return this;
        }


        /**
         * Use to specify configuration for RAG Store.
         */
        public Builder ragStoreConfig(RagStoreConfig ragStoreConfig) {
            Utils.checkNotNull(ragStoreConfig, "ragStoreConfig");
            this.ragStoreConfig = Optional.ofNullable(ragStoreConfig);
            return this;
        }

        /**
         * Use to specify configuration for RAG Store.
         */
        public Builder ragStoreConfig(Optional<? extends RagStoreConfig> ragStoreConfig) {
            Utils.checkNotNull(ragStoreConfig, "ragStoreConfig");
            this.ragStoreConfig = ragStoreConfig;
            return this;
        }


        /**
         * The types of file retrieval to enable.
         */
        public Builder retrievalTypes(List<RetrievalRetrievalType> retrievalTypes) {
            Utils.checkNotNull(retrievalTypes, "retrievalTypes");
            this.retrievalTypes = Optional.ofNullable(retrievalTypes);
            return this;
        }

        /**
         * The types of file retrieval to enable.
         */
        public Builder retrievalTypes(Optional<? extends List<RetrievalRetrievalType>> retrievalTypes) {
            Utils.checkNotNull(retrievalTypes, "retrievalTypes");
            this.retrievalTypes = retrievalTypes;
            return this;
        }


        /**
         * Used to specify configuration for VertexAISearch.
         */
        public Builder vertexAiSearchConfig(VertexAISearchConfig vertexAiSearchConfig) {
            Utils.checkNotNull(vertexAiSearchConfig, "vertexAiSearchConfig");
            this.vertexAiSearchConfig = Optional.ofNullable(vertexAiSearchConfig);
            return this;
        }

        /**
         * Used to specify configuration for VertexAISearch.
         */
        public Builder vertexAiSearchConfig(Optional<? extends VertexAISearchConfig> vertexAiSearchConfig) {
            Utils.checkNotNull(vertexAiSearchConfig, "vertexAiSearchConfig");
            this.vertexAiSearchConfig = vertexAiSearchConfig;
            return this;
        }

        public Retrieval build() {

            return new Retrieval(
                exaAiSearchConfig, parallelAiSearchConfig, ragStoreConfig,
                retrievalTypes, vertexAiSearchConfig);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_Type =
                new LazySingletonValue<>(
                        "type",
                        "\"retrieval\"",
                        new TypeReference<String>() {});
    }
}
