/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * SpeechConfig
 * 
 * <p>The configuration for speech interaction.
 */
public class SpeechConfig {
    /**
     * The language of the speech.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("language")
    private String language;

    /**
     * The speaker's name, it should match the speaker name given in the prompt.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("speaker")
    private String speaker;

    /**
     * The voice of the speaker.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("voice")
    private String voice;

    @JsonCreator
    public SpeechConfig(
            @JsonProperty("language") @Nullable String language,
            @JsonProperty("speaker") @Nullable String speaker,
            @JsonProperty("voice") @Nullable String voice) {
        this.language = language;
        this.speaker = speaker;
        this.voice = voice;
    }
    
    public SpeechConfig() {
        this(null, null, null);
    }

    /**
     * The language of the speech.
     */
    public Optional<String> language() {
        return Optional.ofNullable(this.language);
    }

    /**
     * The speaker's name, it should match the speaker name given in the prompt.
     */
    public Optional<String> speaker() {
        return Optional.ofNullable(this.speaker);
    }

    /**
     * The voice of the speaker.
     */
    public Optional<String> voice() {
        return Optional.ofNullable(this.voice);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The language of the speech.
     */
    public SpeechConfig withLanguage(@Nullable String language) {
        this.language = language;
        return this;
    }


    /**
     * The speaker's name, it should match the speaker name given in the prompt.
     */
    public SpeechConfig withSpeaker(@Nullable String speaker) {
        this.speaker = speaker;
        return this;
    }


    /**
     * The voice of the speaker.
     */
    public SpeechConfig withVoice(@Nullable String voice) {
        this.voice = voice;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SpeechConfig other = (SpeechConfig) o;
        return 
            Utils.enhancedDeepEquals(this.language, other.language) &&
            Utils.enhancedDeepEquals(this.speaker, other.speaker) &&
            Utils.enhancedDeepEquals(this.voice, other.voice);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            language, speaker, voice);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SpeechConfig.class,
                "language", language,
                "speaker", speaker,
                "voice", voice);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String language;

        private String speaker;

        private String voice;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The language of the speech.
         */
        public Builder language(@Nullable String language) {
            this.language = language;
            return this;
        }

        /**
         * The speaker's name, it should match the speaker name given in the prompt.
         */
        public Builder speaker(@Nullable String speaker) {
            this.speaker = speaker;
            return this;
        }

        /**
         * The voice of the speaker.
         */
        public Builder voice(@Nullable String voice) {
            this.voice = voice;
            return this;
        }

        public SpeechConfig build() {
            return new SpeechConfig(
                language, speaker, voice);
        }

    }
}
