/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * SpeechConfig
 * 
 * <p>The configuration for speech interaction.
 */
@SuppressWarnings("all")
public class SpeechConfig {
    /**
     * The voice of the speaker.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("voice")
    private Optional<String> voice;

    /**
     * The language of the speech.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("language")
    private Optional<String> language;

    /**
     * The speaker's name, it should match the speaker name given in the prompt.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("speaker")
    private Optional<String> speaker;

    @JsonCreator
    public SpeechConfig(
            @JsonProperty("voice") Optional<String> voice,
            @JsonProperty("language") Optional<String> language,
            @JsonProperty("speaker") Optional<String> speaker) {
        Utils.checkNotNull(voice, "voice");
        Utils.checkNotNull(language, "language");
        Utils.checkNotNull(speaker, "speaker");
        this.voice = voice;
        this.language = language;
        this.speaker = speaker;
    }
    
    public SpeechConfig() {
        this(Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * The voice of the speaker.
     */
    @JsonIgnore
    public Optional<String> voice() {
        return voice;
    }

    /**
     * The language of the speech.
     */
    @JsonIgnore
    public Optional<String> language() {
        return language;
    }

    /**
     * The speaker's name, it should match the speaker name given in the prompt.
     */
    @JsonIgnore
    public Optional<String> speaker() {
        return speaker;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The voice of the speaker.
     */
    public SpeechConfig withVoice(String voice) {
        Utils.checkNotNull(voice, "voice");
        this.voice = Optional.ofNullable(voice);
        return this;
    }


    /**
     * The voice of the speaker.
     */
    public SpeechConfig withVoice(Optional<String> voice) {
        Utils.checkNotNull(voice, "voice");
        this.voice = voice;
        return this;
    }

    /**
     * The language of the speech.
     */
    public SpeechConfig withLanguage(String language) {
        Utils.checkNotNull(language, "language");
        this.language = Optional.ofNullable(language);
        return this;
    }


    /**
     * The language of the speech.
     */
    public SpeechConfig withLanguage(Optional<String> language) {
        Utils.checkNotNull(language, "language");
        this.language = language;
        return this;
    }

    /**
     * The speaker's name, it should match the speaker name given in the prompt.
     */
    public SpeechConfig withSpeaker(String speaker) {
        Utils.checkNotNull(speaker, "speaker");
        this.speaker = Optional.ofNullable(speaker);
        return this;
    }


    /**
     * The speaker's name, it should match the speaker name given in the prompt.
     */
    public SpeechConfig withSpeaker(Optional<String> speaker) {
        Utils.checkNotNull(speaker, "speaker");
        this.speaker = speaker;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SpeechConfig other = (SpeechConfig) o;
        return 
            Utils.enhancedDeepEquals(this.voice, other.voice) &&
            Utils.enhancedDeepEquals(this.language, other.language) &&
            Utils.enhancedDeepEquals(this.speaker, other.speaker);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            voice, language, speaker);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SpeechConfig.class,
                "voice", voice,
                "language", language,
                "speaker", speaker);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> voice = Optional.empty();

        private Optional<String> language = Optional.empty();

        private Optional<String> speaker = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The voice of the speaker.
         */
        public Builder voice(String voice) {
            Utils.checkNotNull(voice, "voice");
            this.voice = Optional.ofNullable(voice);
            return this;
        }

        /**
         * The voice of the speaker.
         */
        public Builder voice(Optional<String> voice) {
            Utils.checkNotNull(voice, "voice");
            this.voice = voice;
            return this;
        }


        /**
         * The language of the speech.
         */
        public Builder language(String language) {
            Utils.checkNotNull(language, "language");
            this.language = Optional.ofNullable(language);
            return this;
        }

        /**
         * The language of the speech.
         */
        public Builder language(Optional<String> language) {
            Utils.checkNotNull(language, "language");
            this.language = language;
            return this;
        }


        /**
         * The speaker's name, it should match the speaker name given in the prompt.
         */
        public Builder speaker(String speaker) {
            Utils.checkNotNull(speaker, "speaker");
            this.speaker = Optional.ofNullable(speaker);
            return this;
        }

        /**
         * The speaker's name, it should match the speaker name given in the prompt.
         */
        public Builder speaker(Optional<String> speaker) {
            Utils.checkNotNull(speaker, "speaker");
            this.speaker = speaker;
            return this;
        }

        public SpeechConfig build() {

            return new SpeechConfig(
                voice, language, speaker);
        }

    }
}
