/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.google.genai.gaos.utils.LazySingletonValue;
import com.google.genai.gaos.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


@SuppressWarnings("all")
public class StepStart {

    @JsonProperty("event_type")
    private String eventType;


    @JsonProperty("index")
    private int index;

    /**
     * A step in the interaction.
     */
    @JsonProperty("step")
    private Step step;

    /**
     * The event_id token to be used to resume the interaction stream, from
     * this event.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("event_id")
    private Optional<String> eventId;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metadata")
    private Optional<? extends StreamMetadata> metadata;

    @JsonCreator
    public StepStart(
            @JsonProperty("index") int index,
            @JsonProperty("step") Step step,
            @JsonProperty("event_id") Optional<String> eventId,
            @JsonProperty("metadata") Optional<? extends StreamMetadata> metadata) {
        Utils.checkNotNull(index, "index");
        Utils.checkNotNull(step, "step");
        Utils.checkNotNull(eventId, "eventId");
        Utils.checkNotNull(metadata, "metadata");
        this.eventType = Builder._SINGLETON_VALUE_EventType.value();
        this.index = index;
        this.step = step;
        this.eventId = eventId;
        this.metadata = metadata;
    }
    
    public StepStart(
            int index,
            Step step) {
        this(index, step, Optional.empty(),
            Optional.empty());
    }

    @JsonIgnore
    public String eventType() {
        return eventType;
    }

    @JsonIgnore
    public int index() {
        return index;
    }

    /**
     * A step in the interaction.
     */
    @JsonIgnore
    public Step step() {
        return step;
    }

    /**
     * The event_id token to be used to resume the interaction stream, from
     * this event.
     */
    @JsonIgnore
    public Optional<String> eventId() {
        return eventId;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<StreamMetadata> metadata() {
        return (Optional<StreamMetadata>) metadata;
    }

    public static Builder builder() {
        return new Builder();
    }


    public StepStart withIndex(int index) {
        Utils.checkNotNull(index, "index");
        this.index = index;
        return this;
    }

    /**
     * A step in the interaction.
     */
    public StepStart withStep(Step step) {
        Utils.checkNotNull(step, "step");
        this.step = step;
        return this;
    }

    /**
     * The event_id token to be used to resume the interaction stream, from
     * this event.
     */
    public StepStart withEventId(String eventId) {
        Utils.checkNotNull(eventId, "eventId");
        this.eventId = Optional.ofNullable(eventId);
        return this;
    }


    /**
     * The event_id token to be used to resume the interaction stream, from
     * this event.
     */
    public StepStart withEventId(Optional<String> eventId) {
        Utils.checkNotNull(eventId, "eventId");
        this.eventId = eventId;
        return this;
    }

    public StepStart withMetadata(StreamMetadata metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = Optional.ofNullable(metadata);
        return this;
    }


    public StepStart withMetadata(Optional<? extends StreamMetadata> metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = metadata;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StepStart other = (StepStart) o;
        return 
            Utils.enhancedDeepEquals(this.eventType, other.eventType) &&
            Utils.enhancedDeepEquals(this.index, other.index) &&
            Utils.enhancedDeepEquals(this.step, other.step) &&
            Utils.enhancedDeepEquals(this.eventId, other.eventId) &&
            Utils.enhancedDeepEquals(this.metadata, other.metadata);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            eventType, index, step,
            eventId, metadata);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StepStart.class,
                "eventType", eventType,
                "index", index,
                "step", step,
                "eventId", eventId,
                "metadata", metadata);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Integer index;

        private Step step;

        private Optional<String> eventId = Optional.empty();

        private Optional<? extends StreamMetadata> metadata = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder index(int index) {
            Utils.checkNotNull(index, "index");
            this.index = index;
            return this;
        }


        /**
         * A step in the interaction.
         */
        public Builder step(Step step) {
            Utils.checkNotNull(step, "step");
            this.step = step;
            return this;
        }


        /**
         * The event_id token to be used to resume the interaction stream, from
         * this event.
         */
        public Builder eventId(String eventId) {
            Utils.checkNotNull(eventId, "eventId");
            this.eventId = Optional.ofNullable(eventId);
            return this;
        }

        /**
         * The event_id token to be used to resume the interaction stream, from
         * this event.
         */
        public Builder eventId(Optional<String> eventId) {
            Utils.checkNotNull(eventId, "eventId");
            this.eventId = eventId;
            return this;
        }


        public Builder metadata(StreamMetadata metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        public Builder metadata(Optional<? extends StreamMetadata> metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = metadata;
            return this;
        }

        public StepStart build() {

            return new StepStart(
                index, step, eventId,
                metadata);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_EventType =
                new LazySingletonValue<>(
                        "event_type",
                        "\"step.start\"",
                        new TypeReference<String>() {});
    }
}
