/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.google.genai.gaos.utils.GenericTypeIdResolver;
import java.lang.IllegalArgumentException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;

public class StepDeltaDataTypeIdResolver extends GenericTypeIdResolver<StepDeltaData> {

    public StepDeltaDataTypeIdResolver() {
        super(UnknownStepDeltaData.class);
        initializeTypeMap();
    }

    private void initializeTypeMap() {
        registerType("arguments_delta", ArgumentsDelta.class);
        registerType("audio", AudioDelta.class);
        registerType("code_execution_call", CodeExecutionCallDelta.class);
        registerType("code_execution_result", CodeExecutionResultDelta.class);
        registerType("document", DocumentDelta.class);
        registerType("file_search_call", FileSearchCallDelta.class);
        registerType("file_search_result", FileSearchResultDelta.class);
        registerType("function_result", FunctionResultDelta.class);
        registerType("google_maps_call", GoogleMapsCallDelta.class);
        registerType("google_maps_result", GoogleMapsResultDelta.class);
        registerType("google_search_call", GoogleSearchCallDelta.class);
        registerType("google_search_result", GoogleSearchResultDelta.class);
        registerType("image", ImageDelta.class);
        registerType("mcp_server_tool_call", MCPServerToolCallDelta.class);
        registerType("mcp_server_tool_result", MCPServerToolResultDelta.class);
        registerType("retrieval_call", RetrievalCallDelta.class);
        registerType("retrieval_result", RetrievalResultDelta.class);
        registerType("text_annotation_delta", TextAnnotationDelta.class);
        registerType("text", TextDelta.class);
        registerType("thought_signature", ThoughtSignatureDelta.class);
        registerType("thought_summary", ThoughtSummaryDelta.class);
        registerType("url_context_call", URLContextCallDelta.class);
        registerType("url_context_result", URLContextResultDelta.class);
        registerType("video", VideoDelta.class);
    }

    @Override
    public String idFromValue(Object value) {
        if (value == null) {
            return null;
        }

        // Handle known types by checking if they implement the discriminator method
        if (value instanceof StepDeltaData) {
            StepDeltaData discriminated = (StepDeltaData) value;
            return discriminated.type();
        }

        throw new IllegalArgumentException(
                "Unknown value type: " + value.getClass().getName());
    }

    @Override
    public String getDescForKnownTypeIds() {
        return "StepDeltaData type resolver";
    }
}
