/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.google.genai.gaos.utils.LazySingletonValue;
import com.google.genai.gaos.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;


@SuppressWarnings("all")
public class TextAnnotationDelta {

    @JsonProperty("type")
    private String type;

    /**
     * Citation information for model-generated content.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("annotations")
    private Optional<? extends List<Annotation>> annotations;

    @JsonCreator
    public TextAnnotationDelta(
            @JsonProperty("annotations") Optional<? extends List<Annotation>> annotations) {
        Utils.checkNotNull(annotations, "annotations");
        this.type = Builder._SINGLETON_VALUE_Type.value();
        this.annotations = annotations;
    }
    
    public TextAnnotationDelta() {
        this(Optional.empty());
    }

    @JsonIgnore
    public String type() {
        return type;
    }

    /**
     * Citation information for model-generated content.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<Annotation>> annotations() {
        return (Optional<List<Annotation>>) annotations;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Citation information for model-generated content.
     */
    public TextAnnotationDelta withAnnotations(List<Annotation> annotations) {
        Utils.checkNotNull(annotations, "annotations");
        this.annotations = Optional.ofNullable(annotations);
        return this;
    }


    /**
     * Citation information for model-generated content.
     */
    public TextAnnotationDelta withAnnotations(Optional<? extends List<Annotation>> annotations) {
        Utils.checkNotNull(annotations, "annotations");
        this.annotations = annotations;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TextAnnotationDelta other = (TextAnnotationDelta) o;
        return 
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.annotations, other.annotations);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            type, annotations);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TextAnnotationDelta.class,
                "type", type,
                "annotations", annotations);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends List<Annotation>> annotations = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Citation information for model-generated content.
         */
        public Builder annotations(List<Annotation> annotations) {
            Utils.checkNotNull(annotations, "annotations");
            this.annotations = Optional.ofNullable(annotations);
            return this;
        }

        /**
         * Citation information for model-generated content.
         */
        public Builder annotations(Optional<? extends List<Annotation>> annotations) {
            Utils.checkNotNull(annotations, "annotations");
            this.annotations = annotations;
            return this;
        }

        public TextAnnotationDelta build() {

            return new TextAnnotationDelta(
                annotations);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_Type =
                new LazySingletonValue<>(
                        "type",
                        "\"text_annotation_delta\"",
                        new TypeReference<String>() {});
    }
}
