/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.google.genai.gaos.utils.OneOfDeserializer;
import com.google.genai.gaos.utils.TypedObject;
import com.google.genai.gaos.utils.Utils.JsonShape;
import com.google.genai.gaos.utils.Utils.TypeReferenceWithShape;
import com.google.genai.gaos.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Transform
 * 
 * <p>Headers to inject on all outbound requests matching this domain. Accepts a single dict or a list of
 * dicts. The egress proxy injects these automatically.
 */
@JsonDeserialize(using = Transform._Deserializer.class)
public class Transform {

    @JsonValue
    private final TypedObject value;
    
    private Transform(TypedObject value) {
        this.value = value;
    }

    public static Transform of(List<Map<String, String>> value) {
        Utils.checkNotNull(value, "value");
        return new Transform(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<List<Map<String, String>>>(){}));
    }

    public static Transform of(Map<String, String> value) {
        Utils.checkNotNull(value, "value");
        return new Transform(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<Map<String, String>>(){}));
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code List<Map<String, String>>},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code List<Map<String, String>>} value, or empty if not of this type
     */
    @SuppressWarnings("unchecked")
    public Optional<List<Map<String, String>>> arrayOfMap() {
        if (value.value() instanceof List) {
            return Optional.of((List<Map<String, String>>) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code Map<String, String>},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code Map<String, String>} value, or empty if not of this type
     */
    @SuppressWarnings("unchecked")
    public Optional<Map<String, String>> mapOfString() {
        if (value.value() instanceof Map) {
            return Optional.of((Map<String, String>) value.value());
        }
        return Optional.empty();
    }
   /**
    * Returns an {@link Optional} containing the value as a {@code JsonNode}.
    * This accessor returns the raw JSON when the value doesn't match any of the defined union types.
    *
    * @return an {@link Optional} containing the {@code JsonNode} value, or empty if value matched a known type
    */
   public Optional<JsonNode> asJson() {
       if (value.value() instanceof JsonNode) {
           return Optional.of((JsonNode) value.value());
       }
       return Optional.empty();
   }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Transform other = (Transform) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value());
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<Transform> {

        public _Deserializer() {
            super(Transform.class, false,
                  TypeReferenceWithShape.of(new TypeReference<List<Map<String, String>>>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<Map<String, String>>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(Transform.class,
                "value", value);
    }

}

