/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nullable;
import java.util.List;
import java.util.Optional;

/**
 * Usage
 *
 * <p>Statistics on the interaction request's token usage.
 */
public class Usage {
  /** A breakdown of cached token usage by modality. */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("cached_tokens_by_modality")
  private List<ModalityTokens> cachedTokensByModality;

  /** Grounding tool count. */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("grounding_tool_count")
  private List<GroundingToolCount> groundingToolCount;

  /** A breakdown of input token usage by modality. */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("input_tokens_by_modality")
  private List<ModalityTokens> inputTokensByModality;

  /** A breakdown of output token usage by modality. */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("output_tokens_by_modality")
  private List<ModalityTokens> outputTokensByModality;

  /** A breakdown of tool-use token usage by modality. */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("tool_use_tokens_by_modality")
  private List<ModalityTokens> toolUseTokensByModality;

  /** Number of tokens in the cached part of the prompt (the cached content). */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("total_cached_tokens")
  private Integer totalCachedTokens;

  /** Number of tokens in the prompt (context). */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("total_input_tokens")
  private Integer totalInputTokens;

  /** Total number of tokens across all the generated responses. */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("total_output_tokens")
  private Integer totalOutputTokens;

  /** Number of tokens of thoughts for thinking models. */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("total_thought_tokens")
  private Integer totalThoughtTokens;

  /** Total token count for the interaction request (prompt + responses + other internal tokens). */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("total_tokens")
  private Integer totalTokens;

  /** Number of tokens present in tool-use prompt(s). */
  @JsonInclude(Include.NON_ABSENT)
  @JsonProperty("total_tool_use_tokens")
  private Integer totalToolUseTokens;

  @JsonCreator
  public Usage(
      @JsonProperty("cached_tokens_by_modality") @Nullable
          List<ModalityTokens> cachedTokensByModality,
      @JsonProperty("grounding_tool_count") @Nullable List<GroundingToolCount> groundingToolCount,
      @JsonProperty("input_tokens_by_modality") @Nullable
          List<ModalityTokens> inputTokensByModality,
      @JsonProperty("output_tokens_by_modality") @Nullable
          List<ModalityTokens> outputTokensByModality,
      @JsonProperty("tool_use_tokens_by_modality") @Nullable
          List<ModalityTokens> toolUseTokensByModality,
      @JsonProperty("total_cached_tokens") @Nullable Integer totalCachedTokens,
      @JsonProperty("total_input_tokens") @Nullable Integer totalInputTokens,
      @JsonProperty("total_output_tokens") @Nullable Integer totalOutputTokens,
      @JsonProperty("total_thought_tokens") @Nullable Integer totalThoughtTokens,
      @JsonProperty("total_tokens") @Nullable Integer totalTokens,
      @JsonProperty("total_tool_use_tokens") @Nullable Integer totalToolUseTokens) {
    this.cachedTokensByModality = cachedTokensByModality;
    this.groundingToolCount = groundingToolCount;
    this.inputTokensByModality = inputTokensByModality;
    this.outputTokensByModality = outputTokensByModality;
    this.toolUseTokensByModality = toolUseTokensByModality;
    this.totalCachedTokens = totalCachedTokens;
    this.totalInputTokens = totalInputTokens;
    this.totalOutputTokens = totalOutputTokens;
    this.totalThoughtTokens = totalThoughtTokens;
    this.totalTokens = totalTokens;
    this.totalToolUseTokens = totalToolUseTokens;
  }

  public Usage() {
    this(null, null, null, null, null, null, null, null, null, null, null);
  }

  /** A breakdown of cached token usage by modality. */
  public Optional<List<ModalityTokens>> cachedTokensByModality() {
    return Optional.ofNullable(this.cachedTokensByModality);
  }

  /** Grounding tool count. */
  public Optional<List<GroundingToolCount>> groundingToolCount() {
    return Optional.ofNullable(this.groundingToolCount);
  }

  /** A breakdown of input token usage by modality. */
  public Optional<List<ModalityTokens>> inputTokensByModality() {
    return Optional.ofNullable(this.inputTokensByModality);
  }

  /** A breakdown of output token usage by modality. */
  public Optional<List<ModalityTokens>> outputTokensByModality() {
    return Optional.ofNullable(this.outputTokensByModality);
  }

  /** A breakdown of tool-use token usage by modality. */
  public Optional<List<ModalityTokens>> toolUseTokensByModality() {
    return Optional.ofNullable(this.toolUseTokensByModality);
  }

  /** Number of tokens in the cached part of the prompt (the cached content). */
  public Optional<Integer> totalCachedTokens() {
    return Optional.ofNullable(this.totalCachedTokens);
  }

  /** Number of tokens in the prompt (context). */
  public Optional<Integer> totalInputTokens() {
    return Optional.ofNullable(this.totalInputTokens);
  }

  /** Total number of tokens across all the generated responses. */
  public Optional<Integer> totalOutputTokens() {
    return Optional.ofNullable(this.totalOutputTokens);
  }

  /** Number of tokens of thoughts for thinking models. */
  public Optional<Integer> totalThoughtTokens() {
    return Optional.ofNullable(this.totalThoughtTokens);
  }

  /** Total token count for the interaction request (prompt + responses + other internal tokens). */
  public Optional<Integer> totalTokens() {
    return Optional.ofNullable(this.totalTokens);
  }

  /** Number of tokens present in tool-use prompt(s). */
  public Optional<Integer> totalToolUseTokens() {
    return Optional.ofNullable(this.totalToolUseTokens);
  }

  public static Builder builder() {
    return new Builder();
  }

  /** A breakdown of cached token usage by modality. */
  public Usage withCachedTokensByModality(@Nullable List<ModalityTokens> cachedTokensByModality) {
    this.cachedTokensByModality = cachedTokensByModality;
    return this;
  }

  /** Grounding tool count. */
  public Usage withGroundingToolCount(@Nullable List<GroundingToolCount> groundingToolCount) {
    this.groundingToolCount = groundingToolCount;
    return this;
  }

  /** A breakdown of input token usage by modality. */
  public Usage withInputTokensByModality(@Nullable List<ModalityTokens> inputTokensByModality) {
    this.inputTokensByModality = inputTokensByModality;
    return this;
  }

  /** A breakdown of output token usage by modality. */
  public Usage withOutputTokensByModality(@Nullable List<ModalityTokens> outputTokensByModality) {
    this.outputTokensByModality = outputTokensByModality;
    return this;
  }

  /** A breakdown of tool-use token usage by modality. */
  public Usage withToolUseTokensByModality(@Nullable List<ModalityTokens> toolUseTokensByModality) {
    this.toolUseTokensByModality = toolUseTokensByModality;
    return this;
  }

  /** Number of tokens in the cached part of the prompt (the cached content). */
  public Usage withTotalCachedTokens(@Nullable Integer totalCachedTokens) {
    this.totalCachedTokens = totalCachedTokens;
    return this;
  }

  /** Number of tokens in the prompt (context). */
  public Usage withTotalInputTokens(@Nullable Integer totalInputTokens) {
    this.totalInputTokens = totalInputTokens;
    return this;
  }

  /** Total number of tokens across all the generated responses. */
  public Usage withTotalOutputTokens(@Nullable Integer totalOutputTokens) {
    this.totalOutputTokens = totalOutputTokens;
    return this;
  }

  /** Number of tokens of thoughts for thinking models. */
  public Usage withTotalThoughtTokens(@Nullable Integer totalThoughtTokens) {
    this.totalThoughtTokens = totalThoughtTokens;
    return this;
  }

  /** Total token count for the interaction request (prompt + responses + other internal tokens). */
  public Usage withTotalTokens(@Nullable Integer totalTokens) {
    this.totalTokens = totalTokens;
    return this;
  }

  /** Number of tokens present in tool-use prompt(s). */
  public Usage withTotalToolUseTokens(@Nullable Integer totalToolUseTokens) {
    this.totalToolUseTokens = totalToolUseTokens;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Usage other = (Usage) o;
    return Utils.enhancedDeepEquals(this.cachedTokensByModality, other.cachedTokensByModality)
        && Utils.enhancedDeepEquals(this.groundingToolCount, other.groundingToolCount)
        && Utils.enhancedDeepEquals(this.inputTokensByModality, other.inputTokensByModality)
        && Utils.enhancedDeepEquals(this.outputTokensByModality, other.outputTokensByModality)
        && Utils.enhancedDeepEquals(this.toolUseTokensByModality, other.toolUseTokensByModality)
        && Utils.enhancedDeepEquals(this.totalCachedTokens, other.totalCachedTokens)
        && Utils.enhancedDeepEquals(this.totalInputTokens, other.totalInputTokens)
        && Utils.enhancedDeepEquals(this.totalOutputTokens, other.totalOutputTokens)
        && Utils.enhancedDeepEquals(this.totalThoughtTokens, other.totalThoughtTokens)
        && Utils.enhancedDeepEquals(this.totalTokens, other.totalTokens)
        && Utils.enhancedDeepEquals(this.totalToolUseTokens, other.totalToolUseTokens);
  }

  @Override
  public int hashCode() {
    return Utils.enhancedHash(
        cachedTokensByModality,
        groundingToolCount,
        inputTokensByModality,
        outputTokensByModality,
        toolUseTokensByModality,
        totalCachedTokens,
        totalInputTokens,
        totalOutputTokens,
        totalThoughtTokens,
        totalTokens,
        totalToolUseTokens);
  }

  @Override
  public String toString() {
    return Utils.toString(
        Usage.class,
        "cachedTokensByModality",
        cachedTokensByModality,
        "groundingToolCount",
        groundingToolCount,
        "inputTokensByModality",
        inputTokensByModality,
        "outputTokensByModality",
        outputTokensByModality,
        "toolUseTokensByModality",
        toolUseTokensByModality,
        "totalCachedTokens",
        totalCachedTokens,
        "totalInputTokens",
        totalInputTokens,
        "totalOutputTokens",
        totalOutputTokens,
        "totalThoughtTokens",
        totalThoughtTokens,
        "totalTokens",
        totalTokens,
        "totalToolUseTokens",
        totalToolUseTokens);
  }

  @SuppressWarnings("UnusedReturnValue")
  public static final class Builder {

    private List<ModalityTokens> cachedTokensByModality;

    private List<GroundingToolCount> groundingToolCount;

    private List<ModalityTokens> inputTokensByModality;

    private List<ModalityTokens> outputTokensByModality;

    private List<ModalityTokens> toolUseTokensByModality;

    private Integer totalCachedTokens;

    private Integer totalInputTokens;

    private Integer totalOutputTokens;

    private Integer totalThoughtTokens;

    private Integer totalTokens;

    private Integer totalToolUseTokens;

    private Builder() {
      // force use of static builder() method
    }

    /** A breakdown of cached token usage by modality. */
    public Builder cachedTokensByModality(@Nullable List<ModalityTokens> cachedTokensByModality) {
      this.cachedTokensByModality = cachedTokensByModality;
      return this;
    }

    /** Grounding tool count. */
    public Builder groundingToolCount(@Nullable List<GroundingToolCount> groundingToolCount) {
      this.groundingToolCount = groundingToolCount;
      return this;
    }

    /** A breakdown of input token usage by modality. */
    public Builder inputTokensByModality(@Nullable List<ModalityTokens> inputTokensByModality) {
      this.inputTokensByModality = inputTokensByModality;
      return this;
    }

    /** A breakdown of output token usage by modality. */
    public Builder outputTokensByModality(@Nullable List<ModalityTokens> outputTokensByModality) {
      this.outputTokensByModality = outputTokensByModality;
      return this;
    }

    /** A breakdown of tool-use token usage by modality. */
    public Builder toolUseTokensByModality(@Nullable List<ModalityTokens> toolUseTokensByModality) {
      this.toolUseTokensByModality = toolUseTokensByModality;
      return this;
    }

    /** Number of tokens in the cached part of the prompt (the cached content). */
    public Builder totalCachedTokens(@Nullable Integer totalCachedTokens) {
      this.totalCachedTokens = totalCachedTokens;
      return this;
    }

    /** Number of tokens in the prompt (context). */
    public Builder totalInputTokens(@Nullable Integer totalInputTokens) {
      this.totalInputTokens = totalInputTokens;
      return this;
    }

    /** Total number of tokens across all the generated responses. */
    public Builder totalOutputTokens(@Nullable Integer totalOutputTokens) {
      this.totalOutputTokens = totalOutputTokens;
      return this;
    }

    /** Number of tokens of thoughts for thinking models. */
    public Builder totalThoughtTokens(@Nullable Integer totalThoughtTokens) {
      this.totalThoughtTokens = totalThoughtTokens;
      return this;
    }

    /**
     * Total token count for the interaction request (prompt + responses + other internal tokens).
     */
    public Builder totalTokens(@Nullable Integer totalTokens) {
      this.totalTokens = totalTokens;
      return this;
    }

    /** Number of tokens present in tool-use prompt(s). */
    public Builder totalToolUseTokens(@Nullable Integer totalToolUseTokens) {
      this.totalToolUseTokens = totalToolUseTokens;
      return this;
    }

    public Usage build() {
      return new Usage(
          cachedTokensByModality,
          groundingToolCount,
          inputTokensByModality,
          outputTokensByModality,
          toolUseTokensByModality,
          totalCachedTokens,
          totalInputTokens,
          totalOutputTokens,
          totalThoughtTokens,
          totalTokens,
          totalToolUseTokens);
    }
  }
}
