/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

/**
 * VertexAISearchConfig
 * 
 * <p>Used to specify configuration for VertexAISearch.
 */
@SuppressWarnings("all")
public class VertexAISearchConfig {
    /**
     * Optional. Used to specify Vertex AI Search engine.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("engine")
    private Optional<String> engine;

    /**
     * Optional. Used to specify Vertex AI Search datastores.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("datastores")
    private Optional<? extends List<String>> datastores;

    @JsonCreator
    public VertexAISearchConfig(
            @JsonProperty("engine") Optional<String> engine,
            @JsonProperty("datastores") Optional<? extends List<String>> datastores) {
        Utils.checkNotNull(engine, "engine");
        Utils.checkNotNull(datastores, "datastores");
        this.engine = engine;
        this.datastores = datastores;
    }
    
    public VertexAISearchConfig() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * Optional. Used to specify Vertex AI Search engine.
     */
    @JsonIgnore
    public Optional<String> engine() {
        return engine;
    }

    /**
     * Optional. Used to specify Vertex AI Search datastores.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> datastores() {
        return (Optional<List<String>>) datastores;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Optional. Used to specify Vertex AI Search engine.
     */
    public VertexAISearchConfig withEngine(String engine) {
        Utils.checkNotNull(engine, "engine");
        this.engine = Optional.ofNullable(engine);
        return this;
    }


    /**
     * Optional. Used to specify Vertex AI Search engine.
     */
    public VertexAISearchConfig withEngine(Optional<String> engine) {
        Utils.checkNotNull(engine, "engine");
        this.engine = engine;
        return this;
    }

    /**
     * Optional. Used to specify Vertex AI Search datastores.
     */
    public VertexAISearchConfig withDatastores(List<String> datastores) {
        Utils.checkNotNull(datastores, "datastores");
        this.datastores = Optional.ofNullable(datastores);
        return this;
    }


    /**
     * Optional. Used to specify Vertex AI Search datastores.
     */
    public VertexAISearchConfig withDatastores(Optional<? extends List<String>> datastores) {
        Utils.checkNotNull(datastores, "datastores");
        this.datastores = datastores;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VertexAISearchConfig other = (VertexAISearchConfig) o;
        return 
            Utils.enhancedDeepEquals(this.engine, other.engine) &&
            Utils.enhancedDeepEquals(this.datastores, other.datastores);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            engine, datastores);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VertexAISearchConfig.class,
                "engine", engine,
                "datastores", datastores);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> engine = Optional.empty();

        private Optional<? extends List<String>> datastores = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Optional. Used to specify Vertex AI Search engine.
         */
        public Builder engine(String engine) {
            Utils.checkNotNull(engine, "engine");
            this.engine = Optional.ofNullable(engine);
            return this;
        }

        /**
         * Optional. Used to specify Vertex AI Search engine.
         */
        public Builder engine(Optional<String> engine) {
            Utils.checkNotNull(engine, "engine");
            this.engine = engine;
            return this;
        }


        /**
         * Optional. Used to specify Vertex AI Search datastores.
         */
        public Builder datastores(List<String> datastores) {
            Utils.checkNotNull(datastores, "datastores");
            this.datastores = Optional.ofNullable(datastores);
            return this;
        }

        /**
         * Optional. Used to specify Vertex AI Search datastores.
         */
        public Builder datastores(Optional<? extends List<String>> datastores) {
            Utils.checkNotNull(datastores, "datastores");
            this.datastores = datastores;
            return this;
        }

        public VertexAISearchConfig build() {

            return new VertexAISearchConfig(
                engine, datastores);
        }

    }
}
