/*
* Copyright 2026 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

@SuppressWarnings("all")
public enum VideoDeltaMimeType {
    VIDEO_MP4("video/mp4"),
    VIDEO_MPEG("video/mpeg"),
    VIDEO_MPG("video/mpg"),
    VIDEO_MOV("video/mov"),
    VIDEO_AVI("video/avi"),
    VIDEO_X_FLV("video/x-flv"),
    VIDEO_WEBM("video/webm"),
    VIDEO_WMV("video/wmv"),
    VIDEO3GPP("video/3gpp");

    @JsonValue
    private final String value;

    VideoDeltaMimeType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<VideoDeltaMimeType> fromValue(String value) {
        for (VideoDeltaMimeType o: VideoDeltaMimeType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

