/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.interactions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * VideoConfig
 * 
 * <p>Configuration options for video generation.
 */
public class VideoConfig {
    /**
     * Optional task mode for video generation. If not specified, the model
     * automatically determines the appropriate mode based on the provided text
     * prompt and input media.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("task")
    private Task task;

    @JsonCreator
    public VideoConfig(
            @JsonProperty("task") @Nullable Task task) {
        this.task = task;
    }
    
    public VideoConfig() {
        this(null);
    }

    /**
     * Optional task mode for video generation. If not specified, the model
     * automatically determines the appropriate mode based on the provided text
     * prompt and input media.
     */
    public Optional<Task> task() {
        return Optional.ofNullable(this.task);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Optional task mode for video generation. If not specified, the model
     * automatically determines the appropriate mode based on the provided text
     * prompt and input media.
     */
    public VideoConfig withTask(@Nullable Task task) {
        this.task = task;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VideoConfig other = (VideoConfig) o;
        return 
            Utils.enhancedDeepEquals(this.task, other.task);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            task);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VideoConfig.class,
                "task", task);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Task task;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Optional task mode for video generation. If not specified, the model
         * automatically determines the appropriate mode based on the provided text
         * prompt and input media.
         */
        public Builder task(@Nullable Task task) {
            this.task = task;
            return this;
        }

        public VideoConfig build() {
            return new VideoConfig(
                task);
        }

    }
}
