/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

// File generated from our OpenAPI spec by Stainless.

package com.google.genai.interactions.models.interactions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.google.genai.interactions.core.JsonValue
import com.google.genai.interactions.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CreateModelInteractionParamsTest {

    @Test
    fun create() {
        val createModelInteractionParams =
            CreateModelInteractionParams.builder()
                .input(
                    TextContent.builder()
                        .text("text")
                        .addAnnotation(
                            UrlCitation.builder()
                                .endIndex(0)
                                .startIndex(0)
                                .title("title")
                                .url("url")
                                .build()
                        )
                        .build()
                )
                .model(Model.GEMINI_2_5_COMPUTER_USE_PREVIEW_10_2025)
                .id("id")
                .background(true)
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .generationConfig(
                    GenerationConfig.builder()
                        .imageConfig(
                            ImageConfig.builder()
                                .aspectRatio(ImageConfig.AspectRatio._1_1)
                                .imageSize(ImageConfig.ImageSize._1_K)
                                .build()
                        )
                        .maxOutputTokens(0)
                        .seed(0)
                        .addSpeechConfig(
                            SpeechConfig.builder()
                                .language("language")
                                .speaker("speaker")
                                .voice("voice")
                                .build()
                        )
                        .addStopSequence("string")
                        .temperature(0.0f)
                        .thinkingLevel(ThinkingLevel.MINIMAL)
                        .thinkingSummaries(GenerationConfig.ThinkingSummaries.AUTO)
                        .toolChoice(ToolChoiceType.AUTO)
                        .topP(0.0f)
                        .build()
                )
                .previousInteractionId("previous_interaction_id")
                .responseFormatOfList(
                    listOf(
                        CreateModelInteractionParams.ResponseFormat.InnerResponseFormat.ofAudio(
                            AudioResponseFormat.builder()
                                .bitRate(0)
                                .delivery(AudioResponseFormat.Delivery.INLINE)
                                .mimeType(AudioResponseFormat.MimeType.AUDIO_MP3)
                                .sampleRate(0)
                                .build()
                        )
                    )
                )
                .responseMimeType("response_mime_type")
                .addResponseModality(CreateModelInteractionParams.ResponseModality.TEXT)
                .role("role")
                .serviceTier(CreateModelInteractionParams.ServiceTier.FLEX)
                .status(CreateModelInteractionParams.Status.IN_PROGRESS)
                .store(true)
                .stream(true)
                .systemInstruction("system_instruction")
                .addTool(
                    Function.builder()
                        .description("description")
                        .name("name")
                        .parameters(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .updated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .usage(
                    Usage.builder()
                        .addCachedTokensByModality(
                            Usage.CachedTokensByModality.builder()
                                .modality(Usage.CachedTokensByModality.Modality.TEXT)
                                .tokens(0)
                                .build()
                        )
                        .addGroundingToolCount(
                            Usage.GroundingToolCount.builder()
                                .count(0)
                                .type(Usage.GroundingToolCount.Type.GOOGLE_SEARCH)
                                .build()
                        )
                        .addInputTokensByModality(
                            Usage.InputTokensByModality.builder()
                                .modality(Usage.InputTokensByModality.Modality.TEXT)
                                .tokens(0)
                                .build()
                        )
                        .addOutputTokensByModality(
                            Usage.OutputTokensByModality.builder()
                                .modality(Usage.OutputTokensByModality.Modality.TEXT)
                                .tokens(0)
                                .build()
                        )
                        .addToolUseTokensByModality(
                            Usage.ToolUseTokensByModality.builder()
                                .modality(Usage.ToolUseTokensByModality.Modality.TEXT)
                                .tokens(0)
                                .build()
                        )
                        .totalCachedTokens(0)
                        .totalInputTokens(0)
                        .totalOutputTokens(0)
                        .totalThoughtTokens(0)
                        .totalTokens(0)
                        .totalToolUseTokens(0)
                        .build()
                )
                .webhookConfig(
                    CreateModelInteractionParams.WebhookConfig.builder()
                        .addUris("string")
                        .userMetadata(
                            CreateModelInteractionParams.WebhookConfig.UserMetadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(createModelInteractionParams.input())
            .isEqualTo(
                CreateModelInteractionParams.Input.ofTextContent(
                    TextContent.builder()
                        .text("text")
                        .addAnnotation(
                            UrlCitation.builder()
                                .endIndex(0)
                                .startIndex(0)
                                .title("title")
                                .url("url")
                                .build()
                        )
                        .build()
                )
            )
        assertThat(createModelInteractionParams.model())
            .isEqualTo(Model.GEMINI_2_5_COMPUTER_USE_PREVIEW_10_2025)
        assertThat(createModelInteractionParams.id()).contains("id")
        assertThat(createModelInteractionParams.background()).contains(true)
        assertThat(createModelInteractionParams.created())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(createModelInteractionParams.generationConfig())
            .contains(
                GenerationConfig.builder()
                    .imageConfig(
                        ImageConfig.builder()
                            .aspectRatio(ImageConfig.AspectRatio._1_1)
                            .imageSize(ImageConfig.ImageSize._1_K)
                            .build()
                    )
                    .maxOutputTokens(0)
                    .seed(0)
                    .addSpeechConfig(
                        SpeechConfig.builder()
                            .language("language")
                            .speaker("speaker")
                            .voice("voice")
                            .build()
                    )
                    .addStopSequence("string")
                    .temperature(0.0f)
                    .thinkingLevel(ThinkingLevel.MINIMAL)
                    .thinkingSummaries(GenerationConfig.ThinkingSummaries.AUTO)
                    .toolChoice(ToolChoiceType.AUTO)
                    .topP(0.0f)
                    .build()
            )
        assertThat(createModelInteractionParams.previousInteractionId())
            .contains("previous_interaction_id")
        assertThat(createModelInteractionParams.responseFormat())
            .contains(
                CreateModelInteractionParams.ResponseFormat.ofList(
                    listOf(
                        CreateModelInteractionParams.ResponseFormat.InnerResponseFormat.ofAudio(
                            AudioResponseFormat.builder()
                                .bitRate(0)
                                .delivery(AudioResponseFormat.Delivery.INLINE)
                                .mimeType(AudioResponseFormat.MimeType.AUDIO_MP3)
                                .sampleRate(0)
                                .build()
                        )
                    )
                )
            )
        assertThat(createModelInteractionParams.responseMimeType()).contains("response_mime_type")
        assertThat(createModelInteractionParams.responseModalities().getOrNull())
            .containsExactly(CreateModelInteractionParams.ResponseModality.TEXT)
        assertThat(createModelInteractionParams.role()).contains("role")
        assertThat(createModelInteractionParams.serviceTier())
            .contains(CreateModelInteractionParams.ServiceTier.FLEX)
        assertThat(createModelInteractionParams.status())
            .contains(CreateModelInteractionParams.Status.IN_PROGRESS)
        assertThat(createModelInteractionParams.store()).contains(true)
        assertThat(createModelInteractionParams.stream()).contains(true)
        assertThat(createModelInteractionParams.systemInstruction()).contains("system_instruction")
        assertThat(createModelInteractionParams.tools().getOrNull())
            .containsExactly(
                Tool.ofFunction(
                    Function.builder()
                        .description("description")
                        .name("name")
                        .parameters(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
            )
        assertThat(createModelInteractionParams.updated())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(createModelInteractionParams.usage())
            .contains(
                Usage.builder()
                    .addCachedTokensByModality(
                        Usage.CachedTokensByModality.builder()
                            .modality(Usage.CachedTokensByModality.Modality.TEXT)
                            .tokens(0)
                            .build()
                    )
                    .addGroundingToolCount(
                        Usage.GroundingToolCount.builder()
                            .count(0)
                            .type(Usage.GroundingToolCount.Type.GOOGLE_SEARCH)
                            .build()
                    )
                    .addInputTokensByModality(
                        Usage.InputTokensByModality.builder()
                            .modality(Usage.InputTokensByModality.Modality.TEXT)
                            .tokens(0)
                            .build()
                    )
                    .addOutputTokensByModality(
                        Usage.OutputTokensByModality.builder()
                            .modality(Usage.OutputTokensByModality.Modality.TEXT)
                            .tokens(0)
                            .build()
                    )
                    .addToolUseTokensByModality(
                        Usage.ToolUseTokensByModality.builder()
                            .modality(Usage.ToolUseTokensByModality.Modality.TEXT)
                            .tokens(0)
                            .build()
                    )
                    .totalCachedTokens(0)
                    .totalInputTokens(0)
                    .totalOutputTokens(0)
                    .totalThoughtTokens(0)
                    .totalTokens(0)
                    .totalToolUseTokens(0)
                    .build()
            )
        assertThat(createModelInteractionParams.webhookConfig())
            .contains(
                CreateModelInteractionParams.WebhookConfig.builder()
                    .addUris("string")
                    .userMetadata(
                        CreateModelInteractionParams.WebhookConfig.UserMetadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val createModelInteractionParams =
            CreateModelInteractionParams.builder()
                .input(
                    TextContent.builder()
                        .text("text")
                        .addAnnotation(
                            UrlCitation.builder()
                                .endIndex(0)
                                .startIndex(0)
                                .title("title")
                                .url("url")
                                .build()
                        )
                        .build()
                )
                .model(Model.GEMINI_2_5_COMPUTER_USE_PREVIEW_10_2025)
                .id("id")
                .background(true)
                .created(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .generationConfig(
                    GenerationConfig.builder()
                        .imageConfig(
                            ImageConfig.builder()
                                .aspectRatio(ImageConfig.AspectRatio._1_1)
                                .imageSize(ImageConfig.ImageSize._1_K)
                                .build()
                        )
                        .maxOutputTokens(0)
                        .seed(0)
                        .addSpeechConfig(
                            SpeechConfig.builder()
                                .language("language")
                                .speaker("speaker")
                                .voice("voice")
                                .build()
                        )
                        .addStopSequence("string")
                        .temperature(0.0f)
                        .thinkingLevel(ThinkingLevel.MINIMAL)
                        .thinkingSummaries(GenerationConfig.ThinkingSummaries.AUTO)
                        .toolChoice(ToolChoiceType.AUTO)
                        .topP(0.0f)
                        .build()
                )
                .previousInteractionId("previous_interaction_id")
                .responseFormatOfList(
                    listOf(
                        CreateModelInteractionParams.ResponseFormat.InnerResponseFormat.ofAudio(
                            AudioResponseFormat.builder()
                                .bitRate(0)
                                .delivery(AudioResponseFormat.Delivery.INLINE)
                                .mimeType(AudioResponseFormat.MimeType.AUDIO_MP3)
                                .sampleRate(0)
                                .build()
                        )
                    )
                )
                .responseMimeType("response_mime_type")
                .addResponseModality(CreateModelInteractionParams.ResponseModality.TEXT)
                .role("role")
                .serviceTier(CreateModelInteractionParams.ServiceTier.FLEX)
                .status(CreateModelInteractionParams.Status.IN_PROGRESS)
                .store(true)
                .stream(true)
                .systemInstruction("system_instruction")
                .addTool(
                    Function.builder()
                        .description("description")
                        .name("name")
                        .parameters(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .updated(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .usage(
                    Usage.builder()
                        .addCachedTokensByModality(
                            Usage.CachedTokensByModality.builder()
                                .modality(Usage.CachedTokensByModality.Modality.TEXT)
                                .tokens(0)
                                .build()
                        )
                        .addGroundingToolCount(
                            Usage.GroundingToolCount.builder()
                                .count(0)
                                .type(Usage.GroundingToolCount.Type.GOOGLE_SEARCH)
                                .build()
                        )
                        .addInputTokensByModality(
                            Usage.InputTokensByModality.builder()
                                .modality(Usage.InputTokensByModality.Modality.TEXT)
                                .tokens(0)
                                .build()
                        )
                        .addOutputTokensByModality(
                            Usage.OutputTokensByModality.builder()
                                .modality(Usage.OutputTokensByModality.Modality.TEXT)
                                .tokens(0)
                                .build()
                        )
                        .addToolUseTokensByModality(
                            Usage.ToolUseTokensByModality.builder()
                                .modality(Usage.ToolUseTokensByModality.Modality.TEXT)
                                .tokens(0)
                                .build()
                        )
                        .totalCachedTokens(0)
                        .totalInputTokens(0)
                        .totalOutputTokens(0)
                        .totalThoughtTokens(0)
                        .totalTokens(0)
                        .totalToolUseTokens(0)
                        .build()
                )
                .webhookConfig(
                    CreateModelInteractionParams.WebhookConfig.builder()
                        .addUris("string")
                        .userMetadata(
                            CreateModelInteractionParams.WebhookConfig.UserMetadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedCreateModelInteractionParams =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(createModelInteractionParams),
                jacksonTypeRef<CreateModelInteractionParams>(),
            )

        assertThat(roundtrippedCreateModelInteractionParams).isEqualTo(createModelInteractionParams)
    }
}
