/*
* Copyright 2025 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

// File generated from our OpenAPI spec by Stainless.

package com.google.genai.interactions.models.interactions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.google.genai.interactions.core.JsonValue
import com.google.genai.interactions.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class InteractionTest {

    @Test
    fun create() {
        val interaction =
            Interaction.builder()
                .id("v1_ChdXS0l4YWZXTk9xbk0xZThQczhEcmlROBIXV0tJeGFmV05PcW5NMWU4UHM4RHJpUTg")
                .created(OffsetDateTime.parse("2025-12-04T15:01:45Z"))
                .status(Interaction.Status.COMPLETED)
                .addStep(
                    ModelOutputStep.builder()
                        .addContent(
                            TextContent.builder()
                                .text(
                                    "Hello! I'm doing well, functioning as expected. Thank you for asking! How are you doing today?"
                                )
                                .addAnnotation(
                                    UrlCitation.builder()
                                        .endIndex(0)
                                        .startIndex(0)
                                        .title("title")
                                        .url("url")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .updated(OffsetDateTime.parse("2025-12-04T15:01:45Z"))
                .agent(Interaction.Agent.DEEP_RESEARCH_PRO_PREVIEW_12_2025)
                .agentConfig(DynamicAgentConfig.builder().build())
                .generationConfig(
                    GenerationConfig.builder()
                        .imageConfig(
                            ImageConfig.builder()
                                .aspectRatio(ImageConfig.AspectRatio._1_1)
                                .imageSize(ImageConfig.ImageSize._1_K)
                                .build()
                        )
                        .maxOutputTokens(0)
                        .seed(0)
                        .addSpeechConfig(
                            SpeechConfig.builder()
                                .language("language")
                                .speaker("speaker")
                                .voice("voice")
                                .build()
                        )
                        .addStopSequence("string")
                        .temperature(0.0f)
                        .thinkingLevel(ThinkingLevel.MINIMAL)
                        .thinkingSummaries(GenerationConfig.ThinkingSummaries.AUTO)
                        .toolChoice(ToolChoiceType.AUTO)
                        .topP(0.0f)
                        .build()
                )
                .input(
                    TextContent.builder()
                        .text("text")
                        .addAnnotation(
                            UrlCitation.builder()
                                .endIndex(0)
                                .startIndex(0)
                                .title("title")
                                .url("url")
                                .build()
                        )
                        .build()
                )
                .model(Model.GEMINI_3_FLASH_PREVIEW)
                .previousInteractionId("previous_interaction_id")
                .responseFormatOfList(
                    listOf(
                        Interaction.ResponseFormat.InnerResponseFormat.ofAudio(
                            AudioResponseFormat.builder()
                                .bitRate(0)
                                .delivery(AudioResponseFormat.Delivery.INLINE)
                                .mimeType(AudioResponseFormat.MimeType.AUDIO_MP3)
                                .sampleRate(0)
                                .build()
                        )
                    )
                )
                .responseMimeType("response_mime_type")
                .addResponseModality(Interaction.ResponseModality.TEXT)
                .role("role")
                .serviceTier(Interaction.ServiceTier.FLEX)
                .systemInstruction("system_instruction")
                .addTool(
                    Function.builder()
                        .description("description")
                        .name("name")
                        .parameters(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .usage(
                    Usage.builder()
                        .addCachedTokensByModality(
                            Usage.CachedTokensByModality.builder()
                                .modality(Usage.CachedTokensByModality.Modality.TEXT)
                                .tokens(0)
                                .build()
                        )
                        .addGroundingToolCount(
                            Usage.GroundingToolCount.builder()
                                .count(0)
                                .type(Usage.GroundingToolCount.Type.GOOGLE_SEARCH)
                                .build()
                        )
                        .addInputTokensByModality(
                            Usage.InputTokensByModality.builder()
                                .modality(Usage.InputTokensByModality.Modality.TEXT)
                                .tokens(7)
                                .build()
                        )
                        .addOutputTokensByModality(
                            Usage.OutputTokensByModality.builder()
                                .modality(Usage.OutputTokensByModality.Modality.TEXT)
                                .tokens(0)
                                .build()
                        )
                        .addToolUseTokensByModality(
                            Usage.ToolUseTokensByModality.builder()
                                .modality(Usage.ToolUseTokensByModality.Modality.TEXT)
                                .tokens(0)
                                .build()
                        )
                        .totalCachedTokens(0)
                        .totalInputTokens(7)
                        .totalOutputTokens(23)
                        .totalThoughtTokens(49)
                        .totalTokens(79)
                        .totalToolUseTokens(0)
                        .build()
                )
                .webhookConfig(
                    Interaction.WebhookConfig.builder()
                        .addUris("string")
                        .userMetadata(
                            Interaction.WebhookConfig.UserMetadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(interaction.id())
            .isEqualTo("v1_ChdXS0l4YWZXTk9xbk0xZThQczhEcmlROBIXV0tJeGFmV05PcW5NMWU4UHM4RHJpUTg")
        assertThat(interaction.created()).isEqualTo(OffsetDateTime.parse("2025-12-04T15:01:45Z"))
        assertThat(interaction.status()).isEqualTo(Interaction.Status.COMPLETED)
        assertThat(interaction.steps())
            .containsExactly(
                Step.ofModelOutput(
                    ModelOutputStep.builder()
                        .addContent(
                            TextContent.builder()
                                .text(
                                    "Hello! I'm doing well, functioning as expected. Thank you for asking! How are you doing today?"
                                )
                                .addAnnotation(
                                    UrlCitation.builder()
                                        .endIndex(0)
                                        .startIndex(0)
                                        .title("title")
                                        .url("url")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
            )
        assertThat(interaction.updated()).isEqualTo(OffsetDateTime.parse("2025-12-04T15:01:45Z"))
        assertThat(interaction.agent())
            .contains(Interaction.Agent.DEEP_RESEARCH_PRO_PREVIEW_12_2025)
        assertThat(interaction.agentConfig())
            .contains(Interaction.AgentConfig.ofDynamic(DynamicAgentConfig.builder().build()))
        assertThat(interaction.generationConfig())
            .contains(
                GenerationConfig.builder()
                    .imageConfig(
                        ImageConfig.builder()
                            .aspectRatio(ImageConfig.AspectRatio._1_1)
                            .imageSize(ImageConfig.ImageSize._1_K)
                            .build()
                    )
                    .maxOutputTokens(0)
                    .seed(0)
                    .addSpeechConfig(
                        SpeechConfig.builder()
                            .language("language")
                            .speaker("speaker")
                            .voice("voice")
                            .build()
                    )
                    .addStopSequence("string")
                    .temperature(0.0f)
                    .thinkingLevel(ThinkingLevel.MINIMAL)
                    .thinkingSummaries(GenerationConfig.ThinkingSummaries.AUTO)
                    .toolChoice(ToolChoiceType.AUTO)
                    .topP(0.0f)
                    .build()
            )
        assertThat(interaction.input())
            .contains(
                Interaction.Input.ofTextContent(
                    TextContent.builder()
                        .text("text")
                        .addAnnotation(
                            UrlCitation.builder()
                                .endIndex(0)
                                .startIndex(0)
                                .title("title")
                                .url("url")
                                .build()
                        )
                        .build()
                )
            )
        assertThat(interaction.model()).contains(Model.GEMINI_3_FLASH_PREVIEW)
        assertThat(interaction.previousInteractionId()).contains("previous_interaction_id")
        assertThat(interaction.responseFormat())
            .contains(
                Interaction.ResponseFormat.ofList(
                    listOf(
                        Interaction.ResponseFormat.InnerResponseFormat.ofAudio(
                            AudioResponseFormat.builder()
                                .bitRate(0)
                                .delivery(AudioResponseFormat.Delivery.INLINE)
                                .mimeType(AudioResponseFormat.MimeType.AUDIO_MP3)
                                .sampleRate(0)
                                .build()
                        )
                    )
                )
            )
        assertThat(interaction.responseMimeType()).contains("response_mime_type")
        assertThat(interaction.responseModalities().getOrNull())
            .containsExactly(Interaction.ResponseModality.TEXT)
        assertThat(interaction.role()).contains("role")
        assertThat(interaction.serviceTier()).contains(Interaction.ServiceTier.FLEX)
        assertThat(interaction.systemInstruction()).contains("system_instruction")
        assertThat(interaction.tools().getOrNull())
            .containsExactly(
                Tool.ofFunction(
                    Function.builder()
                        .description("description")
                        .name("name")
                        .parameters(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
            )
        assertThat(interaction.usage())
            .contains(
                Usage.builder()
                    .addCachedTokensByModality(
                        Usage.CachedTokensByModality.builder()
                            .modality(Usage.CachedTokensByModality.Modality.TEXT)
                            .tokens(0)
                            .build()
                    )
                    .addGroundingToolCount(
                        Usage.GroundingToolCount.builder()
                            .count(0)
                            .type(Usage.GroundingToolCount.Type.GOOGLE_SEARCH)
                            .build()
                    )
                    .addInputTokensByModality(
                        Usage.InputTokensByModality.builder()
                            .modality(Usage.InputTokensByModality.Modality.TEXT)
                            .tokens(7)
                            .build()
                    )
                    .addOutputTokensByModality(
                        Usage.OutputTokensByModality.builder()
                            .modality(Usage.OutputTokensByModality.Modality.TEXT)
                            .tokens(0)
                            .build()
                    )
                    .addToolUseTokensByModality(
                        Usage.ToolUseTokensByModality.builder()
                            .modality(Usage.ToolUseTokensByModality.Modality.TEXT)
                            .tokens(0)
                            .build()
                    )
                    .totalCachedTokens(0)
                    .totalInputTokens(7)
                    .totalOutputTokens(23)
                    .totalThoughtTokens(49)
                    .totalTokens(79)
                    .totalToolUseTokens(0)
                    .build()
            )
        assertThat(interaction.webhookConfig())
            .contains(
                Interaction.WebhookConfig.builder()
                    .addUris("string")
                    .userMetadata(
                        Interaction.WebhookConfig.UserMetadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val interaction =
            Interaction.builder()
                .id("v1_ChdXS0l4YWZXTk9xbk0xZThQczhEcmlROBIXV0tJeGFmV05PcW5NMWU4UHM4RHJpUTg")
                .created(OffsetDateTime.parse("2025-12-04T15:01:45Z"))
                .status(Interaction.Status.COMPLETED)
                .addStep(
                    ModelOutputStep.builder()
                        .addContent(
                            TextContent.builder()
                                .text(
                                    "Hello! I'm doing well, functioning as expected. Thank you for asking! How are you doing today?"
                                )
                                .addAnnotation(
                                    UrlCitation.builder()
                                        .endIndex(0)
                                        .startIndex(0)
                                        .title("title")
                                        .url("url")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .updated(OffsetDateTime.parse("2025-12-04T15:01:45Z"))
                .agent(Interaction.Agent.DEEP_RESEARCH_PRO_PREVIEW_12_2025)
                .agentConfig(DynamicAgentConfig.builder().build())
                .generationConfig(
                    GenerationConfig.builder()
                        .imageConfig(
                            ImageConfig.builder()
                                .aspectRatio(ImageConfig.AspectRatio._1_1)
                                .imageSize(ImageConfig.ImageSize._1_K)
                                .build()
                        )
                        .maxOutputTokens(0)
                        .seed(0)
                        .addSpeechConfig(
                            SpeechConfig.builder()
                                .language("language")
                                .speaker("speaker")
                                .voice("voice")
                                .build()
                        )
                        .addStopSequence("string")
                        .temperature(0.0f)
                        .thinkingLevel(ThinkingLevel.MINIMAL)
                        .thinkingSummaries(GenerationConfig.ThinkingSummaries.AUTO)
                        .toolChoice(ToolChoiceType.AUTO)
                        .topP(0.0f)
                        .build()
                )
                .input(
                    TextContent.builder()
                        .text("text")
                        .addAnnotation(
                            UrlCitation.builder()
                                .endIndex(0)
                                .startIndex(0)
                                .title("title")
                                .url("url")
                                .build()
                        )
                        .build()
                )
                .model(Model.GEMINI_3_FLASH_PREVIEW)
                .previousInteractionId("previous_interaction_id")
                .responseFormatOfList(
                    listOf(
                        Interaction.ResponseFormat.InnerResponseFormat.ofAudio(
                            AudioResponseFormat.builder()
                                .bitRate(0)
                                .delivery(AudioResponseFormat.Delivery.INLINE)
                                .mimeType(AudioResponseFormat.MimeType.AUDIO_MP3)
                                .sampleRate(0)
                                .build()
                        )
                    )
                )
                .responseMimeType("response_mime_type")
                .addResponseModality(Interaction.ResponseModality.TEXT)
                .role("role")
                .serviceTier(Interaction.ServiceTier.FLEX)
                .systemInstruction("system_instruction")
                .addTool(
                    Function.builder()
                        .description("description")
                        .name("name")
                        .parameters(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .usage(
                    Usage.builder()
                        .addCachedTokensByModality(
                            Usage.CachedTokensByModality.builder()
                                .modality(Usage.CachedTokensByModality.Modality.TEXT)
                                .tokens(0)
                                .build()
                        )
                        .addGroundingToolCount(
                            Usage.GroundingToolCount.builder()
                                .count(0)
                                .type(Usage.GroundingToolCount.Type.GOOGLE_SEARCH)
                                .build()
                        )
                        .addInputTokensByModality(
                            Usage.InputTokensByModality.builder()
                                .modality(Usage.InputTokensByModality.Modality.TEXT)
                                .tokens(7)
                                .build()
                        )
                        .addOutputTokensByModality(
                            Usage.OutputTokensByModality.builder()
                                .modality(Usage.OutputTokensByModality.Modality.TEXT)
                                .tokens(0)
                                .build()
                        )
                        .addToolUseTokensByModality(
                            Usage.ToolUseTokensByModality.builder()
                                .modality(Usage.ToolUseTokensByModality.Modality.TEXT)
                                .tokens(0)
                                .build()
                        )
                        .totalCachedTokens(0)
                        .totalInputTokens(7)
                        .totalOutputTokens(23)
                        .totalThoughtTokens(49)
                        .totalTokens(79)
                        .totalToolUseTokens(0)
                        .build()
                )
                .webhookConfig(
                    Interaction.WebhookConfig.builder()
                        .addUris("string")
                        .userMetadata(
                            Interaction.WebhookConfig.UserMetadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedInteraction =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(interaction),
                jacksonTypeRef<Interaction>(),
            )

        assertThat(roundtrippedInteraction).isEqualTo(interaction)
    }
}
