/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.google.genai.gaos.models.environments;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.genai.gaos.utils.Utils;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;

/**
 * ListEnvironmentsResponse
 *
 * <p>Response for `ListEnvironments`.
 */
public class ListEnvironmentsResponse {
    /**
     * Environments belonging to the provided project.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("environments")
    private List<Environment> environments;

    /**
     * Pagination token.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("next_page_token")
    private String nextPageToken;

    @JsonCreator
    public ListEnvironmentsResponse(
            @JsonProperty("environments") @Nullable List<Environment> environments,
            @JsonProperty("next_page_token") @Nullable String nextPageToken) {
        this.environments = environments;
        this.nextPageToken = nextPageToken;
    }

    public ListEnvironmentsResponse() {
        this(null, null);
    }

    /**
     * Environments belonging to the provided project.
     */
    public Optional<List<Environment>> environments() {
        return Optional.ofNullable(this.environments);
    }

    /**
     * Pagination token.
     */
    public Optional<String> nextPageToken() {
        return Optional.ofNullable(this.nextPageToken);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * Environments belonging to the provided project.
     */
    public ListEnvironmentsResponse withEnvironments(@Nullable List<Environment> environments) {
        this.environments = environments;
        return this;
    }

    /**
     * Pagination token.
     */
    public ListEnvironmentsResponse withNextPageToken(@Nullable String nextPageToken) {
        this.nextPageToken = nextPageToken;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListEnvironmentsResponse other = (ListEnvironmentsResponse) o;
        return Utils.enhancedDeepEquals(this.environments, other.environments)
                && Utils.enhancedDeepEquals(this.nextPageToken, other.nextPageToken);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(environments, nextPageToken);
    }

    @Override
    public String toString() {
        return Utils.toString(
                ListEnvironmentsResponse.class, "environments", environments, "nextPageToken", nextPageToken);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private List<Environment> environments;

        private String nextPageToken;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * Environments belonging to the provided project.
         */
        public Builder environments(@Nullable List<Environment> environments) {
            this.environments = environments;
            return this;
        }

        /**
         * Pagination token.
         */
        public Builder nextPageToken(@Nullable String nextPageToken) {
            this.nextPageToken = nextPageToken;
            return this;
        }

        public ListEnvironmentsResponse build() {
            return new ListEnvironmentsResponse(environments, nextPageToken);
        }
    }
}
