name: Pre-release Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_name == 'release-please--branches--main' || github.head_ref == 'release-please--branches--main'
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      with:
        persist-credentials: false
    - uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
    - name: Install Root
      run: mvn -B -ntp install -DskipTests -Djacoco.skip=true -Dclirr.skip=true
    - name: Compile Examples
      run: mvn -B -ntp compile -f examples/pom.xml
    - name: Generate Javadoc
      run: mvn -B -ntp package -DperformRelease=true -DskipTests -Djacoco.skip=true -Dclirr.skip=true
