name: Publish Javadoc

on:
  push:
    branches:
      - test-publish-doc

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v3.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: gh-pages
          java-version: 17
          target-folder: javadoc
          project: maven
          custom-command: mvn javadoc:javadoc
